/* AUTOMOTRIZ — 4 rubros. */
const CAT = 'Automotriz';

module.exports = [
  /* Taller mecánico */
  {
    slug: 'taller', category: CAT, label: 'Taller mecánico', brand: 'AutoFix Taller',
    fonts: { heading: 'Oswald', body: 'Inter' },
    palette: { primary: '#C8451F', secondary: '#1E1A18', accent: '#F0A030', bg: '#F6F5F3', text: '#1E1A18' },
    plan: ['nav', 'heroSplit', 'stats', 'servicesGrid', 'process', 'testimonials', 'ctaBanner', 'contact', 'footer'],
    nav: ['Inicio', 'Servicios', 'Proceso', 'Contacto'], navCta: 'Agenda tu cita',
    eyebrow: 'Taller mecánico · Lima', h1: 'Tu auto en manos expertas', sub: 'Mantenimiento y reparación con diagnóstico honesto, repuestos de calidad y garantía. Te explicamos todo en simple.',
    cta1: 'Agenda tu cita', cta2: 'Ver servicios', heroPills: ['Diagnóstico honesto', 'Garantía por escrito'],
    stats: [{ n: '20 años', l: 'de experiencia' }, { n: '30,000+', l: 'autos atendidos' }, { n: 'Todas', l: 'las marcas' }, { n: '4.9★', l: 'clientes' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Todo para tu vehículo',
    services: [{ t: 'Mantenimiento preventivo', d: 'Cambio de aceite, filtros y revisión general.' }, { t: 'Mecánica general', d: 'Motor, frenos, suspensión y transmisión.' }, { t: 'Diagnóstico computarizado', d: 'Detectamos fallas con escáner profesional.' }, { t: 'Sistema eléctrico', d: 'Batería, alternador y electrónica.' }, { t: 'Aire acondicionado', d: 'Recarga y reparación del clima.' }, { t: 'Planchado y pintura', d: 'Dejamos tu auto como nuevo.' }],
    processTitle: 'Cómo trabajamos',
    process: [{ t: 'Diagnóstico', d: 'Revisamos y te explicamos qué necesita.' }, { t: 'Cotización', d: 'Precio claro antes de empezar, sin sorpresas.' }, { t: 'Reparación', d: 'Trabajamos con repuestos de calidad.' }, { t: 'Garantía', d: 'Entregamos con garantía por escrito.' }],
    testiTitle: 'Lo que dicen nuestros clientes',
    testimonials: [{ q: 'Por fin un taller honesto que no te infla la cuenta. Confío ciegamente.', n: 'Manuel Reátegui', r: 'Cliente' }, { q: 'Diagnóstico rápido, precio justo y mi auto quedó perfecto. Recomendados.', n: 'Sergio Ldomas', r: 'Cliente' }, { q: 'Me explicaron todo con paciencia y cumplieron el plazo. Excelentes.', n: 'Carla Bendezú', r: 'Cliente' }],
    ctaTitle: '¿Tu auto necesita revisión?', ctaSub: 'Escríbenos por WhatsApp y agenda tu cita hoy mismo.',
    contactTitle: 'Agenda tu cita', contactSub: 'Cuéntanos qué necesita tu auto y te atendemos pronto.',
    phone: '+51 945 220 660', address: 'Av. Nicolás Arriola 1820, La Victoria, Lima', hours: 'Lun–Sáb · 8:00 – 18:00', contactCta: 'Agendar cita', email: 'citas@autofix.pe',
    footerAbout: 'Taller mecánico en Lima con 20 años de experiencia. Diagnóstico honesto, repuestos de calidad y garantía.',
    whatsappHref: 'https://wa.me/51945220660',
    pexels: { hero: 'car mechanic auto repair shop', about: 'mechanic working on car engine' },
  },

  /* Venta de autos / concesionario */
  {
    slug: 'autos', category: CAT, label: 'Venta de autos', brand: 'AutoPrime',
    fonts: { heading: 'Sora', body: 'Inter' },
    palette: { primary: '#1A2A4A', secondary: '#14213B', accent: '#C8A45C', bg: '#F6F8FB', text: '#16202E' },
    plan: ['nav', 'heroFullBg', 'stats', 'cards', 'servicesGrid', 'testimonials', 'ctaBanner', 'contact', 'footer'],
    nav: ['Inicio', 'Vehículos', 'Servicios', 'Contacto'], navCta: 'Agenda tu prueba',
    eyebrow: 'Concesionario · Lima', h1: 'Encuentra el auto perfecto para ti', sub: 'Vehículos nuevos y seminuevos garantizados, financiamiento a tu medida y la asesoría honesta que mereces.',
    cta1: 'Ver vehículos', cta2: 'Agenda prueba de manejo',
    stats: [{ n: '2,000+', l: 'autos vendidos' }, { n: '100%', l: 'garantizados' }, { n: 'Crédito', l: 'aprobación rápida' }, { n: '4.8★', l: 'clientes' }],
    cardsEyebrow: 'Stock disponible', cardsTitle: 'Vehículos destacados', cardsCta: 'Ver detalle',
    cards: [{ tag: 'Nuevo', t: 'SUV Familiar 2024', d: 'Full equipo · automático · garantía', p: 'US$ 28,900' }, { tag: 'Seminuevo', t: 'Sedán Ejecutivo 2022', d: '45,000 km · impecable · único dueño', p: 'US$ 18,500' }, { t: 'Hatchback 2023', d: 'Ideal ciudad · bajo consumo', p: 'US$ 15,900' }, { tag: 'Oferta', t: 'Camioneta 4x4 2021', d: 'Robusta · lista para la aventura', p: 'US$ 32,000' }, { t: 'City Car 2024', d: 'Económico y ágil', p: 'US$ 13,500' }, { t: 'Pickup de trabajo', d: 'Para tu negocio, rendidora', p: 'US$ 21,000' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Compra con confianza',
    services: [{ t: 'Financiamiento', d: 'Crédito vehicular con aprobación rápida.' }, { t: 'Parte de pago', d: 'Recibimos tu auto usado.' }, { t: 'Garantía y postventa', d: 'Respaldo y servicio técnico.' }],
    ctaTitle: '¿Listo para estrenar?', ctaSub: 'Escríbenos por WhatsApp y agenda tu prueba de manejo sin compromiso.',
    contactTitle: 'Agenda tu prueba de manejo', contactSub: 'Cuéntanos qué buscas y te mostramos las mejores opciones.',
    phone: '+51 1 488 6060', address: 'Av. Javier Prado Este 4200, Surco, Lima', hours: 'Lun–Dom · 9:00 – 20:00', contactCta: 'Agendar prueba', email: 'ventas@autoprime.pe',
    footerAbout: 'Concesionario en Lima. Autos nuevos y seminuevos garantizados con financiamiento a tu medida.',
    whatsappHref: 'https://wa.me/5114886060',
    pexels: { hero: 'car dealership showroom modern', cards: ['suv car modern', 'sedan car luxury', 'hatchback car', 'pickup truck 4x4', 'compact city car', 'pickup work truck'] },
  },

  /* Autodetailing / lavado */
  {
    slug: 'autolavado', category: CAT, label: 'Autolavado / Detailing', brand: 'Brilla Auto Spa',
    fonts: { heading: 'Sora', body: 'Inter' },
    palette: { primary: '#1E9BB0', secondary: '#14333A', accent: '#F0A030', bg: '#F4FBFB', text: '#16292F' },
    plan: ['nav', 'heroFullBg', 'stats', 'servicesGrid', 'gallery', 'pricing', 'testimonials', 'contact', 'footer'],
    nav: ['Inicio', 'Servicios', 'Galería', 'Precios', 'Contacto'], navCta: 'Reservar',
    eyebrow: 'Auto detailing · Lima', h1: 'Tu auto, reluciente como nuevo', sub: 'Lavado premium y detailing profesional. Cuidamos cada detalle de tu vehículo por dentro y por fuera.',
    cta1: 'Reserva tu lavado', cta2: 'Ver servicios',
    stats: [{ n: '50,000+', l: 'autos relucientes' }, { n: 'Premium', l: 'productos importados' }, { n: 'Express', l: 'o detailing full' }, { n: '4.9★', l: 'clientes' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Cuidado profesional para tu auto',
    services: [{ t: 'Lavado premium', d: 'Exterior e interior con productos de calidad.' }, { t: 'Detailing completo', d: 'Restauración estética total de tu vehículo.' }, { t: 'Pulido y encerado', d: 'Brillo y protección para tu pintura.' }, { t: 'Limpieza de tapiz', d: 'Asientos y tableros como nuevos.' }, { t: 'Tratamiento cerámico', d: 'Protección de larga duración.' }, { t: 'Lavado de motor', d: 'Limpieza segura del compartimiento.' }],
    galleryEyebrow: 'Galería', galleryTitle: 'El antes y después habla',
    pricingTitle: 'Nuestros precios',
    pricing: [{ name: 'Lavado Express', price: 'S/ 35', per: '', feats: ['Exterior e interior', 'Aspirado', 'Aromatizante'], cta: 'Reservar' }, { name: 'Detailing Full', price: 'S/ 180', per: '', feats: ['Lavado premium', 'Pulido y encerado', 'Limpieza profunda interior', 'Tratamiento de plásticos'], featured: true, cta: 'Reservar' }, { name: 'Cerámico', price: 'S/ 450', per: '', feats: ['Tratamiento cerámico', 'Protección 1 año', 'Brillo espejo'], cta: 'Reservar' }],
    testiTitle: 'Lo que dicen nuestros clientes',
    testimonials: [{ q: 'Dejaron mi auto impecable, parecía recién salido de agencia. Brutales.', n: 'Diego Ramos', r: 'Cliente' }, { q: 'El detailing full vale cada sol. Atención y calidad de primera.', n: 'Lucía Tapia', r: 'Cliente' }, { q: 'El tratamiento cerámico es lo mejor que le hice a mi carro. Recomendados.', n: 'Andrés Pinto', r: 'Cliente' }],
    contactTitle: 'Reserva tu lavado', contactSub: 'Agenda por WhatsApp y deja tu auto reluciente.',
    phone: '+51 945 660 110', address: 'Av. Tomás Marsano 1450, Surco, Lima', hours: 'Lun–Dom · 8:00 – 20:00', contactCta: 'Reservar ahora', email: 'reservas@brillaautospa.pe',
    footerAbout: 'Autolavado y detailing en Surco. Cuidamos cada detalle de tu auto con productos premium.',
    whatsappHref: 'https://wa.me/51945660110',
    pexels: { hero: 'car wash detailing clean shiny', gallery: ['car wash foam', 'car detailing polish', 'clean car interior', 'car wax shine', 'car cleaning wheels', 'luxury car clean'] },
  },

  /* Escuela de manejo */
  {
    slug: 'manejo', category: CAT, label: 'Escuela de manejo', brand: 'Ruta Segura',
    fonts: { heading: 'Oswald', body: 'Inter' },
    palette: { primary: '#E0641E', secondary: '#2A2018', accent: '#1E63A8', bg: '#FBF7F0', text: '#2A2218' },
    plan: ['nav', 'heroSplit', 'stats', 'servicesGrid', 'process', 'pricing', 'testimonials', 'contact', 'footer'],
    nav: ['Inicio', 'Cursos', 'Proceso', 'Precios', 'Contacto'], navCta: 'Inscríbete',
    eyebrow: 'Escuela de manejo · Lima', h1: 'Aprende a manejar con seguridad y confianza', sub: 'Clases prácticas y teóricas con instructores pacientes y autos de doble comando. Saca tu brevete sin estrés.',
    cta1: 'Inscríbete ahora', cta2: 'Ver cursos', heroPills: ['Autos doble comando', 'Instructores certificados'],
    stats: [{ n: '12,000+', l: 'conductores formados' }, { n: '15 años', l: 'enseñando' }, { n: '95%', l: 'aprueba el examen' }, { n: '4.9★', l: 'alumnos' }],
    servicesEyebrow: 'Cursos', servicesTitle: 'Programas para cada conductor',
    services: [{ t: 'Curso para principiantes', d: 'Desde cero hasta manejar con seguridad.' }, { t: 'Clases de reforzamiento', d: 'Para quienes ya saben pero quieren practicar.' }, { t: 'Manejo defensivo', d: 'Anticipa riesgos y conduce seguro.' }, { t: 'Preparación de brevete', d: 'Teoría y práctica para aprobar el examen.' }],
    processTitle: 'Tu camino al volante',
    process: [{ t: 'Inscripción', d: 'Elige tu paquete y horario flexible.' }, { t: 'Teoría', d: 'Aprende reglas y señales de tránsito.' }, { t: 'Práctica', d: 'Manejas con instructor en doble comando.' }, { t: 'Brevete', d: 'Te preparamos para aprobar tu examen.' }],
    pricingTitle: 'Paquetes',
    pricing: [{ name: 'Básico', price: 'S/ 290', per: '', feats: ['6 clases prácticas', 'Material teórico', 'Auto doble comando'], cta: 'Inscribirme' }, { name: 'Completo', price: 'S/ 450', per: '', feats: ['12 clases prácticas', 'Teoría completa', 'Simulacro de examen', 'Apoyo para brevete'], featured: true, cta: 'Inscribirme' }, { name: 'Reforzamiento', price: 'S/ 45', per: '/clase', feats: ['Clase individual', 'Horario flexible', 'Práctica en ruta'], cta: 'Inscribirme' }],
    testiTitle: 'Conductores que confiaron en nosotros',
    testimonials: [{ q: 'Le tenía miedo a manejar y ahora conduzco tranquila. Instructores muy pacientes.', n: 'Gabriela Ñope', r: 'Alumna' }, { q: 'Aprobé mi brevete a la primera. La preparación fue clave. Gracias.', n: 'Renzo Aliaga', r: 'Alumno' }, { q: 'Excelente metodología y autos cómodos. 100% recomendado.', n: 'Mauricio Lévano', r: 'Alumno' }],
    contactTitle: 'Inscríbete hoy', contactSub: 'Empieza a manejar con seguridad. Reserva tu cupo.',
    phone: '+51 945 880 660', address: 'Av. Brasil 980, Breña, Lima', hours: 'Lun–Sáb · 8:00 – 20:00', contactCta: 'Quiero inscribirme', email: 'informes@rutasegura.pe',
    footerAbout: 'Escuela de manejo en Lima. Instructores pacientes y autos de doble comando para que manejes con confianza.',
    whatsappHref: 'https://wa.me/51945880660',
    pexels: { hero: 'driving lesson car instructor', about: 'driving school student car' },
  },
];
