/* BELLEZA Y CUIDADO PERSONAL — 3 rubros. */
const CAT = 'Belleza y cuidado personal';

module.exports = [
  /* Barbería */
  {
    slug: 'barberia', category: CAT, label: 'Barbería', brand: 'The Barber Club',
    fonts: { heading: 'Oswald', body: 'Inter' },
    palette: { primary: '#2A2420', secondary: '#16120E', accent: '#B8863C', bg: '#F4F1EC', text: '#221E18' },
    plan: ['nav', 'heroFullBg', 'stats', 'servicesGrid', 'gallery', 'pricing', 'testimonials', 'contact', 'footer'],
    nav: ['Inicio', 'Servicios', 'Galería', 'Precios', 'Contacto'], navCta: 'Reservar turno',
    eyebrow: 'Barbería · Lima', h1: 'Estilo que se nota', sub: 'Cortes clásicos y modernos, afeitado a navaja y el ritual completo del caballero. Tu mejor versión empieza aquí.',
    cta1: 'Reserva tu turno', cta2: 'Ver servicios',
    stats: [{ n: '15,000+', l: 'cortes al año' }, { n: '8 años', l: 'marcando estilo' }, { n: '6', l: 'barberos expertos' }, { n: '4.9★', l: 'clientes' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'El ritual completo del caballero',
    services: [{ t: 'Corte de cabello', d: 'Clásico o moderno, a tu estilo.' }, { t: 'Afeitado a navaja', d: 'El ritual tradicional con toalla caliente.' }, { t: 'Perfilado de barba', d: 'Diseño y arreglo profesional de barba.' }, { t: 'Corte + barba', d: 'El combo completo para lucir impecable.' }, { t: 'Tinte y diseños', d: 'Color y líneas personalizadas.' }, { t: 'Tratamiento facial', d: 'Limpieza e hidratación para hombres.' }],
    galleryEyebrow: 'Galería', galleryTitle: 'Nuestro trabajo habla',
    pricingTitle: 'Nuestros precios',
    pricing: [{ name: 'Corte', price: 'S/ 35', per: '', feats: ['Corte a tu estilo', 'Lavado incluido', 'Peinado final'], cta: 'Reservar' }, { name: 'Corte + Barba', price: 'S/ 55', per: '', feats: ['Corte completo', 'Perfilado de barba', 'Toalla caliente', 'Bebida de cortesía'], featured: true, cta: 'Reservar' }, { name: 'Afeitado clásico', price: 'S/ 30', per: '', feats: ['Afeitado a navaja', 'Toalla caliente', 'Bálsamo post-afeitado'], cta: 'Reservar' }],
    testiTitle: 'Lo que dicen los clientes',
    testimonials: [{ q: 'El mejor corte que me han hecho. Ambiente top y atención de primera.', n: 'Renato Gómez', r: 'Cliente' }, { q: 'El afeitado a navaja es otro nivel. Me siento como nuevo cada vez.', n: 'Aldo Ferrer', r: 'Cliente frecuente' }, { q: 'Por fin una barbería que entiende lo que pido. Recomendadísima.', n: 'Piero Salas', r: 'Cliente' }],
    contactTitle: 'Reserva tu turno', contactSub: 'Agenda por WhatsApp y evita la espera.',
    phone: '+51 945 220 110', address: 'Av. Larco 540, Miraflores, Lima', hours: 'Lun–Sáb · 10:00 – 21:00', contactCta: 'Reservar turno', email: 'turnos@thebarberclub.pe',
    footerAbout: 'Barbería en Miraflores. Cortes, afeitado a navaja y el ritual completo del caballero.',
    whatsappHref: 'https://wa.me/51945220110',
    pexels: { hero: 'barbershop haircut man styling', gallery: ['barber haircut man', 'beard trimming barber', 'barbershop interior', 'man haircut style', 'straight razor shave', 'barber tools'] },
  },

  /* Salón de belleza / spa */
  {
    slug: 'belleza', category: CAT, label: 'Salón de belleza', brand: 'Bellísima Salón',
    fonts: { heading: 'Cormorant Garamond', body: 'Jost' },
    palette: { primary: '#D14E8C', secondary: '#2E1A28', accent: '#E0A0C0', bg: '#FBF5F8', text: '#2A1E26' },
    plan: ['nav', 'heroFullBg', 'stats', 'servicesGrid', 'gallery', 'pricing', 'testimonials', 'contact', 'footer'],
    nav: ['Inicio', 'Servicios', 'Galería', 'Precios', 'Contacto'], navCta: 'Reservar cita',
    eyebrow: 'Salón de belleza · Lima', h1: 'Realza tu belleza, brilla como mereces', sub: 'Cabello, maquillaje y tratamientos en un solo lugar. Expertas que te escuchan y te hacen sentir increíble.',
    cta1: 'Reserva tu cita', cta2: 'Ver servicios',
    stats: [{ n: '10,000+', l: 'clientas felices' }, { n: '12 años', l: 'de experiencia' }, { n: '15+', l: 'servicios' }, { n: '4.9★', l: 'valoración' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Todo para verte y sentirte bien',
    services: [{ t: 'Corte y peinado', d: 'Cortes a tu estilo y peinados para toda ocasión.' }, { t: 'Color y mechas', d: 'Coloración, balayage y looks de tendencia.' }, { t: 'Tratamientos capilares', d: 'Keratina, botox capilar y nutrición profunda.' }, { t: 'Maquillaje', d: 'Social, de novia y para eventos.' }, { t: 'Manicure y pedicure', d: 'Uñas impecables, esmaltado y nail art.' }, { t: 'Cejas y pestañas', d: 'Diseño de cejas y lifting de pestañas.' }],
    galleryEyebrow: 'Galería', galleryTitle: 'Transformaciones que enamoran',
    pricingTitle: 'Paquetes destacados',
    pricing: [{ name: 'Look del día', price: 'S/ 90', per: '', feats: ['Lavado y corte', 'Peinado', 'Asesoría de imagen'], cta: 'Reservar' }, { name: 'Pack Novia', price: 'S/ 450', per: '', feats: ['Prueba de maquillaje', 'Maquillaje y peinado', 'Manicure', 'Atención a domicilio'], featured: true, cta: 'Reservar' }, { name: 'Spa capilar', price: 'S/ 180', per: '', feats: ['Tratamiento profundo', 'Masaje capilar', 'Brushing final'], cta: 'Reservar' }],
    testiTitle: 'Lo que dicen nuestras clientas',
    testimonials: [{ q: 'Me hicieron el balayage de mis sueños. Salí feliz y me sentí hermosa.', n: 'Valentina Ríos', r: 'Cliente' }, { q: 'El maquillaje de mi boda fue perfecto y duró todo el día. Gracias.', n: 'Melissa Cuba', r: 'Novia' }, { q: 'Atención cálida y profesional. Mi salón de confianza siempre.', n: 'Karla Espinoza', r: 'Cliente frecuente' }],
    contactTitle: 'Reserva tu cita', contactSub: 'Agenda tu transformación. Te esperamos.',
    phone: '+51 956 330 770', address: 'Av. Benavides 1820, Miraflores, Lima', hours: 'Lun–Sáb · 9:00 – 20:00', contactCta: 'Reservar cita', email: 'citas@bellisimasalon.pe',
    footerAbout: 'Salón de belleza en Miraflores. Cabello, maquillaje y tratamientos para que brilles como mereces.',
    whatsappHref: 'https://wa.me/51956330770',
    pexels: { hero: 'beauty salon hair styling woman', gallery: ['hair salon styling', 'hair color balayage', 'makeup artist woman', 'manicure nails', 'salon interior modern', 'woman beautiful hair'] },
  },

  /* Nail salon / uñas */
  {
    slug: 'unas', category: CAT, label: 'Nail Salon / Uñas', brand: 'Nails Lab',
    fonts: { heading: 'Poppins', body: 'Inter' },
    palette: { primary: '#C86B8C', secondary: '#2A1A22', accent: '#E0B0C0', bg: '#FBF6F8', text: '#2A2026' },
    plan: ['nav', 'heroFullBg', 'stats', 'servicesGrid', 'gallery', 'pricing', 'testimonials', 'contact', 'footer'],
    nav: ['Inicio', 'Servicios', 'Galería', 'Precios', 'Contacto'], navCta: 'Reservar cita',
    eyebrow: 'Nail Salon · Lima', h1: 'Uñas perfectas, siempre', sub: 'Manicure, pedicure y nail art con los mejores productos. Diseños únicos que duran y enamoran.',
    cta1: 'Reserva tu cita', cta2: 'Ver diseños',
    stats: [{ n: '8,000+', l: 'manos felices' }, { n: '200+', l: 'diseños' }, { n: '3 semanas', l: 'de duración' }, { n: '4.9★', l: 'clientas' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Tus uñas en las mejores manos',
    services: [{ t: 'Manicure semipermanente', d: 'Color que dura semanas, impecable.' }, { t: 'Uñas acrílicas', d: 'Extensiones a tu largo y forma ideal.' }, { t: 'Soft gel', d: 'Naturales, resistentes y ligeras.' }, { t: 'Nail art', d: 'Diseños personalizados y de tendencia.' }, { t: 'Pedicure spa', d: 'Pies suaves y relajados.' }, { t: 'Retiro y reparación', d: 'Cuidamos la salud de tu uña natural.' }],
    galleryEyebrow: 'Galería', galleryTitle: 'Diseños que inspiran',
    pricingTitle: 'Nuestros precios',
    pricing: [{ name: 'Manicure semi', price: 'S/ 45', per: '', feats: ['Esmaltado semipermanente', 'Cutícula y limado', 'Color a elección'], cta: 'Reservar' }, { name: 'Acrílicas + diseño', price: 'S/ 90', per: '', feats: ['Extensión acrílica', 'Diseño personalizado', 'Decoración premium', 'Duración 3+ semanas'], featured: true, cta: 'Reservar' }, { name: 'Pedicure spa', price: 'S/ 55', per: '', feats: ['Exfoliación e hidratación', 'Esmaltado semi', 'Masaje relajante'], cta: 'Reservar' }],
    testiTitle: 'Lo que dicen nuestras clientas',
    testimonials: [{ q: 'Mis uñas quedaron preciosas y me duraron casi un mes. ¡Las amo!', n: 'Sthefany Lozano', r: 'Cliente' }, { q: 'Los diseños son arte puro. Salgo feliz cada vez que voy.', n: 'Brenda Cáceres', r: 'Cliente frecuente' }, { q: 'Súper limpias, puntuales y talentosas. Mi nail salon de confianza.', n: 'Lucero Díaz', r: 'Cliente' }],
    contactTitle: 'Reserva tu cita', contactSub: 'Agenda tu diseño favorito por WhatsApp.',
    phone: '+51 967 110 550', address: 'Av. Primavera 540, Surco, Lima', hours: 'Lun–Sáb · 10:00 – 20:00', contactCta: 'Reservar cita', email: 'citas@nailslab.pe',
    footerAbout: 'Nail salon en Surco. Manicure, acrílicas y nail art con diseños únicos que duran semanas.',
    whatsappHref: 'https://wa.me/51967110550',
    pexels: { hero: 'nail salon manicure design', gallery: ['manicure nail art', 'acrylic nails design', 'nail polish colorful', 'pedicure spa feet', 'nail salon interior', 'nails glitter design'] },
  },
];
