/* EDUCACIÓN — 5 rubros. */
const CAT = 'Educación';

module.exports = [
  /* Colegio / nido */
  {
    slug: 'colegio', category: CAT, label: 'Colegio / Nido', brand: 'Colegio Nuevo Horizonte',
    fonts: { heading: 'Poppins', body: 'Inter' },
    palette: { primary: '#1E63A8', secondary: '#14304A', accent: '#F0B030', bg: '#F6F9FC', text: '#18242E' },
    plan: ['nav', 'heroFullBg', 'stats', 'servicesGrid', 'featureSplit', 'gallery', 'testimonials', 'contact', 'footer'],
    nav: ['Inicio', 'Niveles', 'Nosotros', 'Galería', 'Contacto'], navCta: 'Solicita vacante',
    eyebrow: 'Educación · Lima', h1: 'Formamos a los líderes del mañana', sub: 'Educación integral con valores, tecnología e inglés. Un espacio donde tus hijos aprenden felices.',
    cta1: 'Solicita una vacante', cta2: 'Conoce el colegio',
    stats: [{ n: '30 años', l: 'formando personas' }, { n: '1,200+', l: 'alumnos' }, { n: 'Bilingüe', l: 'inglés intensivo' }, { n: '98%', l: 'ingreso a universidad' }],
    servicesEyebrow: 'Niveles', servicesTitle: 'Acompañamos cada etapa',
    services: [{ t: 'Inicial', d: 'Estimulación temprana en un entorno seguro y lúdico.' }, { t: 'Primaria', d: 'Bases sólidas en lectura, matemática y valores.' }, { t: 'Secundaria', d: 'Preparación académica y vocacional para la universidad.' }, { t: 'Programa bilingüe', d: 'Inglés intensivo certificado en todos los niveles.' }],
    aboutTitle: 'Una educación que va más allá de las notas', aboutBody: 'Creemos en formar personas íntegras, críticas y felices. Combinamos exigencia académica con educación emocional, deporte y arte, para que cada alumno descubra y desarrolle su máximo potencial.',
    aboutBullets: ['Docentes especializados y vocacionales', 'Aulas con tecnología y laboratorios', 'Deporte, arte y formación en valores'],
    galleryEyebrow: 'Nuestro campus', galleryTitle: 'Un lugar para crecer',
    testiTitle: 'Lo que dicen las familias',
    testimonials: [{ q: 'Mis hijos aman ir al colegio. El nivel académico y humano es excelente.', n: 'Familia Paredes', r: 'Padres de familia' }, { q: 'El inglés que reciben es real. Mi hija ya conversa con fluidez.', n: 'Gloria Marín', r: 'Madre de familia' }, { q: 'Más que un colegio, una segunda familia para nuestros hijos.', n: 'Familia Otárola', r: 'Padres de familia' }],
    contactTitle: 'Solicita una vacante', contactSub: 'Agenda una visita y conoce nuestra propuesta educativa.',
    phone: '+51 1 488 3030', address: 'Av. La Molina 2400, La Molina, Lima', hours: 'Lun–Vie · 7:30 – 16:00', contactCta: 'Solicitar vacante', email: 'admision@nuevohorizonte.edu.pe',
    footerAbout: 'Colegio bilingüe con 30 años formando personas íntegras, críticas y felices en La Molina.',
    whatsappHref: 'https://wa.me/5114883030',
    pexels: { hero: 'school children classroom learning', about: 'teacher students classroom', gallery: ['children school playground', 'classroom students', 'school library kids', 'students science lab', 'kids art class', 'school sports children'] },
  },

  /* Academia preuniversitaria / instituto */
  {
    slug: 'academia', category: CAT, label: 'Academia / Instituto', brand: 'Academia Élite',
    fonts: { heading: 'Sora', body: 'Inter' },
    palette: { primary: '#D23A2A', secondary: '#2A1614', accent: '#F0B030', bg: '#F8F6F4', text: '#221816' },
    plan: ['nav', 'heroSplit', 'stats', 'servicesGrid', 'process', 'testimonials', 'faq', 'contact', 'footer'],
    nav: ['Inicio', 'Programas', 'Metodología', 'Contacto'], navCta: 'Inscríbete ahora',
    eyebrow: 'Preparación · Lima', h1: 'Tu ingreso a la universidad empieza aquí', sub: 'Preparación preuniversitaria con los mejores profesores y una metodología que sí funciona. Ingreso garantizado.',
    cta1: 'Inscríbete ahora', cta2: 'Ver programas', heroPills: ['Primeros puestos', 'Aula virtual incluida'],
    stats: [{ n: '+500', l: 'ingresantes al año' }, { n: '15 años', l: 'de experiencia' }, { n: 'Top 10', l: 'primeros puestos' }, { n: '4.9★', l: 'alumnos' }],
    servicesEyebrow: 'Programas', servicesTitle: 'Preparación para cada meta',
    services: [{ t: 'Preuniversitario', d: 'Preparación intensiva para San Marcos, UNI y más.' }, { t: 'Ciclo escolar', d: 'Reforzamiento para 3°, 4° y 5° de secundaria.' }, { t: 'Admisión particular', d: 'Preparación para universidades privadas.' }, { t: 'Clases virtuales', d: 'Aprende desde casa con la misma calidad.' }],
    processTitle: 'Nuestra metodología',
    process: [{ t: 'Evaluación', d: 'Medimos tu nivel inicial sin costo.' }, { t: 'Plan de estudio', d: 'Diseñamos tu ruta hacia el ingreso.' }, { t: 'Clases y práctica', d: 'Teoría, simulacros y reforzamiento constante.' }, { t: 'Ingreso', d: 'Te acompañamos hasta lograr tu vacante.' }],
    testiTitle: 'Nuestros ingresantes',
    testimonials: [{ q: 'Ingresé a San Marcos en primera opción. Los profes son lo máximo.', n: 'Kevin Huamán', r: 'Ingresante UNMSM' }, { q: 'Los simulacros me prepararon para el examen real. ¡Ingresé!', n: 'Lucía Tarazona', r: 'Ingresante UNI' }, { q: 'Pasé de no entender nada a ingresar. Gracias academia.', n: 'Diego Mallqui', r: 'Ingresante PUCP' }],
    faqTitle: 'Preguntas frecuentes',
    faq: [{ q: '¿Tienen clases virtuales?', a: 'Sí, puedes estudiar presencial o virtual con acceso a grabaciones.' }, { q: '¿Cuándo empiezan los ciclos?', a: 'Abrimos ciclos durante todo el año; escríbenos por el más próximo.' }, { q: '¿Hacen simulacros?', a: 'Sí, simulacros tipo examen de admisión cada semana.' }],
    contactTitle: 'Inscríbete hoy', contactSub: 'Reserva tu vacante y empieza a preparar tu ingreso.',
    phone: '+51 945 110 330', address: 'Av. Garcilaso de la Vega 1250, Cercado, Lima', hours: 'Lun–Sáb · 8:00 – 21:00', contactCta: 'Quiero inscribirme', email: 'informes@academiaelite.pe',
    footerAbout: 'Academia preuniversitaria en Lima. Los mejores profesores y una metodología con ingreso comprobado.',
    whatsappHref: 'https://wa.me/51945110330',
    pexels: { hero: 'students studying classroom university', about: 'teacher explaining whiteboard' },
  },

  /* Profesor / clases particulares */
  {
    slug: 'profesor', category: CAT, label: 'Clases particulares', brand: 'AprendeMás',
    fonts: { heading: 'Poppins', body: 'Inter' },
    palette: { primary: '#2E8C6A', secondary: '#1A2E26', accent: '#E0A93C', bg: '#F6FBF8', text: '#1A2622' },
    plan: ['nav', 'heroSplit', 'stats', 'servicesGrid', 'process', 'testimonials', 'contact', 'footer'],
    nav: ['Inicio', 'Materias', 'Cómo funciona', 'Contacto'], navCta: 'Reserva una clase',
    eyebrow: 'Clases particulares', h1: 'Aprende a tu ritmo, con quien sabe enseñar', sub: 'Clases particulares personalizadas, presenciales o virtuales, para reforzar, nivelar o prepararte. Resultados desde la primera clase.',
    cta1: 'Reserva tu clase', cta2: 'Ver materias', heroPills: ['Primera clase de prueba', 'Presencial u online'],
    stats: [{ n: '1,500+', l: 'alumnos ayudados' }, { n: '20+', l: 'materias' }, { n: '4.9★', l: 'valoración' }, { n: '100%', l: 'personalizado' }],
    servicesEyebrow: 'Materias', servicesTitle: 'Te ayudamos en lo que necesites',
    services: [{ t: 'Matemática y Física', d: 'Desde escolar hasta universitario.' }, { t: 'Letras y Comunicación', d: 'Redacción, literatura e historia.' }, { t: 'Inglés', d: 'Conversación, gramática y exámenes.' }, { t: 'Apoyo universitario', d: 'Cálculo, estadística y cursos de carrera.' }],
    processTitle: 'Cómo funciona',
    process: [{ t: 'Cuéntanos', d: 'Dinos qué materia y tu objetivo.' }, { t: 'Asignamos', d: 'Te conectamos con el profe ideal.' }, { t: 'Clase de prueba', d: 'La primera clase es para conocerse.' }, { t: 'Avanzas', d: 'Refuerzas y mejoras clase a clase.' }],
    testiTitle: 'Alumnos que mejoraron',
    testimonials: [{ q: 'Pasé de jalar matemática a sacar las mejores notas. Increíble profe.', n: 'Madre de Sebastián', r: 'Clases de matemática' }, { q: 'Me prepararon para mi examen de inglés y lo aprobé. Mil gracias.', n: 'Andrea Pino', r: 'Clases de inglés' }, { q: 'Las clases online funcionan súper bien. Muy recomendable.', n: 'Luis Bardales', r: 'Apoyo universitario' }],
    contactTitle: 'Reserva tu primera clase', contactSub: 'Cuéntanos qué necesitas reforzar y empezamos.',
    phone: '+51 956 220 770', address: 'Atención en Lima y online', hours: 'Lun–Dom · 8:00 – 21:00', contactCta: 'Reservar clase', email: 'hola@aprendemas.pe',
    footerAbout: 'Clases particulares personalizadas en Lima y online. Refuerza, nivélate y alcanza tus metas.',
    whatsappHref: 'https://wa.me/51956220770',
    pexels: { hero: 'tutor student private lesson', about: 'teacher helping student desk' },
  },

  /* Academia de idiomas */
  {
    slug: 'idiomas', category: CAT, label: 'Academia de idiomas', brand: 'Lingua Center',
    fonts: { heading: 'Sora', body: 'Inter' },
    palette: { primary: '#2E6BC4', secondary: '#16263F', accent: '#F0A93C', bg: '#F6F9FC', text: '#1A2430' },
    plan: ['nav', 'heroSplit', 'stats', 'servicesGrid', 'pricing', 'testimonials', 'faq', 'contact', 'footer'],
    nav: ['Inicio', 'Idiomas', 'Planes', 'Contacto'], navCta: 'Reserva tu prueba',
    eyebrow: 'Idiomas · Lima', h1: 'Habla un nuevo idioma con confianza', sub: 'Cursos de inglés, portugués y más, con metodología comunicativa y profesores nativos. Conversa desde la primera clase.',
    cta1: 'Reserva tu prueba de nivel', cta2: 'Ver planes', heroPills: ['Prueba de nivel gratis', 'Certificación internacional'],
    stats: [{ n: '12,000+', l: 'alumnos graduados' }, { n: '6', l: 'idiomas' }, { n: 'Nativos', l: 'profesores' }, { n: '4.9★', l: 'satisfacción' }],
    servicesEyebrow: 'Idiomas', servicesTitle: 'Elige tu idioma',
    services: [{ t: 'Inglés', d: 'Desde básico hasta preparación para TOEFL e IELTS.' }, { t: 'Portugués', d: 'Aprende el idioma de toda Latinoamérica y Brasil.' }, { t: 'Italiano y francés', d: 'Cultura e idioma para viajar o estudiar.' }, { t: 'Inglés para niños', d: 'Programas lúdicos para los más pequeños.' }],
    pricingTitle: 'Planes para ti',
    pricing: [{ name: 'Grupal', price: 'S/ 180', per: '/mes', feats: ['Clases en grupo reducido', 'Material incluido', 'Acceso a plataforma'], cta: 'Inscribirme' }, { name: 'Intensivo', price: 'S/ 290', per: '/mes', feats: ['Avanza el doble de rápido', 'Clases diarias', 'Material y plataforma', 'Certificado'], featured: true, cta: 'Inscribirme' }, { name: 'Personalizado', price: 'S/ 60', per: '/clase', feats: ['Clases 1 a 1', 'Horario flexible', 'Plan a tu medida'], cta: 'Inscribirme' }],
    testiTitle: 'Alumnos que ya lo hablan',
    testimonials: [{ q: 'En seis meses pasé de cero a conversar en inglés. Metodología buenísima.', n: 'Rodrigo Salas', r: 'Alumno de inglés' }, { q: 'Los profes nativos hacen la diferencia. Aprendí portugués rapidísimo.', n: 'Daniela Yi', r: 'Alumna de portugués' }, { q: 'Mi hijo ama sus clases de inglés. Aprende jugando.', n: 'Madre de familia', r: 'Inglés para niños' }],
    faqTitle: 'Preguntas frecuentes',
    faq: [{ q: '¿La prueba de nivel tiene costo?', a: 'No, es gratuita y te ubica en el nivel exacto.' }, { q: '¿Dan certificado?', a: 'Sí, otorgamos certificación al completar cada nivel.' }, { q: '¿Hay clases virtuales?', a: 'Sí, puedes estudiar presencial o en vivo online.' }],
    contactTitle: 'Reserva tu prueba de nivel', contactSub: 'Descubre tu nivel y empieza a hablar un nuevo idioma.',
    phone: '+51 1 441 6060', address: 'Av. Arenales 1320, Lince, Lima', hours: 'Lun–Sáb · 8:00 – 21:00', contactCta: 'Reservar prueba', email: 'informes@linguacenter.pe',
    footerAbout: 'Academia de idiomas en Lima con profesores nativos y metodología comunicativa. Habla desde el día uno.',
    whatsappHref: 'https://wa.me/5114416060',
    pexels: { hero: 'language class students learning', about: 'language teacher conversation class' },
  },

  /* Cursos online / e-learning */
  {
    slug: 'cursos', category: CAT, label: 'Cursos online / E-learning', brand: 'Skillab',
    fonts: { heading: 'Sora', body: 'Inter' },
    palette: { primary: '#6D3FE0', secondary: '#1E1A3A', accent: '#4FC2A8', bg: '#FAF8FF', text: '#1F1B2E' },
    plan: ['nav', 'heroSplit', 'stats', 'cards', 'featureSplit', 'testimonials', 'ctaBanner', 'contact', 'footer'],
    nav: ['Inicio', 'Cursos', 'Nosotros', 'Contacto'], navCta: 'Empieza gratis',
    eyebrow: 'Educación online', h1: 'Aprende habilidades que sí piden las empresas', sub: 'Cursos online prácticos, con proyectos reales y certificado. Aprende a tu ritmo, desde donde estés.',
    cta1: 'Explora los cursos', cta2: 'Empieza gratis', heroPills: ['Acceso de por vida', 'Certificado incluido'],
    stats: [{ n: '40,000+', l: 'estudiantes' }, { n: '120+', l: 'cursos' }, { n: '4.8★', l: 'valoración' }, { n: 'De por vida', l: 'acceso' }],
    cardsEyebrow: 'Cursos populares', cardsTitle: 'Empieza por el que más te sirva', cardsCta: 'Ver curso',
    cards: [{ tag: 'Top ventas', t: 'Marketing Digital', d: 'Domina redes, ads y embudos de venta', p: 'S/ 99' }, { tag: 'Nuevo', t: 'Excel Profesional', d: 'De básico a experto con casos reales', p: 'S/ 79' }, { tag: 'Demanda', t: 'Diseño con IA', d: 'Crea piezas profesionales sin ser diseñador', p: 'S/ 129' }, { t: 'Finanzas personales', d: 'Ordena tu dinero y haz crecer tus ahorros', p: 'S/ 89' }, { t: 'Programación web', d: 'Crea tu primera página desde cero', p: 'S/ 149' }, { t: 'Ventas y negociación', d: 'Cierra más tratos con técnicas probadas', p: 'S/ 99' }],
    aboutTitle: 'Aprendizaje práctico, resultados reales', aboutBody: 'Olvídate de la teoría aburrida. Cada curso está hecho para que apliques desde el primer día, con proyectos, plantillas y el acompañamiento de expertos que trabajan en lo que enseñan.',
    aboutBullets: ['Profesores que trabajan en la industria', 'Proyectos y plantillas descargables', 'Comunidad y soporte para tus dudas'],
    testiTitle: 'Estudiantes que avanzaron',
    testimonials: [{ q: 'Conseguí un mejor trabajo aplicando lo del curso de marketing. Brutal.', n: 'Jhon Ramírez', r: 'Estudiante' }, { q: 'El curso de Excel me ascendieron en la oficina. Súper práctico.', n: 'Milagros Pari', r: 'Estudiante' }, { q: 'Aprendí a mi ritmo y con certificado. Justo lo que necesitaba.', n: 'Cristian Loayza', r: 'Estudiante' }],
    ctaTitle: 'Tu próxima habilidad te espera', ctaSub: 'Empieza hoy con acceso de por vida. Escríbenos por WhatsApp.',
    contactTitle: 'Empieza a aprender', contactSub: 'Cuéntanos qué quieres aprender y te recomendamos el curso ideal.',
    phone: '+51 940 550 220', address: '100% online · Perú', hours: 'Soporte Lun–Sáb · 9:00 – 20:00', contactCta: 'Quiero empezar', email: 'hola@skillab.pe',
    footerAbout: 'Plataforma de cursos online en Perú. Habilidades prácticas con proyectos reales y certificado.',
    whatsappHref: 'https://wa.me/51940550220',
    pexels: { hero: 'online learning laptop student home', about: 'person studying laptop online course' },
  },
];
