/* FINANZAS — 3 rubros. */
const CAT = 'Finanzas';

module.exports = [
  /* Asesoría financiera */
  {
    slug: 'finanzas', category: CAT, label: 'Asesoría financiera', brand: 'Capital Asesores',
    fonts: { heading: 'Sora', body: 'Inter' },
    palette: { primary: '#1E7A5A', secondary: '#14302A', accent: '#C8A45C', bg: '#F5FAF8', text: '#182A24' },
    plan: ['nav', 'heroSplit', 'stats', 'servicesGrid', 'process', 'testimonials', 'faq', 'contact', 'footer'],
    nav: ['Inicio', 'Servicios', 'Proceso', 'Contacto'], navCta: 'Asesórate gratis',
    eyebrow: 'Asesoría financiera · Lima', h1: 'Haz que tu dinero trabaje para ti', sub: 'Asesoría financiera independiente para personas y empresas. Ordena tus finanzas, invierte mejor y alcanza tus metas.',
    cta1: 'Solicita asesoría gratis', cta2: 'Ver servicios', heroPills: ['Asesoría independiente', 'Primera reunión sin costo'],
    stats: [{ n: '2,500+', l: 'clientes asesorados' }, { n: '12 años', l: 'de experiencia' }, { n: 'S/ 200M+', l: 'patrimonio gestionado' }, { n: '4.9★', l: 'satisfacción' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Soluciones para tu patrimonio',
    services: [{ t: 'Planificación financiera', d: 'Un plan claro para alcanzar tus metas.' }, { t: 'Inversiones', d: 'Estrategias según tu perfil y objetivos.' }, { t: 'Finanzas para empresas', d: 'Optimiza el flujo y la rentabilidad.' }, { t: 'Plan de retiro', d: 'Asegura tu tranquilidad a futuro.' }, { t: 'Reestructuración de deudas', d: 'Ordena y reduce tus obligaciones.' }, { t: 'Educación financiera', d: 'Aprende a manejar mejor tu dinero.' }],
    processTitle: 'Cómo trabajamos',
    process: [{ t: 'Diagnóstico', d: 'Analizamos tu situación financiera, gratis.' }, { t: 'Plan', d: 'Diseñamos una estrategia a tu medida.' }, { t: 'Ejecución', d: 'Te acompañamos a implementarla.' }, { t: 'Seguimiento', d: 'Revisamos y ajustamos contigo.' }],
    testiTitle: 'Clientes que mejoraron sus finanzas',
    testimonials: [{ q: 'Ordenaron mis finanzas y por fin empecé a invertir con sentido. Excelentes.', n: 'Mariano Tovar', r: 'Cliente' }, { q: 'Me ayudaron a reestructurar mis deudas y respirar de nuevo. Gracias.', n: 'Cecilia Ramos', r: 'Cliente' }, { q: 'Asesoría honesta y sin venderme productos. Confianza total.', n: 'Empresa del Sur', r: 'Cliente corporativo' }],
    faqTitle: 'Preguntas frecuentes',
    faq: [{ q: '¿La primera reunión tiene costo?', a: 'No, la primera reunión de diagnóstico es totalmente gratuita.' }, { q: '¿Venden productos financieros?', a: 'Somos asesores independientes: te recomendamos lo mejor para ti, sin sesgos.' }, { q: '¿Atienden a personas o empresas?', a: 'A ambas. Adaptamos la asesoría a tu situación.' }],
    contactTitle: 'Solicita tu asesoría gratuita', contactSub: 'Conversemos sobre tus metas financieras sin compromiso.',
    phone: '+51 1 622 9090', address: 'Av. Canaval y Moreyra 480, San Isidro, Lima', hours: 'Lun–Vie · 9:00 – 18:00', contactCta: 'Quiero asesoría', email: 'contacto@capitalasesores.pe',
    footerAbout: 'Asesoría financiera independiente en Lima. Ordena tus finanzas, invierte mejor y alcanza tus metas.',
    whatsappHref: 'https://wa.me/5116229090',
    pexels: { hero: 'financial advisor meeting charts', about: 'financial planning documents calculator' },
  },

  /* Seguros / corredores */
  {
    slug: 'seguros', category: CAT, label: 'Seguros / Corredores', brand: 'Protege Seguros',
    fonts: { heading: 'Sora', body: 'Inter' },
    palette: { primary: '#1C4E8C', secondary: '#14253B', accent: '#F0A030', bg: '#F6F8FB', text: '#1A2330' },
    plan: ['nav', 'heroSplit', 'stats', 'servicesGrid', 'cards', 'testimonials', 'faq', 'contact', 'footer'],
    nav: ['Inicio', 'Servicios', 'Seguros', 'Contacto'], navCta: 'Cotiza tu seguro',
    eyebrow: 'Corredores de seguros · Perú', h1: 'Protege lo que más quieres', sub: 'Te asesoramos para elegir el seguro ideal entre todas las aseguradoras. Independientes, a tu favor, sin costo extra para ti.',
    cta1: 'Cotiza tu seguro', cta2: 'Ver seguros', heroPills: ['Comparamos aseguradoras', 'Te acompañamos en el siniestro'],
    stats: [{ n: '10,000+', l: 'asegurados' }, { n: 'Todas', l: 'las aseguradoras' }, { n: '15 años', l: 'protegiendo' }, { n: '4.9★', l: 'clientes' }],
    servicesEyebrow: 'Por qué nosotros', servicesTitle: 'Asesoría que está de tu lado',
    services: [{ t: 'Comparamos por ti', d: 'Cotizamos en todas las aseguradoras.' }, { t: 'Asesoría honesta', d: 'Te explicamos coberturas en simple.' }, { t: 'Apoyo en siniestros', d: 'Te acompañamos cuando más importa.' }],
    cardsEyebrow: 'Seguros', cardsTitle: 'Coberturas para cada necesidad', cardsCta: 'Cotizar',
    cards: [{ tag: 'Popular', t: 'Seguro vehicular', d: 'Protección total o contra terceros', p: 'Cotiza gratis' }, { t: 'Seguro de salud', d: 'EPS y seguros médicos para tu familia', p: 'Cotiza gratis' }, { t: 'Seguro de vida', d: 'Tranquilidad para los que amas', p: 'Cotiza gratis' }, { t: 'Seguro de hogar', d: 'Protege tu casa y tu patrimonio', p: 'Cotiza gratis' }, { t: 'SOAT', d: 'Rápido y al mejor precio', p: 'Desde S/ 75' }, { t: 'Seguro empresarial', d: 'Protege tu negocio y a tu equipo', p: 'Cotiza gratis' }],
    testiTitle: 'Lo que dicen nuestros clientes',
    testimonials: [{ q: 'Me consiguieron el mejor seguro vehicular y me ayudaron con el choque. Top.', n: 'Renato Salas', r: 'Cliente' }, { q: 'Me explicaron todo clarito y elegí el seguro de salud ideal para mi familia.', n: 'Patricia Vela', r: 'Cliente' }, { q: 'Cuando tuve el siniestro, ellos hicieron todo. Vale oro tener un corredor.', n: 'Jorge Medina', r: 'Cliente' }],
    faqTitle: 'Preguntas frecuentes',
    faq: [{ q: '¿Cobrar por su asesoría?', a: 'No. Como corredores, la aseguradora nos paga; para ti el costo es el mismo o mejor.' }, { q: '¿Con qué aseguradoras trabajan?', a: 'Con todas las principales del país, para ofrecerte la mejor opción.' }, { q: '¿Me ayudan si tengo un siniestro?', a: 'Sí, te acompañamos en todo el proceso hasta la indemnización.' }],
    contactTitle: 'Cotiza tu seguro gratis', contactSub: 'Cuéntanos qué quieres proteger y te enviamos las mejores opciones.',
    phone: '+51 1 700 5050', address: 'Av. República de Panamá 3600, San Isidro, Lima', hours: 'Lun–Vie · 9:00 – 18:00', contactCta: 'Cotizar gratis', email: 'contacto@protegeseguros.pe',
    footerAbout: 'Corredores de seguros en Lima. Comparamos todas las aseguradoras para que protejas lo que más quieres.',
    whatsappHref: 'https://wa.me/5117005050',
    pexels: { hero: 'insurance protection family hands', cards: ['car insurance vehicle', 'health insurance medical', 'life insurance family', 'home insurance house', 'car soat document', 'business insurance office'] },
  },

  /* Cooperativa / caja */
  {
    slug: 'cooperativa', category: CAT, label: 'Cooperativa / Caja', brand: 'Coopera Crece',
    fonts: { heading: 'Sora', body: 'Inter' },
    palette: { primary: '#2E8C5A', secondary: '#14302A', accent: '#F0A82E', bg: '#F5FAF6', text: '#182A22' },
    plan: ['nav', 'heroSplit', 'stats', 'servicesGrid', 'cards', 'testimonials', 'faq', 'contact', 'footer'],
    nav: ['Inicio', 'Servicios', 'Productos', 'Contacto'], navCta: 'Hazte socio',
    eyebrow: 'Cooperativa de ahorro y crédito', h1: 'Juntos hacemos crecer tu economía', sub: 'Ahorro y crédito pensados en ti. Mejores tasas, trato cercano y la fuerza de pertenecer a una cooperativa que te cuida.',
    cta1: 'Hazte socio', cta2: 'Ver productos', heroPills: ['Mejores tasas', 'Trato cercano'],
    stats: [{ n: '50,000+', l: 'socios' }, { n: '25 años', l: 'de respaldo' }, { n: 'Tasas', l: 'preferenciales' }, { n: '4.8★', l: 'confianza' }],
    servicesEyebrow: 'Por qué asociarte', servicesTitle: 'Una cooperativa que te cuida',
    services: [{ t: 'Mejores tasas', d: 'Más rentabilidad en ahorros, menos en créditos.' }, { t: 'Trato cercano', d: 'Te conocemos por tu nombre, no por un número.' }, { t: 'Decides con nosotros', d: 'Como socio, eres parte de la cooperativa.' }],
    cardsEyebrow: 'Productos', cardsTitle: 'Ahorro y crédito para ti', cardsCta: 'Más info',
    cards: [{ tag: 'Ahorro', t: 'Cuenta de ahorros', d: 'Disponibilidad y rentabilidad', p: 'Sin mantenimiento' }, { tag: 'Ahorro', t: 'Depósito a plazo', d: 'Las mejores tasas del mercado', p: 'Hasta 8% anual' }, { tag: 'Crédito', t: 'Crédito personal', d: 'Para lo que necesites, rápido', p: 'Tasa preferencial' }, { tag: 'Crédito', t: 'Crédito para negocio', d: 'Haz crecer tu emprendimiento', p: 'Cuotas flexibles' }, { tag: 'Crédito', t: 'Crédito vehicular', d: 'Estrena tu auto', p: 'Aprobación rápida' }, { t: 'Seguro de socio', d: 'Protección para ti y tu familia', p: 'Incluido' }],
    testiTitle: 'Socios que crecen con nosotros',
    testimonials: [{ q: 'Me dieron el crédito que ningún banco me dio, y con mejor tasa. Agradecido.', n: 'Walter Ñahui', r: 'Socio' }, { q: 'Mis ahorros rinden más aquí y me atienden con mucho cariño. Encantada.', n: 'Rosa Quispe', r: 'Socia' }, { q: 'Financié mi negocio con ellos y me acompañaron en todo. Excelente.', n: 'Pedro Mamani', r: 'Socio' }],
    faqTitle: 'Preguntas frecuentes',
    faq: [{ q: '¿Cómo me hago socio?', a: 'Es muy fácil: con tu DNI y un aporte inicial mínimo ya eres parte.' }, { q: '¿Mis ahorros están protegidos?', a: 'Sí, contamos con respaldo y supervisión, y tus aportes están protegidos.' }, { q: '¿Dan créditos a emprendedores?', a: 'Sí, tenemos productos pensados para hacer crecer tu negocio.' }],
    contactTitle: 'Hazte socio hoy', contactSub: 'Acércate o escríbenos y empieza a crecer con nosotros.',
    phone: '+51 1 480 3030', address: 'Av. Próceres de la Independencia 1840, SJL, Lima', hours: 'Lun–Sáb · 9:00 – 18:00', contactCta: 'Quiero asociarme', email: 'socios@cooperacrece.pe',
    footerAbout: 'Cooperativa de ahorro y crédito en Lima. Mejores tasas y trato cercano para hacer crecer tu economía.',
    whatsappHref: 'https://wa.me/5114803030',
    pexels: { hero: 'savings money cooperative people', cards: ['savings account money', 'fixed deposit savings', 'personal loan handshake', 'small business loan', 'car loan keys', 'family protection insurance'] },
  },
];
