/* FITNESS Y DEPORTE — 3 rubros. */
const CAT = 'Fitness y deporte';

module.exports = [
  /* Gimnasio / crossfit */
  {
    slug: 'gimnasio', category: CAT, label: 'Gimnasio / Crossfit', brand: 'Forge Gym',
    fonts: { heading: 'Oswald', body: 'Inter' },
    palette: { primary: '#E0431E', secondary: '#18181B', accent: '#15151A', bg: '#F5F5F4', text: '#1A1A1E' },
    plan: ['nav', 'heroFullBg', 'stats', 'pricing', 'servicesGrid', 'gallery', 'testimonials', 'ctaBanner', 'contact', 'footer'],
    nav: ['Inicio', 'Planes', 'Servicios', 'Galería', 'Contacto'], navCta: 'Empieza hoy',
    eyebrow: 'Gimnasio · Lima', h1: 'Forja tu mejor versión', sub: 'Equipos de última generación, entrenadores certificados y la energía que necesitas para superar tus límites.',
    cta1: 'Empieza hoy', cta2: 'Ver planes',
    stats: [{ n: '3,000+', l: 'miembros activos' }, { n: '600m²', l: 'de área' }, { n: '20+', l: 'clases a la semana' }, { n: '4.9★', l: 'comunidad' }],
    pricingTitle: 'Elige tu plan',
    pricing: [{ name: 'Mensual', price: 'S/ 99', per: '/mes', feats: ['Acceso completo', 'Clases grupales', 'Casillero'], cta: 'Inscribirme' }, { name: 'Trimestral', price: 'S/ 249', per: '/3 meses', feats: ['Todo el plan mensual', 'Evaluación física', 'Plan de entrenamiento', 'Mejor precio'], featured: true, cta: 'Inscribirme' }, { name: 'Anual', price: 'S/ 790', per: '/año', feats: ['Acceso ilimitado', 'Asesoría nutricional', 'Congela tu plan', 'Máximo ahorro'], cta: 'Inscribirme' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Todo para tu entrenamiento',
    services: [{ t: 'Sala de máquinas', d: 'Equipos de fuerza y cardio de última generación.' }, { t: 'Clases grupales', d: 'Funcional, spinning, box y más energía.' }, { t: 'Crossfit', d: 'Box equipado y coaches especializados.' }, { t: 'Entrenamiento personal', d: 'Resultados más rápidos con un coach a tu lado.' }, { t: 'Asesoría nutricional', d: 'Plan de alimentación para tu objetivo.' }, { t: 'Zona funcional', d: 'Espacio amplio para entrenar libre.' }],
    galleryEyebrow: 'Galería', galleryTitle: 'Vive la experiencia',
    testiTitle: 'Historias que inspiran',
    testimonials: [{ q: 'Bajé 15 kilos y gané fuerza. Los coaches te motivan de verdad.', n: 'Christian Rojas', r: 'Miembro' }, { q: 'El mejor ambiente para entrenar. La comunidad es increíble.', n: 'Fiorella Anchante', r: 'Miembro' }, { q: 'Equipos top y siempre limpio. Cambió mi rutina por completo.', n: 'Bruno Castillo', r: 'Miembro' }],
    ctaTitle: '¿Listo para empezar?', ctaSub: 'Escríbenos por WhatsApp y prueba tu primera clase gratis.',
    contactTitle: 'Empieza hoy mismo', contactSub: 'Ven a conocer el gym y prueba una clase sin costo.',
    phone: '+51 945 880 220', address: 'Av. El Polo 670, Surco, Lima', hours: 'Lun–Sáb · 5:00 – 23:00 · Dom 8:00 – 14:00', contactCta: 'Quiero empezar', email: 'hola@forgegym.pe',
    footerAbout: 'Gimnasio y box de crossfit en Surco. Equipos top, coaches certificados y una comunidad que te impulsa.',
    whatsappHref: 'https://wa.me/51945880220',
    pexels: { hero: 'gym fitness training weights dark', gallery: ['gym equipment modern', 'crossfit workout', 'people training gym', 'dumbbells weights', 'fitness class group', 'man lifting weights'] },
  },

  /* Yoga / pilates */
  {
    slug: 'yoga', category: CAT, label: 'Yoga / Pilates', brand: 'Namasté Studio',
    fonts: { heading: 'Fraunces', body: 'Jost' },
    palette: { primary: '#7C8C5A', secondary: '#2A2E1E', accent: '#D8B08C', bg: '#F8F7F0', text: '#2A2A20' },
    plan: ['nav', 'heroFullBg', 'stats', 'servicesGrid', 'featureSplit', 'pricing', 'testimonials', 'contact', 'footer'],
    nav: ['Inicio', 'Clases', 'Nosotros', 'Planes', 'Contacto'], navCta: 'Clase de prueba',
    eyebrow: 'Yoga & Pilates', h1: 'Encuentra tu equilibrio', sub: 'Un espacio para reconectar cuerpo y mente. Clases de yoga y pilates para todos los niveles, en un ambiente sereno.',
    cta1: 'Reserva tu clase de prueba', cta2: 'Ver clases',
    stats: [{ n: '2,000+', l: 'alumnos' }, { n: '25+', l: 'clases semanales' }, { n: 'Todos', l: 'los niveles' }, { n: '4.9★', l: 'bienestar' }],
    servicesEyebrow: 'Clases', servicesTitle: 'Encuentra tu práctica ideal',
    services: [{ t: 'Hatha Yoga', d: 'Posturas y respiración para principiantes.' }, { t: 'Vinyasa Flow', d: 'Movimiento dinámico y fluido.' }, { t: 'Pilates mat', d: 'Fuerza, postura y core en colchoneta.' }, { t: 'Pilates reformer', d: 'Tonificación con máquina especializada.' }, { t: 'Yin Yoga', d: 'Práctica suave y profundamente relajante.' }, { t: 'Meditación', d: 'Calma tu mente y reduce el estrés.' }],
    aboutTitle: 'Un refugio para tu bienestar', aboutBody: 'Creamos un espacio donde puedas desconectarte del ritmo de la ciudad y reconectar contigo. Con instructores certificados y grupos reducidos, cada clase es una oportunidad para sentirte mejor.',
    aboutBullets: ['Instructores certificados', 'Grupos reducidos y personalizados', 'Ambiente sereno y acogedor'],
    pricingTitle: 'Planes flexibles',
    pricing: [{ name: 'Clase suelta', price: 'S/ 35', per: '', feats: ['Una clase a elección', 'Sin compromiso', 'Mat incluido'], cta: 'Reservar' }, { name: 'Mensual ilimitado', price: 'S/ 220', per: '/mes', feats: ['Clases ilimitadas', 'Todas las disciplinas', 'Reserva prioritaria', 'Mejor valor'], featured: true, cta: 'Empezar' }, { name: 'Pack 8 clases', price: 'S/ 240', per: '/mes', feats: ['8 clases al mes', 'Horario flexible', 'Válido 5 semanas'], cta: 'Empezar' }],
    testiTitle: 'Lo que viven nuestros alumnos',
    testimonials: [{ q: 'Bajó mi estrés y mejoró mi postura. Este lugar es mi refugio.', n: 'Patricia Núñez', r: 'Alumna' }, { q: 'Los instructores son excelentes y el ambiente es pura paz.', n: 'Gonzalo Rivas', r: 'Alumno' }, { q: 'Empecé desde cero y ahora no puedo vivir sin mis clases. Hermoso.', n: 'Sofía Lama', r: 'Alumna' }],
    contactTitle: 'Reserva tu clase de prueba', contactSub: 'Ven a sentir la experiencia. Tu primera clase te espera.',
    phone: '+51 956 770 330', address: 'Calle Colón 240, Barranco, Lima', hours: 'Lun–Sáb · 7:00 – 21:00', contactCta: 'Reservar clase', email: 'hola@namastestudio.pe',
    footerAbout: 'Estudio de yoga y pilates en Barranco. Un refugio para reconectar cuerpo y mente.',
    whatsappHref: 'https://wa.me/51956770330',
    pexels: { hero: 'yoga studio class peaceful', about: 'pilates yoga practice woman' },
  },

  /* Academia deportiva */
  {
    slug: 'deportiva', category: CAT, label: 'Academia deportiva', brand: 'Campeones Academy',
    fonts: { heading: 'Oswald', body: 'Inter' },
    palette: { primary: '#1E63A8', secondary: '#14233B', accent: '#F0A030', bg: '#F6F9FC', text: '#18242E' },
    plan: ['nav', 'heroFullBg', 'stats', 'servicesGrid', 'gallery', 'pricing', 'testimonials', 'contact', 'footer'],
    nav: ['Inicio', 'Disciplinas', 'Galería', 'Planes', 'Contacto'], navCta: 'Inscríbete',
    eyebrow: 'Academia deportiva · Lima', h1: 'Formamos campeones dentro y fuera de la cancha', sub: 'Escuela deportiva para niños y jóvenes. Disciplina, valores y técnica con entrenadores profesionales.',
    cta1: 'Inscribe a tu hijo', cta2: 'Ver disciplinas',
    stats: [{ n: '1,500+', l: 'deportistas formados' }, { n: '10 años', l: 'de experiencia' }, { n: '6', l: 'disciplinas' }, { n: '4.9★', l: 'familias' }],
    servicesEyebrow: 'Disciplinas', servicesTitle: 'Encuentra el deporte ideal',
    services: [{ t: 'Fútbol', d: 'Técnica, táctica y juego en equipo.' }, { t: 'Vóley', d: 'Para niñas y niños desde categoría menor.' }, { t: 'Básquet', d: 'Fundamentos y competencia formativa.' }, { t: 'Natación', d: 'Aprende y perfecciona tu estilo.' }, { t: 'Artes marciales', d: 'Disciplina, defensa personal y respeto.' }, { t: 'Atletismo', d: 'Velocidad, resistencia y coordinación.' }],
    galleryEyebrow: 'Galería', galleryTitle: 'Nuestros deportistas en acción',
    pricingTitle: 'Planes mensuales',
    pricing: [{ name: '2 veces/semana', price: 'S/ 130', per: '/mes', feats: ['2 sesiones semanales', 'Entrenador profesional', 'Plan formativo'], cta: 'Inscribir' }, { name: '3 veces/semana', price: 'S/ 180', per: '/mes', feats: ['3 sesiones semanales', 'Evaluación de progreso', 'Participación en torneos', 'Mejor opción'], featured: true, cta: 'Inscribir' }, { name: 'Vacacional', price: 'S/ 220', per: '/mes', feats: ['Programa intensivo', 'Lunes a viernes', 'Incluye materiales'], cta: 'Inscribir' }],
    testiTitle: 'Lo que dicen las familias',
    testimonials: [{ q: 'Mi hijo mejoró su disciplina y hace amigos. La academia es excelente.', n: 'Padre de Mateo', r: 'Fútbol' }, { q: 'Entrenadores muy profesionales y atentos. Mi hija ama el vóley.', n: 'Madre de Camila', r: 'Vóley' }, { q: 'Más que deporte, le enseñan valores. Súper recomendados.', n: 'Familia Reátegui', r: 'Natación' }],
    contactTitle: 'Inscribe a tu hijo', contactSub: 'Agenda una clase de prueba gratuita y conócenos.',
    phone: '+51 945 330 660', address: 'Complejo Deportivo, Av. Huarochirí 320, Ate, Lima', hours: 'Lun–Sáb · 15:00 – 21:00', contactCta: 'Quiero inscribir', email: 'informes@campeonesacademy.pe',
    footerAbout: 'Academia deportiva en Lima para niños y jóvenes. Formamos campeones con disciplina y valores.',
    whatsappHref: 'https://wa.me/51945330660',
    pexels: { hero: 'kids sports training soccer field', gallery: ['children soccer training', 'kids volleyball', 'basketball youth', 'swimming kids pool', 'martial arts children', 'athletics running track'] },
  },
];
