/* GASTRONOMÍA — 3 rubros (restaurante/cevichería está en base). */
const CAT = 'Gastronomía';

module.exports = [
  /* Pollería */
  {
    slug: 'polleria', category: CAT, label: 'Pollería', brand: 'Brasa Dorada',
    fonts: { heading: 'Poppins', body: 'Inter' },
    palette: { primary: '#C8331F', secondary: '#2A1612', accent: '#F0A82E', bg: '#FBF6F0', text: '#241814' },
    plan: ['nav', 'heroFullBg', 'stats', 'menu', 'gallery', 'testimonials', 'ctaBanner', 'contact', 'footer'],
    nav: ['Inicio', 'Carta', 'Galería', 'Contacto'], navCta: 'Pedir delivery',
    eyebrow: 'Pollería · Lima', h1: 'El pollo a la brasa que todos aman', sub: 'Dorado, jugoso y con el sabor de siempre. A la leña, con nuestras salsas de la casa. Delivery en toda Lima.',
    cta1: 'Pide tu delivery', cta2: 'Ver la carta',
    stats: [{ n: '20 años', l: 'de tradición' }, { n: '1M+', l: 'pollos servidos' }, { n: '30 min', l: 'delivery promedio' }, { n: '4.9★', l: 'sabor' }],
    menuEyebrow: 'Nuestra carta', menuTitle: 'Lo que nos hace famosos',
    menu: [{ t: 'Pollo a la brasa entero', d: 'Con papas, ensalada y nuestras salsas', p: 'S/ 62' }, { t: '1/2 Pollo a la brasa', d: 'Con papas y ensalada fresca', p: 'S/ 35' }, { t: '1/4 Pollo + papas', d: 'La porción perfecta para uno', p: 'S/ 22' }, { t: 'Mostrito', d: 'Pollo, papas, chaufa y salchipapa', p: 'S/ 18' }, { t: 'Parrilla personal', d: 'Bistec, chorizo, mollejas y anticucho', p: 'S/ 38' }, { t: 'Chaufa de pollo', d: 'Al wok, bien servido', p: 'S/ 24' }, { t: 'Gaseosa 1.5L', d: 'Para acompañar tu pedido', p: 'S/ 10' }, { t: 'Combo familiar', d: 'Pollo entero + chaufa + gaseosa', p: 'S/ 82' }],
    galleryEyebrow: 'Galería', galleryTitle: 'Para abrir el apetito',
    testiTitle: 'Lo que dicen nuestros clientes',
    testimonials: [{ q: 'El mejor pollo a la brasa de la zona. Crocante por fuera y jugoso por dentro.', n: 'Marco Aurelio', r: 'Cliente' }, { q: 'El delivery siempre llega rápido y calentito. Mi pollería de cabecera.', n: 'Rosa Linares', r: 'Cliente frecuente' }, { q: 'Las salsas de la casa son adictivas. Pedimos cada fin de semana.', n: 'Familia Quiroz', r: 'Cliente' }],
    ctaTitle: '¿Se te antojó?', ctaSub: 'Pide tu pollo a la brasa por WhatsApp y te lo llevamos calentito.',
    contactTitle: 'Haz tu pedido', contactSub: 'Delivery o recojo en tienda. ¡Te esperamos!',
    phone: '+51 945 770 330', address: 'Av. Universitaria 1850, Los Olivos, Lima', hours: 'Todos los días · 12:00 – 23:00', contactCta: 'Pedir ahora', email: 'pedidos@brasadorada.pe',
    footerAbout: 'Pollería con 20 años de tradición en Lima. Pollo a la brasa a la leña con delivery rápido.',
    whatsappHref: 'https://wa.me/51945770330',
    pexels: { hero: 'grilled chicken rotisserie food', gallery: ['roasted chicken plate', 'french fries food', 'grilled meat barbecue', 'fried rice asian', 'restaurant food table', 'chicken dinner family'] },
  },

  /* Cafetería / pastelería */
  {
    slug: 'cafeteria', category: CAT, label: 'Cafetería / Pastelería', brand: 'Café Aurora',
    fonts: { heading: 'Fraunces', body: 'Inter' },
    palette: { primary: '#6E4B2A', secondary: '#2A1E14', accent: '#C89A5C', bg: '#FAF6EF', text: '#2A211A' },
    plan: ['nav', 'heroFullBg', 'stats', 'menu', 'featureSplit', 'gallery', 'testimonials', 'contact', 'footer'],
    nav: ['Inicio', 'Carta', 'Nosotros', 'Galería', 'Contacto'], navCta: 'Visítanos',
    eyebrow: 'Café de especialidad', h1: 'Tu momento favorito del día', sub: 'Café de especialidad, repostería artesanal y un ambiente acogedor para trabajar, conversar o simplemente disfrutar.',
    cta1: 'Ver la carta', cta2: 'Conócenos',
    stats: [{ n: '100%', l: 'café peruano' }, { n: 'Artesanal', l: 'repostería propia' }, { n: '8 años', l: 'endulzando Lima' }, { n: '4.9★', l: 'ambiente' }],
    menuEyebrow: 'Nuestra carta', menuTitle: 'Hecho con amor cada día',
    menu: [{ t: 'Espresso / Americano', d: 'Café de especialidad de origen peruano', p: 'S/ 8' }, { t: 'Cappuccino / Latte', d: 'Con arte latte y leche cremosa', p: 'S/ 13' }, { t: 'Cold brew', d: 'Café frío extraído en 18 horas', p: 'S/ 15' }, { t: 'Cheesecake del día', d: 'Porción artesanal, sabores rotativos', p: 'S/ 16' }, { t: 'Croissant de mantequilla', d: 'Horneado en casa, hojaldrado', p: 'S/ 10' }, { t: 'Sándwich gourmet', d: 'Pan artesanal y rellenos frescos', p: 'S/ 22' }, { t: 'Torta de chocolate', d: 'Húmeda, con ganache', p: 'S/ 18' }, { t: 'Jugo natural', d: 'Frutas de estación', p: 'S/ 12' }],
    aboutTitle: 'Un café con alma', aboutBody: 'Nacimos del amor por el buen café y la repostería honesta. Trabajamos con granos de productores peruanos y horneamos todo en casa, cada mañana, para que tu pausa del día sepa de verdad.',
    aboutBullets: ['Café de origen peruano seleccionado', 'Repostería artesanal horneada a diario', 'Ambiente ideal para trabajar o conversar'],
    galleryEyebrow: 'Galería', galleryTitle: 'Un rincón para disfrutar',
    testiTitle: 'Lo que dicen nuestros clientes',
    testimonials: [{ q: 'El mejor café de la zona y el ambiente es perfecto para trabajar.', n: 'Camila Ruiz', r: 'Cliente frecuente' }, { q: 'Sus cheesecakes son una locura. Vengo solo por ellos.', n: 'Diego Salazar', r: 'Cliente' }, { q: 'Acogedor, bonito y con un café espectacular. Mi lugar favorito.', n: 'Andrea Méndez', r: 'Cliente' }],
    contactTitle: 'Visítanos', contactSub: 'Te esperamos con un café recién hecho.',
    phone: '+51 987 330 110', address: 'Calle Berlín 360, Miraflores, Lima', hours: 'Lun–Dom · 7:00 – 22:00', contactCta: 'Cómo llegar', email: 'hola@cafeaurora.pe',
    footerAbout: 'Cafetería de especialidad y pastelería artesanal en Miraflores. Tu momento favorito del día.',
    whatsappHref: 'https://wa.me/51987330110',
    pexels: { hero: 'coffee shop cafe cozy interior', about: 'barista latte art coffee', gallery: ['coffee cup latte', 'cheesecake dessert', 'croissant pastry', 'cafe interior cozy', 'coffee beans', 'cake chocolate slice'] },
  },

  /* Catering / banquetería */
  {
    slug: 'catering', category: CAT, label: 'Catering / Banquetería', brand: 'Banquete & Co.',
    fonts: { heading: 'Cormorant Garamond', body: 'Jost' },
    palette: { primary: '#8C2D3A', secondary: '#2A1418', accent: '#C8A45C', bg: '#FAF6F2', text: '#2A1E1E' },
    plan: ['nav', 'heroFullBg', 'stats', 'servicesGrid', 'gallery', 'testimonials', 'ctaBanner', 'contact', 'footer'],
    nav: ['Inicio', 'Servicios', 'Galería', 'Contacto'], navCta: 'Cotiza tu evento',
    eyebrow: 'Catering & Eventos', h1: 'Hacemos inolvidable tu evento', sub: 'Catering gourmet y banquetería para bodas, corporativos y celebraciones. Sabor, presentación y servicio impecable.',
    cta1: 'Cotiza tu evento', cta2: 'Ver galería',
    stats: [{ n: '800+', l: 'eventos realizados' }, { n: '12 años', l: 'de experiencia' }, { n: 'Hasta 1,000', l: 'invitados' }, { n: '4.9★', l: 'clientes' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Para cada tipo de celebración',
    services: [{ t: 'Bodas', d: 'Menús de autor y servicio de lujo para tu gran día.' }, { t: 'Eventos corporativos', d: 'Coffee breaks, almuerzos y cócteles empresariales.' }, { t: 'Cumpleaños y sociales', d: 'Buffets y estaciones para celebrar en grande.' }, { t: 'Cócteles', d: 'Pasapalos gourmet y barra de tragos.' }],
    galleryEyebrow: 'Galería', galleryTitle: 'Momentos que servimos con arte',
    testiTitle: 'Eventos que dejaron huella',
    testimonials: [{ q: 'La comida de nuestra boda fue el comentario de todos. Espectaculares.', n: 'Andrea & Paolo', r: 'Boda' }, { q: 'Atendieron nuestro evento corporativo de 300 personas sin un solo fallo.', n: 'Gerencia, Corporación X', r: 'Evento empresarial' }, { q: 'Presentación de lujo y sabor increíble. Superaron nuestras expectativas.', n: 'Familia Velarde', r: 'Aniversario' }],
    ctaTitle: '¿Tienes un evento en mente?', ctaSub: 'Cuéntanos los detalles por WhatsApp y te armamos una propuesta a medida.',
    contactTitle: 'Cotiza tu evento', contactSub: 'Cuéntanos tu celebración y diseñamos el menú perfecto.',
    phone: '+51 962 440 880', address: 'Av. La Floresta 290, Surco, Lima', hours: 'Lun–Sáb · 9:00 – 19:00', contactCta: 'Solicitar cotización', email: 'eventos@banqueteco.pe',
    footerAbout: 'Catering gourmet y banquetería en Lima. Hacemos inolvidable tu boda, evento o celebración.',
    whatsappHref: 'https://wa.me/51962440880',
    pexels: { hero: 'catering banquet elegant event food', gallery: ['wedding catering table', 'gourmet plated food', 'event buffet elegant', 'cocktail appetizers', 'banquet hall setup', 'chef plating dish'] },
  },
];
