/* SERVICIOS PARA EL HOGAR / OFICIOS — 5 rubros. */
const CAT = 'Servicios para el hogar';

module.exports = [
  /* Gasfitería / electricistas */
  {
    slug: 'gasfiteria', category: CAT, label: 'Gasfitería / Electricidad', brand: 'ServiHogar 24',
    fonts: { heading: 'Sora', body: 'Inter' },
    palette: { primary: '#1E63A8', secondary: '#14304A', accent: '#F0A030', bg: '#F6F9FC', text: '#18242E' },
    plan: ['nav', 'heroSplit', 'stats', 'servicesGrid', 'process', 'testimonials', 'ctaBanner', 'contact', 'footer'],
    nav: ['Inicio', 'Servicios', 'Proceso', 'Contacto'], navCta: 'Llámanos ahora',
    eyebrow: 'Servicios del hogar · Lima', h1: 'Soluciones para tu hogar, cuando las necesitas', sub: 'Gasfitería, electricidad y reparaciones con técnicos certificados. Llegamos rápido, trabajamos limpio y dejamos todo funcionando.',
    cta1: 'Solicita un técnico', cta2: 'Ver servicios', heroPills: ['Atención el mismo día', 'Técnicos certificados'],
    stats: [{ n: '24/7', l: 'emergencias' }, { n: '15,000+', l: 'servicios' }, { n: '60 min', l: 'llegada promedio' }, { n: '4.9★', l: 'clientes' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Todo para tu casa u oficina',
    services: [{ t: 'Gasfitería', d: 'Fugas, desatoros, instalación de griferías y más.' }, { t: 'Electricidad', d: 'Instalaciones, tableros, tomas y fallas.' }, { t: 'Reparación de calentadores', d: 'Termas eléctricas y a gas.' }, { t: 'Instalación de sanitarios', d: 'Inodoros, lavatorios y duchas.' }, { t: 'Mantenimiento general', d: 'Pequeñas reparaciones del hogar.' }, { t: 'Emergencias 24h', d: 'Atendemos cuando más lo necesitas.' }],
    processTitle: 'Tan fácil como',
    process: [{ t: 'Llámanos', d: 'Cuéntanos qué necesitas por WhatsApp.' }, { t: 'Cotización', d: 'Te damos un precio claro antes de empezar.' }, { t: 'Servicio', d: 'Un técnico va y resuelve, limpio y rápido.' }, { t: 'Garantía', d: 'Respaldamos nuestro trabajo.' }],
    testiTitle: 'Lo que dicen nuestros clientes',
    testimonials: [{ q: 'Vinieron en una hora a arreglar una fuga. Rápidos, limpios y honestos.', n: 'Lourdes Pérez', r: 'Cliente' }, { q: 'Resolvieron un problema eléctrico que nadie podía. Técnicos muy capaces.', n: 'Andrés Lira', r: 'Cliente' }, { q: 'Precio justo y buen trabajo. Los tengo guardados para cualquier emergencia.', n: 'Familia Sosa', r: 'Cliente' }],
    ctaTitle: '¿Tienes una emergencia?', ctaSub: 'Escríbenos por WhatsApp y enviamos un técnico de inmediato.',
    contactTitle: 'Solicita un técnico', contactSub: 'Cuéntanos qué necesitas y te atendemos rápido.',
    phone: '+51 945 990 110', address: 'Atención en toda Lima Metropolitana', hours: 'Todos los días · 24 horas', contactCta: 'Pedir técnico', email: 'contacto@servihogar24.pe',
    footerAbout: 'Servicios de gasfitería y electricidad en Lima. Técnicos certificados, atención el mismo día y emergencias 24h.',
    whatsappHref: 'https://wa.me/51945990110',
    pexels: { hero: 'plumber electrician home repair', about: 'plumber fixing pipe sink' },
  },

  /* Limpieza / mantenimiento */
  {
    slug: 'limpieza', category: CAT, label: 'Limpieza / Mantenimiento', brand: 'Limpio Total',
    fonts: { heading: 'Sora', body: 'Inter' },
    palette: { primary: '#1E9BB0', secondary: '#14333A', accent: '#5BB98C', bg: '#F4FBFB', text: '#16292F' },
    plan: ['nav', 'heroSplit', 'stats', 'servicesGrid', 'process', 'testimonials', 'ctaBanner', 'contact', 'footer'],
    nav: ['Inicio', 'Servicios', 'Proceso', 'Contacto'], navCta: 'Cotiza tu limpieza',
    eyebrow: 'Limpieza profesional · Lima', h1: 'Espacios impecables, sin que muevas un dedo', sub: 'Servicio de limpieza para hogares, oficinas y empresas. Personal capacitado, productos de calidad y resultados que se notan.',
    cta1: 'Cotiza tu limpieza', cta2: 'Ver servicios', heroPills: ['Personal de confianza', 'Servicio garantizado'],
    stats: [{ n: '6,000+', l: 'espacios limpios' }, { n: '12 años', l: 'de experiencia' }, { n: '100%', l: 'personal capacitado' }, { n: '4.9★', l: 'clientes' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Limpieza para cada necesidad',
    services: [{ t: 'Limpieza de hogar', d: 'Mantén tu casa impecable, regular o por hora.' }, { t: 'Limpieza de oficinas', d: 'Ambientes de trabajo siempre presentables.' }, { t: 'Limpieza profunda', d: 'Para mudanzas, post-obra o fin de año.' }, { t: 'Limpieza de alfombras', d: 'Lavado y desmanchado profesional.' }, { t: 'Mantenimiento de edificios', d: 'Áreas comunes siempre cuidadas.' }, { t: 'Desinfección', d: 'Espacios seguros y libres de gérmenes.' }],
    processTitle: 'Cómo trabajamos',
    process: [{ t: 'Cotización', d: 'Evaluamos tu espacio y te damos precio.' }, { t: 'Coordinación', d: 'Agendamos el día y la hora que prefieras.' }, { t: 'Limpieza', d: 'Nuestro equipo deja todo impecable.' }, { t: 'Garantía', d: 'Si algo no quedó, lo resolvemos.' }],
    testiTitle: 'Lo que dicen nuestros clientes',
    testimonials: [{ q: 'Mi casa quedó reluciente y el personal súper confiable. Las contrato siempre.', n: 'Gisella Romero', r: 'Cliente' }, { q: 'Mantienen nuestra oficina impecable. Puntuales y muy profesionales.', n: 'Estudio Contable LP', r: 'Cliente corporativo' }, { q: 'La limpieza profunda post-mudanza fue espectacular. Recomendadísimas.', n: 'Martín Aguilar', r: 'Cliente' }],
    ctaTitle: '¿Listo para un espacio impecable?', ctaSub: 'Escríbenos por WhatsApp y cotiza tu servicio de limpieza.',
    contactTitle: 'Cotiza tu limpieza', contactSub: 'Cuéntanos qué necesitas limpiar y te damos un precio justo.',
    phone: '+51 945 330 220', address: 'Atención en Lima Metropolitana', hours: 'Lun–Sáb · 7:00 – 19:00', contactCta: 'Solicitar cotización', email: 'contacto@limpiototal.pe',
    footerAbout: 'Servicio de limpieza profesional en Lima para hogares, oficinas y empresas. Personal de confianza.',
    whatsappHref: 'https://wa.me/51945330220',
    pexels: { hero: 'cleaning service professional home', about: 'cleaning staff office professional' },
  },

  /* Fumigación / control de plagas */
  {
    slug: 'fumigacion', category: CAT, label: 'Control de plagas', brand: 'PlagaStop',
    fonts: { heading: 'Sora', body: 'Inter' },
    palette: { primary: '#2E8C4A', secondary: '#1A2E1E', accent: '#F0A030', bg: '#F5FAF4', text: '#182A1C' },
    plan: ['nav', 'heroSplit', 'stats', 'servicesGrid', 'process', 'faq', 'testimonials', 'contact', 'footer'],
    nav: ['Inicio', 'Servicios', 'Proceso', 'Contacto'], navCta: 'Solicita fumigación',
    eyebrow: 'Control de plagas · Lima', h1: 'Tu espacio libre de plagas, garantizado', sub: 'Fumigación y control de plagas para hogares y empresas. Productos seguros para tu familia y mascotas, con certificado y garantía.',
    cta1: 'Solicita fumigación', cta2: 'Ver servicios', heroPills: ['Productos seguros', 'Certificado incluido'],
    stats: [{ n: '8,000+', l: 'servicios realizados' }, { n: '100%', l: 'productos certificados' }, { n: 'Garantía', l: 'por escrito' }, { n: '4.9★', l: 'clientes' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Control integral de plagas',
    services: [{ t: 'Desinsectación', d: 'Cucarachas, hormigas, pulgas y zancudos.' }, { t: 'Desratización', d: 'Control efectivo de roedores.' }, { t: 'Control de termitas', d: 'Protegemos la madera de tu hogar.' }, { t: 'Desinfección', d: 'Eliminación de virus y bacterias.' }, { t: 'Fumigación de empresas', d: 'Restaurantes, almacenes y oficinas.' }, { t: 'Programas preventivos', d: 'Mantenimiento periódico para que no vuelvan.' }],
    processTitle: 'Cómo trabajamos',
    process: [{ t: 'Inspección', d: 'Evaluamos el tipo y nivel de plaga.' }, { t: 'Plan', d: 'Diseñamos el tratamiento adecuado.' }, { t: 'Aplicación', d: 'Fumigamos con productos seguros.' }, { t: 'Garantía', d: 'Certificado y seguimiento incluido.' }],
    faqTitle: 'Preguntas frecuentes',
    faq: [{ q: '¿Los productos son seguros para niños y mascotas?', a: 'Sí, usamos productos certificados; te indicamos el tiempo de reingreso.' }, { q: '¿Entregan certificado?', a: 'Sí, entregamos certificado de fumigación, útil para empresas y municipios.' }, { q: '¿Ofrecen garantía?', a: 'Sí, todos nuestros servicios incluyen garantía por escrito.' }],
    testiTitle: 'Lo que dicen nuestros clientes',
    testimonials: [{ q: 'Eliminaron la plaga de cucarachas que teníamos hace meses. Por fin tranquilos.', n: 'Familia Quiñones', r: 'Cliente' }, { q: 'Fumigan mi restaurante cada mes. Serios, puntuales y con certificado.', n: 'Restaurante El Buen Sabor', r: 'Cliente' }, { q: 'Productos sin olor fuerte y muy efectivos. Mis mascotas ni se enteraron.', n: 'Daniela Cruz', r: 'Cliente' }],
    contactTitle: 'Solicita tu fumigación', contactSub: 'Cuéntanos tu problema y te damos solución con garantía.',
    phone: '+51 945 660 880', address: 'Atención en Lima y Callao', hours: 'Lun–Dom · 7:00 – 20:00', contactCta: 'Solicitar servicio', email: 'contacto@plagastop.pe',
    footerAbout: 'Control de plagas y fumigación en Lima. Productos seguros, certificado y garantía para hogares y empresas.',
    whatsappHref: 'https://wa.me/51945660880',
    pexels: { hero: 'pest control technician spraying', about: 'pest control service home' },
  },

  /* Seguridad / vigilancia */
  {
    slug: 'seguridad', category: CAT, label: 'Seguridad / Vigilancia', brand: 'Guardian Seguridad',
    fonts: { heading: 'Oswald', body: 'Inter' },
    palette: { primary: '#1A2A3A', secondary: '#14202E', accent: '#C8A45C', bg: '#F6F7FA', text: '#18222E' },
    plan: ['nav', 'heroSplit', 'stats', 'servicesGrid', 'process', 'testimonials', 'contact', 'footer'],
    nav: ['Inicio', 'Servicios', 'Proceso', 'Contacto'], navCta: 'Solicita una cotización',
    eyebrow: 'Seguridad · Perú', h1: 'Protección profesional en la que confiar', sub: 'Servicios de vigilancia y seguridad para empresas, edificios y eventos. Personal capacitado y tecnología para tu tranquilidad.',
    cta1: 'Solicita cotización', cta2: 'Ver servicios', heroPills: ['Personal capacitado', 'Monitoreo 24/7'],
    stats: [{ n: '500+', l: 'agentes' }, { n: '18 años', l: 'de experiencia' }, { n: '24/7', l: 'monitoreo' }, { n: '4.9★', l: 'clientes' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Seguridad integral para ti',
    services: [{ t: 'Vigilancia física', d: 'Agentes capacitados para tu local o edificio.' }, { t: 'Seguridad para eventos', d: 'Control de acceso y orden en tu evento.' }, { t: 'Monitoreo de cámaras', d: 'Central de monitoreo CCTV 24/7.' }, { t: 'Resguardo empresarial', d: 'Protección para empresas e industrias.' }, { t: 'Control de accesos', d: 'Gestión de ingreso de personal y visitas.' }, { t: 'Consultoría de seguridad', d: 'Evaluamos y mejoramos tu seguridad.' }],
    processTitle: 'Cómo trabajamos',
    process: [{ t: 'Evaluación', d: 'Analizamos tus riesgos y necesidades.' }, { t: 'Propuesta', d: 'Diseñamos un plan de seguridad a medida.' }, { t: 'Implementación', d: 'Asignamos personal y tecnología.' }, { t: 'Supervisión', d: 'Monitoreamos y reportamos constantemente.' }],
    testiTitle: 'Empresas que confían su seguridad',
    testimonials: [{ q: 'El personal es serio y profesional. Nuestro edificio está en buenas manos.', n: 'Junta de Propietarios', r: 'Cliente' }, { q: 'Cubrieron nuestro evento de 2,000 personas sin un solo incidente. Top.', n: 'Productora de Eventos', r: 'Cliente' }, { q: 'El monitoreo 24/7 nos da total tranquilidad. Muy recomendados.', n: 'Industria del Sur', r: 'Cliente corporativo' }],
    contactTitle: 'Solicita una cotización', contactSub: 'Cuéntanos qué necesitas proteger y diseñamos tu plan.',
    phone: '+51 1 644 7070', address: 'Av. Colonial 1820, Cercado, Lima', hours: 'Atención 24 horas', contactCta: 'Solicitar cotización', email: 'contacto@guardianseguridad.pe',
    footerAbout: 'Empresa de seguridad y vigilancia en Lima. Personal capacitado y monitoreo 24/7 para tu tranquilidad.',
    whatsappHref: 'https://wa.me/5116447070',
    pexels: { hero: 'security guard professional building', about: 'security cctv monitoring control room' },
  },

  /* Aire acondicionado / refrigeración */
  {
    slug: 'refrigeracion', category: CAT, label: 'Aire acondicionado / Refrigeración', brand: 'ClimaTech',
    fonts: { heading: 'Sora', body: 'Inter' },
    palette: { primary: '#1E9BB0', secondary: '#14333A', accent: '#F0A030', bg: '#F4FBFB', text: '#16292F' },
    plan: ['nav', 'heroSplit', 'stats', 'servicesGrid', 'process', 'testimonials', 'ctaBanner', 'contact', 'footer'],
    nav: ['Inicio', 'Servicios', 'Proceso', 'Contacto'], navCta: 'Solicita servicio',
    eyebrow: 'Climatización · Lima', h1: 'El clima perfecto, todo el año', sub: 'Instalación, mantenimiento y reparación de aire acondicionado y refrigeración para hogares y empresas. Técnicos certificados.',
    cta1: 'Solicita un servicio', cta2: 'Ver servicios', heroPills: ['Técnicos certificados', 'Atención rápida'],
    stats: [{ n: '12,000+', l: 'equipos instalados' }, { n: '16 años', l: 'de experiencia' }, { n: 'Todas', l: 'las marcas' }, { n: '4.9★', l: 'clientes' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Soluciones de climatización',
    services: [{ t: 'Instalación de aire', d: 'Split, multisplit y sistemas centrales.' }, { t: 'Mantenimiento', d: 'Limpieza y recarga para que rinda más.' }, { t: 'Reparación', d: 'Diagnóstico y solución de fallas.' }, { t: 'Refrigeración comercial', d: 'Cámaras y equipos para tu negocio.' }, { t: 'Cámaras frigoríficas', d: 'Instalación y mantenimiento.' }, { t: 'Contratos empresariales', d: 'Mantenimiento programado para empresas.' }],
    processTitle: 'Cómo trabajamos',
    process: [{ t: 'Evaluación', d: 'Visitamos y recomendamos lo ideal.' }, { t: 'Cotización', d: 'Precio claro de equipo e instalación.' }, { t: 'Instalación', d: 'Trabajo limpio y profesional.' }, { t: 'Garantía', d: 'Respaldo y mantenimiento posterior.' }],
    testiTitle: 'Lo que dicen nuestros clientes',
    testimonials: [{ q: 'Instalaron el aire de mi casa rápido y limpio. Funciona perfecto. Excelentes.', n: 'Rodrigo Sánchez', r: 'Cliente' }, { q: 'Dan mantenimiento a los equipos de mi restaurante. Serios y cumplidos.', n: 'Cevichería El Puerto', r: 'Cliente' }, { q: 'Repararon mi aire que nadie podía arreglar. Técnicos de verdad capaces.', n: 'Lucía Paredes', r: 'Cliente' }],
    ctaTitle: '¿Necesitas instalar o reparar?', ctaSub: 'Escríbenos por WhatsApp y coordina tu servicio hoy mismo.',
    contactTitle: 'Solicita tu servicio', contactSub: 'Cuéntanos qué necesitas y te enviamos un técnico.',
    phone: '+51 945 220 990', address: 'Av. Argentina 2400, Cercado, Lima', hours: 'Lun–Sáb · 8:00 – 19:00', contactCta: 'Solicitar servicio', email: 'contacto@climatech.pe',
    footerAbout: 'Aire acondicionado y refrigeración en Lima. Instalación, mantenimiento y reparación con técnicos certificados.',
    whatsappHref: 'https://wa.me/51945220990',
    pexels: { hero: 'air conditioning technician installation', about: 'hvac technician repair unit' },
  },
];
