/* INDUSTRIA / B2B — 5 rubros. */
const CAT = 'Industria / B2B';

module.exports = [
  /* Distribuidora / mayorista */
  {
    slug: 'distribuidora', category: CAT, label: 'Distribuidora / Mayorista', brand: 'DistriMax',
    fonts: { heading: 'Sora', body: 'Inter' },
    palette: { primary: '#15568C', secondary: '#0E2435', accent: '#F0A030', bg: '#F6F8FB', text: '#16222E' },
    plan: ['nav', 'heroSplit', 'stats', 'servicesGrid', 'cards', 'testimonials', 'ctaBanner', 'contact', 'footer'],
    nav: ['Inicio', 'Servicios', 'Productos', 'Contacto'], navCta: 'Solicita catálogo',
    eyebrow: 'Distribuidora · Perú', h1: 'Tu socio mayorista de confianza', sub: 'Distribución de productos de consumo masivo a precios de mayorista, con stock permanente y entrega puntual a tu negocio.',
    cta1: 'Solicita el catálogo', cta2: 'Ver líneas', heroPills: ['Precios de mayorista', 'Entrega a tu local'],
    stats: [{ n: '3,000+', l: 'clientes (bodegas y tiendas)' }, { n: '5,000+', l: 'productos' }, { n: '24-48h', l: 'reposición' }, { n: '20 años', l: 'distribuyendo' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Más que distribución',
    services: [{ t: 'Precios de mayorista', d: 'Mejores márgenes para tu negocio.' }, { t: 'Entrega a tu local', d: 'Reparto puntual en toda Lima y provincias.' }, { t: 'Crédito comercial', d: 'Facilidades de pago para clientes frecuentes.' }, { t: 'Stock permanente', d: 'Siempre tendrás los productos que rotan.' }, { t: 'Atención dedicada', d: 'Un asesor comercial para tu negocio.' }, { t: 'Promociones', d: 'Ofertas y combos para vender más.' }],
    cardsEyebrow: 'Líneas', cardsTitle: 'Nuestras categorías', cardsCta: 'Cotizar',
    cards: [{ t: 'Abarrotes', d: 'Arroz, azúcar, aceite, fideos y más', p: 'Mayorista' }, { t: 'Bebidas', d: 'Gaseosas, agua, jugos y energizantes', p: 'Mayorista' }, { t: 'Limpieza', d: 'Detergentes, lejía y productos de hogar', p: 'Mayorista' }, { t: 'Snacks y golosinas', d: 'Galletas, caramelos y piqueos', p: 'Mayorista' }, { t: 'Cuidado personal', d: 'Shampoo, jabón y aseo', p: 'Mayorista' }, { t: 'Lácteos y conservas', d: 'Leche, atún y enlatados', p: 'Mayorista' }],
    ctaTitle: '¿Tienes un negocio?', ctaSub: 'Escríbenos por WhatsApp y recibe nuestra lista de precios mayorista.',
    contactTitle: 'Solicita tu catálogo', contactSub: 'Cuéntanos sobre tu negocio y te enviamos precios y condiciones.',
    phone: '+51 1 555 7070', address: 'Av. Argentina 2800, Cercado, Lima', hours: 'Lun–Sáb · 7:00 – 18:00', contactCta: 'Pedir catálogo', email: 'ventas@distrimax.pe',
    footerAbout: 'Distribuidora mayorista en Lima. Productos de consumo masivo con stock permanente y entrega a tu negocio.',
    whatsappHref: 'https://wa.me/5115557070',
    pexels: { hero: 'warehouse distribution products shelves', about: 'warehouse worker inventory', cards: ['grocery products shelf', 'beverages bottles', 'cleaning products', 'snacks candy', 'personal care products', 'canned food products'] },
  },

  /* Agroindustria / agroexportación */
  {
    slug: 'agro', category: CAT, label: 'Agroindustria / Agroexportación', brand: 'Valle Verde Agro',
    fonts: { heading: 'Sora', body: 'Inter' },
    palette: { primary: '#5BA02E', secondary: '#2A3A1E', accent: '#E0A93C', bg: '#F8FBF3', text: '#232A1A' },
    plan: ['nav', 'heroFullBg', 'stats', 'servicesGrid', 'featureSplit', 'gallery', 'testimonials', 'contact', 'footer'],
    nav: ['Inicio', 'Productos', 'Nosotros', 'Galería', 'Contacto'], navCta: 'Contáctanos',
    eyebrow: 'Agroindustria · Perú', h1: 'Del campo peruano al mundo', sub: 'Producción y exportación de frutas y vegetales frescos de la más alta calidad, con prácticas sostenibles y certificaciones internacionales.',
    cta1: 'Conoce nuestros productos', cta2: 'Sobre nosotros',
    stats: [{ n: '1,200 ha', l: 'de cultivo' }, { n: '15+', l: 'países de destino' }, { n: 'Global GAP', l: 'certificados' }, { n: '18 años', l: 'exportando' }],
    servicesEyebrow: 'Productos', servicesTitle: 'Lo mejor de nuestra tierra',
    services: [{ t: 'Arándanos', d: 'Frescos y dulces, calidad de exportación.' }, { t: 'Paltas Hass', d: 'Cremosas y reconocidas en el mundo.' }, { t: 'Uvas de mesa', d: 'Variedades sin pepa premium.' }, { t: 'Espárragos', d: 'Verdes y blancos, frescura garantizada.' }, { t: 'Mangos', d: 'Dulces y jugosos, sabor peruano.' }, { t: 'Cítricos', d: 'Mandarinas y naranjas seleccionadas.' }],
    aboutTitle: 'Cultivamos con responsabilidad', aboutBody: 'Combinamos la riqueza del suelo peruano con tecnología agrícola e innovación. Cuidamos cada etapa, del campo al packing, con prácticas sostenibles que respetan el medio ambiente y a nuestra gente.',
    aboutBullets: ['Certificaciones internacionales de calidad', 'Agricultura sostenible y responsable', 'Trazabilidad del campo a destino'],
    galleryEyebrow: 'Galería', galleryTitle: 'Nuestros campos y procesos',
    testiTitle: 'Socios comerciales en el mundo',
    testimonials: [{ q: 'La calidad y consistencia de su fruta es excelente. Un proveedor confiable.', n: 'Importadora EU', r: 'Cliente Europa' }, { q: 'Cumplen los estándares más exigentes. Trabajar con ellos es seguro.', n: 'Distribuidor USA', r: 'Cliente Norteamérica' }, { q: 'Compromiso con la calidad y la sostenibilidad. Excelente alianza.', n: 'Retailer Asia', r: 'Cliente Asia' }],
    contactTitle: 'Contáctanos', contactSub: 'Conversemos sobre oportunidades comerciales y de suministro.',
    phone: '+51 1 711 2020', address: 'Panamericana Norte Km 305, Chao, La Libertad', hours: 'Lun–Vie · 8:00 – 18:00', contactCta: 'Contactar', email: 'comercial@valleverdeagro.pe',
    footerAbout: 'Agroindustria peruana. Producimos y exportamos frutas y vegetales frescos con certificación internacional.',
    whatsappHref: 'https://wa.me/5117112020',
    pexels: { hero: 'agriculture field crops farm peru', about: 'farmer harvest fresh produce', gallery: ['blueberries fresh', 'avocado farm', 'grapes vineyard', 'asparagus field', 'mango fruit', 'agriculture packing'] },
  },

  /* Textil / confecciones */
  {
    slug: 'textil', category: CAT, label: 'Textil / Confecciones', brand: 'Hilo & Trama',
    fonts: { heading: 'Sora', body: 'Inter' },
    palette: { primary: '#7C3A5A', secondary: '#2A1A22', accent: '#C8A45C', bg: '#FAF6F4', text: '#2A2024' },
    plan: ['nav', 'heroSplit', 'stats', 'servicesGrid', 'process', 'gallery', 'testimonials', 'contact', 'footer'],
    nav: ['Inicio', 'Servicios', 'Proceso', 'Galería', 'Contacto'], navCta: 'Cotiza tu producción',
    eyebrow: 'Confecciones · Perú', h1: 'Confeccionamos tu marca con calidad', sub: 'Fabricación textil de prendas de algodón peruano para marcas y empresas. Full package, desde el diseño hasta la entrega.',
    cta1: 'Cotiza tu producción', cta2: 'Ver servicios', heroPills: ['Algodón peruano', 'Producción a escala'],
    stats: [{ n: '500,000+', l: 'prendas al año' }, { n: '100%', l: 'algodón peruano' }, { n: '22 años', l: 'confeccionando' }, { n: 'Export', l: 'calidad' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Tu producción, llave en mano',
    services: [{ t: 'Full package', d: 'Del diseño a la prenda terminada y etiquetada.' }, { t: 'Polos y camisetas', d: 'Algodón pima y jersey de primera.' }, { t: 'Uniformes corporativos', d: 'Para empresas, colegios e instituciones.' }, { t: 'Ropa deportiva', d: 'Telas técnicas y acabados de calidad.' }, { t: 'Estampado y bordado', d: 'Personaliza tus prendas con tu marca.' }, { t: 'Producción a escala', d: 'Grandes volúmenes con plazos cumplidos.' }],
    processTitle: 'Nuestro proceso',
    process: [{ t: 'Diseño', d: 'Desarrollamos tu prenda y ficha técnica.' }, { t: 'Muestra', d: 'Aprobamos contigo el prototipo.' }, { t: 'Producción', d: 'Confeccionamos con control de calidad.' }, { t: 'Entrega', d: 'Empacamos y entregamos a tiempo.' }],
    galleryEyebrow: 'Galería', galleryTitle: 'Nuestro trabajo y procesos',
    testiTitle: 'Marcas que confían en nosotros',
    testimonials: [{ q: 'La calidad de las prendas y el cumplimiento de plazos son impecables.', n: 'Marca Urbana', r: 'Cliente' }, { q: 'Confeccionaron los uniformes de toda mi empresa, perfectos. Recomendados.', n: 'Corporación SG', r: 'Cliente corporativo' }, { q: 'Excelente acabado y el algodón peruano se siente. Gran socio textil.', n: 'StreetBrand', r: 'Cliente' }],
    contactTitle: 'Cotiza tu producción', contactSub: 'Cuéntanos qué necesitas confeccionar y te asesoramos.',
    phone: '+51 1 423 4040', address: 'Jr. Gamarra 680, La Victoria, Lima', hours: 'Lun–Sáb · 8:00 – 18:00', contactCta: 'Solicitar cotización', email: 'ventas@hiloytrama.pe',
    footerAbout: 'Empresa textil en Lima. Confección full package de prendas en algodón peruano para marcas y empresas.',
    whatsappHref: 'https://wa.me/5114234040',
    pexels: { hero: 'textile factory clothing manufacturing', about: 'sewing machine textile worker', gallery: ['textile fabric rolls', 'sewing clothing factory', 'cotton t-shirts stack', 'screen printing shirt', 'garment production', 'clothing manufacturing'] },
  },

  /* Imprenta / artes gráficas */
  {
    slug: 'imprenta', category: CAT, label: 'Imprenta / Artes gráficas', brand: 'PrintLab',
    fonts: { heading: 'Sora', body: 'Inter' },
    palette: { primary: '#E0431E', secondary: '#1E1A18', accent: '#2563EB', bg: '#F6F5F3', text: '#1E1A18' },
    plan: ['nav', 'heroSplit', 'stats', 'cards', 'servicesGrid', 'process', 'testimonials', 'contact', 'footer'],
    nav: ['Inicio', 'Productos', 'Servicios', 'Contacto'], navCta: 'Cotiza tu impresión',
    eyebrow: 'Imprenta · Lima', h1: 'Tu marca impresa con calidad', sub: 'Impresión offset y digital para empresas y emprendedores. Desde tarjetas hasta gran formato, con acabados profesionales.',
    cta1: 'Cotiza tu impresión', cta2: 'Ver productos', heroPills: ['Entrega rápida', 'Diseño incluido'],
    stats: [{ n: '15 años', l: 'imprimiendo' }, { n: '10,000+', l: 'clientes' }, { n: '24-72h', l: 'entrega' }, { n: '4.8★', l: 'calidad' }],
    cardsEyebrow: 'Productos', cardsTitle: 'Imprimimos lo que necesites', cardsCta: 'Cotizar',
    cards: [{ tag: 'Top', t: 'Tarjetas de presentación', d: 'Diseños profesionales, varios acabados', p: 'Desde S/ 49' }, { t: 'Volantes y flyers', d: 'Para promocionar tu negocio', p: 'Desde S/ 89' }, { t: 'Banners y gigantografías', d: 'Gran formato de alta resolución', p: 'Desde S/ 35/m²' }, { t: 'Catálogos y revistas', d: 'Impresión y encuadernado', p: 'Cotización' }, { t: 'Etiquetas y stickers', d: 'Para tus productos', p: 'Desde S/ 59' }, { t: 'Merchandising', d: 'Tazas, polos, lapiceros personalizados', p: 'Cotización' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Todo en un solo lugar',
    services: [{ t: 'Diseño gráfico', d: 'Creamos tu pieza si no tienes el arte.' }, { t: 'Impresión offset y digital', d: 'La técnica ideal según tu volumen.' }, { t: 'Acabados profesionales', d: 'Laminado, troquel, relieve y más.' }],
    processTitle: 'Cómo trabajamos',
    process: [{ t: 'Cotización', d: 'Nos dices qué necesitas, te damos precio.' }, { t: 'Diseño', d: 'Aprobamos el arte juntos.' }, { t: 'Impresión', d: 'Producimos con calidad garantizada.' }, { t: 'Entrega', d: 'Lo recibes a tiempo, listo para usar.' }],
    testiTitle: 'Lo que dicen nuestros clientes',
    testimonials: [{ q: 'Las tarjetas quedaron espectaculares y la entrega fue rapidísima. Top.', n: 'Andrea Cuya', r: 'Cliente' }, { q: 'Imprimieron todo el material de mi evento sin un solo error. Profesionales.', n: 'Eventos LR', r: 'Cliente' }, { q: 'Buen precio, buena calidad y diseño incluido. Mi imprenta de confianza.', n: 'Bodega El Sol', r: 'Cliente' }],
    contactTitle: 'Cotiza tu impresión', contactSub: 'Cuéntanos qué necesitas imprimir y te cotizamos al instante.',
    phone: '+51 945 770 220', address: 'Jr. de la Unión 820, Cercado, Lima', hours: 'Lun–Sáb · 9:00 – 19:00', contactCta: 'Cotizar ahora', email: 'ventas@printlab.pe',
    footerAbout: 'Imprenta en Lima. Offset y digital para empresas y emprendedores, con diseño incluido y entrega rápida.',
    whatsappHref: 'https://wa.me/51945770220',
    pexels: { hero: 'printing press graphic design shop', cards: ['business cards print', 'flyers brochures', 'banner large format', 'magazine catalog print', 'product labels stickers', 'merchandising mugs'] },
  },

  /* Importadora */
  {
    slug: 'importadora', category: CAT, label: 'Importadora', brand: 'Global Import',
    fonts: { heading: 'Sora', body: 'Inter' },
    palette: { primary: '#1C3A5E', secondary: '#14253B', accent: '#C8A45C', bg: '#F7F8FB', text: '#1A2330' },
    plan: ['nav', 'heroSplit', 'stats', 'servicesGrid', 'cards', 'process', 'contact', 'footer'],
    nav: ['Inicio', 'Servicios', 'Productos', 'Contacto'], navCta: 'Contáctanos',
    eyebrow: 'Importadora · Perú', h1: 'Traemos el mundo a tu negocio', sub: 'Importación y comercialización de productos para el hogar, ferretería y consumo. Calidad garantizada y precios competitivos al por mayor.',
    cta1: 'Solicita catálogo', cta2: 'Ver líneas', heroPills: ['Precios mayoristas', 'Stock importado'],
    stats: [{ n: '20 años', l: 'importando' }, { n: '2,000+', l: 'clientes mayoristas' }, { n: '8+', l: 'líneas de producto' }, { n: 'Stock', l: 'permanente' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Tu proveedor importador',
    services: [{ t: 'Venta al por mayor', d: 'Precios competitivos por volumen.' }, { t: 'Importación a pedido', d: 'Traemos el producto que tu negocio necesita.' }, { t: 'Distribución nacional', d: 'Entregamos a todo el Perú.' }, { t: 'Stock permanente', d: 'Disponibilidad continua de las líneas top.' }, { t: 'Crédito comercial', d: 'Facilidades para clientes frecuentes.' }, { t: 'Asesoría comercial', d: 'Te ayudamos a elegir lo que más rota.' }],
    cardsEyebrow: 'Líneas', cardsTitle: 'Nuestras categorías', cardsCta: 'Cotizar',
    cards: [{ t: 'Hogar y bazar', d: 'Utensilios, organización y menaje', p: 'Mayorista' }, { t: 'Ferretería', d: 'Herramientas y accesorios', p: 'Mayorista' }, { t: 'Electrodomésticos menores', d: 'Línea blanca y cocina', p: 'Mayorista' }, { t: 'Juguetería', d: 'Variedad para todas las edades', p: 'Mayorista' }, { t: 'Temporada', d: 'Campañas escolar, navidad y más', p: 'Mayorista' }, { t: 'Tecnología y accesorios', d: 'Gadgets y complementos', p: 'Mayorista' }],
    processTitle: 'Cómo comprar',
    process: [{ t: 'Catálogo', d: 'Te enviamos nuestra lista y precios.' }, { t: 'Pedido', d: 'Eliges tus productos y cantidades.' }, { t: 'Pago', d: 'Contado o crédito según tu perfil.' }, { t: 'Entrega', d: 'Despachamos a tu local o agencia.' }],
    contactTitle: 'Solicita tu catálogo', contactSub: 'Cuéntanos sobre tu negocio y te enviamos precios mayoristas.',
    phone: '+51 1 533 6060', address: 'Av. Aviación 4200, Surquillo, Lima', hours: 'Lun–Sáb · 8:30 – 18:00', contactCta: 'Pedir catálogo', email: 'ventas@globalimport.pe',
    footerAbout: 'Importadora en Lima. Productos para hogar, ferretería y consumo al por mayor con stock permanente.',
    whatsappHref: 'https://wa.me/5115336060',
    pexels: { hero: 'import warehouse products containers', cards: ['home goods kitchenware', 'hardware tools', 'small appliances', 'toys variety', 'seasonal products', 'tech gadgets accessories'] },
  },
];
