/* LOGÍSTICA Y TRANSPORTE — 4 rubros. */
const CAT = 'Logística y transporte';

module.exports = [
  /* Transporte / carga */
  {
    slug: 'transporte', category: CAT, label: 'Transporte / Carga', brand: 'TransCarga Perú',
    fonts: { heading: 'Sora', body: 'Inter' },
    palette: { primary: '#15568C', secondary: '#0E2435', accent: '#F0A030', bg: '#F6F8FB', text: '#16222E' },
    plan: ['nav', 'heroSplit', 'stats', 'servicesGrid', 'process', 'testimonials', 'contact', 'footer'],
    nav: ['Inicio', 'Servicios', 'Proceso', 'Contacto'], navCta: 'Cotiza tu envío',
    eyebrow: 'Transporte de carga · Perú', h1: 'Tu carga, segura y a tiempo', sub: 'Transporte de carga a nivel nacional con flota propia, rastreo en tiempo real y la puntualidad que tu negocio necesita.',
    cta1: 'Cotiza tu envío', cta2: 'Ver servicios', heroPills: ['Cobertura nacional', 'Rastreo GPS'],
    stats: [{ n: '50+', l: 'unidades en flota' }, { n: '24 regiones', l: 'de cobertura' }, { n: '99%', l: 'entregas a tiempo' }, { n: '18 años', l: 'de experiencia' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Soluciones logísticas a tu medida',
    services: [{ t: 'Carga nacional', d: 'Transporte a todo el Perú con flota propia.' }, { t: 'Carga pesada', d: 'Unidades para grandes volúmenes y maquinaria.' }, { t: 'Distribución', d: 'Última milla y reparto a tus clientes.' }, { t: 'Almacenaje', d: 'Espacios seguros para tu mercadería.' }, { t: 'Rastreo GPS', d: 'Monitoreo de tu carga en tiempo real.' }, { t: 'Carga refrigerada', d: 'Cadena de frío para productos sensibles.' }],
    processTitle: 'Cómo trabajamos',
    process: [{ t: 'Cotización', d: 'Nos dices qué y a dónde, te damos precio.' }, { t: 'Recojo', d: 'Recogemos tu carga en el punto acordado.' }, { t: 'En ruta', d: 'Sigue tu envío con rastreo en tiempo real.' }, { t: 'Entrega', d: 'Entregamos a tiempo y con confirmación.' }],
    testiTitle: 'Empresas que confían su carga',
    testimonials: [{ q: 'Nunca nos han fallado con una entrega. Puntualidad y seriedad total.', n: 'Distribuidora Andina', r: 'Cliente corporativo' }, { q: 'El rastreo en tiempo real nos da total tranquilidad. Excelente servicio.', n: 'Comercial del Sur', r: 'Cliente' }, { q: 'Movieron maquinaria pesada sin un solo problema. Muy profesionales.', n: 'Constructora Lima', r: 'Cliente' }],
    contactTitle: 'Cotiza tu envío', contactSub: 'Cuéntanos qué necesitas transportar y te damos una cotización rápida.',
    phone: '+51 1 666 4040', address: 'Av. Argentina 3200, Callao, Lima', hours: 'Lun–Sáb · 7:00 – 19:00', contactCta: 'Solicitar cotización', email: 'operaciones@transcarga.pe',
    footerAbout: 'Empresa de transporte de carga con cobertura nacional, flota propia y rastreo GPS en tiempo real.',
    whatsappHref: 'https://wa.me/5116664040',
    pexels: { hero: 'cargo truck logistics highway', about: 'logistics warehouse trucks' },
  },

  /* Courier / mensajería */
  {
    slug: 'courier', category: CAT, label: 'Courier / Mensajería', brand: 'RapiEnvíos',
    fonts: { heading: 'Sora', body: 'Inter' },
    palette: { primary: '#E0431E', secondary: '#2A1614', accent: '#F0A82E', bg: '#FBF6F2', text: '#241814' },
    plan: ['nav', 'heroSplit', 'stats', 'servicesGrid', 'process', 'testimonials', 'ctaBanner', 'contact', 'footer'],
    nav: ['Inicio', 'Servicios', 'Proceso', 'Contacto'], navCta: 'Pedir recojo',
    eyebrow: 'Courier · Lima', h1: 'Entregas rápidas, clientes felices', sub: 'Servicio de mensajería y delivery para tu negocio. Recogemos y entregamos en toda Lima, el mismo día.',
    cta1: 'Pide un recojo', cta2: 'Ver servicios', heroPills: ['Entrega el mismo día', 'Para e-commerce'],
    stats: [{ n: '500,000+', l: 'entregas realizadas' }, { n: 'Mismo día', l: 'en Lima' }, { n: '2h', l: 'entregas express' }, { n: '4.8★', l: 'puntualidad' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Logística para tu negocio',
    services: [{ t: 'Delivery same-day', d: 'Entregas en Lima el mismo día.' }, { t: 'Express 2 horas', d: 'Cuando no puede esperar.' }, { t: 'E-commerce', d: 'Integramos con tu tienda online.' }, { t: 'Mensajería corporativa', d: 'Documentos y paquetes empresariales.' }, { t: 'Pago contra entrega', d: 'Cobramos por ti al entregar.' }, { t: 'Envíos programados', d: 'Rutas recurrentes para tu operación.' }],
    processTitle: 'Tan fácil como',
    process: [{ t: 'Solicita', d: 'Pídenos el recojo por WhatsApp o web.' }, { t: 'Recogemos', d: 'Vamos por tu paquete donde estés.' }, { t: 'En camino', d: 'Tu cliente sigue la entrega en vivo.' }, { t: 'Entregado', d: 'Confirmación inmediata al entregar.' }],
    testiTitle: 'Negocios que crecen con nosotros',
    testimonials: [{ q: 'Desde que trabajo con ellos, mis clientes reciben el mismo día. Subieron mis ventas.', n: 'Tienda Bella', r: 'E-commerce' }, { q: 'Puntuales y confiables. El pago contra entrega me facilita todo.', n: 'Karen Salas', r: 'Emprendedora' }, { q: 'El mejor courier para mi negocio online. 100% recomendados.', n: 'StoreLima', r: 'Cliente' }],
    ctaTitle: '¿Necesitas entregar hoy?', ctaSub: 'Escríbenos por WhatsApp y coordinamos el recojo al instante.',
    contactTitle: 'Pide tu recojo', contactSub: 'Coordina tu envío y entregamos por ti.',
    phone: '+51 940 660 220', address: 'Atención en toda Lima Metropolitana', hours: 'Lun–Sáb · 8:00 – 20:00', contactCta: 'Pedir recojo', email: 'hola@rapienvios.pe',
    footerAbout: 'Courier y mensajería en Lima. Entregas el mismo día para tu negocio y e-commerce.',
    whatsappHref: 'https://wa.me/51940660220',
    pexels: { hero: 'courier delivery package motorcycle', about: 'delivery man package box' },
  },

  /* Mudanzas */
  {
    slug: 'mudanzas', category: CAT, label: 'Mudanzas', brand: 'Mudanzas Express',
    fonts: { heading: 'Sora', body: 'Inter' },
    palette: { primary: '#1E7A8C', secondary: '#143038', accent: '#F0A030', bg: '#F4FAFB', text: '#16292F' },
    plan: ['nav', 'heroSplit', 'stats', 'servicesGrid', 'process', 'testimonials', 'ctaBanner', 'contact', 'footer'],
    nav: ['Inicio', 'Servicios', 'Proceso', 'Contacto'], navCta: 'Cotiza tu mudanza',
    eyebrow: 'Mudanzas · Lima', h1: 'Tu mudanza sin estrés ni sorpresas', sub: 'Embalamos, trasladamos e instalamos. Cuidamos cada cosa como si fuera nuestra, para que tú solo te preocupes de llegar.',
    cta1: 'Cotiza tu mudanza', cta2: 'Ver servicios', heroPills: ['Embalaje incluido', 'Seguro de traslado'],
    stats: [{ n: '8,000+', l: 'mudanzas realizadas' }, { n: '14 años', l: 'de experiencia' }, { n: '100%', l: 'carga asegurada' }, { n: '4.9★', l: 'clientes' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Todo lo que tu mudanza necesita',
    services: [{ t: 'Mudanza residencial', d: 'Casas y departamentos, dentro y fuera de Lima.' }, { t: 'Mudanza de oficinas', d: 'Trasladamos tu empresa sin parar tu operación.' }, { t: 'Embalaje profesional', d: 'Protegemos cada objeto con materiales adecuados.' }, { t: 'Desarme y armado', d: 'Nos encargamos de tus muebles.' }, { t: 'Guardamuebles', d: 'Almacenaje seguro por el tiempo que necesites.' }, { t: 'Mudanza nacional', d: 'Te llevamos a cualquier región del país.' }],
    processTitle: 'Cómo lo hacemos',
    process: [{ t: 'Cotización', d: 'Evaluamos y te damos un precio cerrado.' }, { t: 'Embalaje', d: 'Protegemos todo con cuidado profesional.' }, { t: 'Traslado', d: 'Movemos tu carga de forma segura.' }, { t: 'Instalación', d: 'Armamos y ubicamos todo en tu nuevo hogar.' }],
    testiTitle: 'Mudanzas que salieron perfectas',
    testimonials: [{ q: 'Mudaron toda mi casa sin un solo rayón. Súper cuidadosos y rápidos.', n: 'Verónica Lazo', r: 'Mudanza residencial' }, { q: 'Trasladaron mi oficina en un fin de semana. El lunes ya operábamos.', n: 'Gerencia, Estudio JM', r: 'Mudanza de oficina' }, { q: 'Precio cerrado, sin sorpresas. Profesionales de principio a fin.', n: 'Daniel Ruiz', r: 'Cliente' }],
    ctaTitle: '¿Te mudas pronto?', ctaSub: 'Escríbenos por WhatsApp y cotiza tu mudanza sin compromiso.',
    contactTitle: 'Cotiza tu mudanza', contactSub: 'Cuéntanos de dónde a dónde y te damos un precio cerrado.',
    phone: '+51 945 770 660', address: 'Av. Tomás Marsano 2100, Surco, Lima', hours: 'Lun–Dom · 7:00 – 20:00', contactCta: 'Solicitar cotización', email: 'contacto@mudanzasexpress.pe',
    footerAbout: 'Empresa de mudanzas en Lima. Embalamos, trasladamos e instalamos con carga asegurada.',
    whatsappHref: 'https://wa.me/51945770660',
    pexels: { hero: 'moving boxes truck home relocation', about: 'movers carrying furniture boxes' },
  },

  /* Agencia de aduanas */
  {
    slug: 'aduanas', category: CAT, label: 'Agencia de aduanas', brand: 'Global Aduanas',
    fonts: { heading: 'Sora', body: 'Inter' },
    palette: { primary: '#1C3A5E', secondary: '#14253B', accent: '#B8924A', bg: '#F7F8FB', text: '#1A2330' },
    plan: ['nav', 'heroSplit', 'stats', 'servicesGrid', 'process', 'faq', 'contact', 'footer'],
    nav: ['Inicio', 'Servicios', 'Proceso', 'Contacto'], navCta: 'Asesórate',
    eyebrow: 'Agencia de aduanas · Perú', h1: 'Importa y exporta sin complicaciones', sub: 'Gestionamos tus operaciones aduaneras con agilidad y cumplimiento. Tu carga liberada a tiempo, sin sobrecostos.',
    cta1: 'Solicita asesoría', cta2: 'Ver servicios', heroPills: ['Agentes autorizados', 'Asesoría sin costo'],
    stats: [{ n: '15 años', l: 'de experiencia' }, { n: '10,000+', l: 'despachos' }, { n: '100%', l: 'cumplimiento' }, { n: '4.9★', l: 'clientes' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Soluciones de comercio exterior',
    services: [{ t: 'Despacho de importación', d: 'Nacionalizamos tu carga con rapidez.' }, { t: 'Despacho de exportación', d: 'Llevamos tus productos al mundo.' }, { t: 'Asesoría arancelaria', d: 'Clasificación correcta y ahorro en tributos.' }, { t: 'Logística internacional', d: 'Coordinamos tu carga de origen a destino.' }, { t: 'Régimen aduanero', d: 'Drawback, admisión temporal y más.' }, { t: 'Gestión documentaria', d: 'Tramitamos toda tu documentación.' }],
    processTitle: 'Nuestro proceso',
    process: [{ t: 'Asesoría', d: 'Analizamos tu operación, sin costo.' }, { t: 'Documentación', d: 'Preparamos todo para el despacho.' }, { t: 'Despacho', d: 'Gestionamos ante aduanas con agilidad.' }, { t: 'Entrega', d: 'Tu carga liberada y lista a tiempo.' }],
    faqTitle: 'Preguntas frecuentes',
    faq: [{ q: '¿Atienden importadores nuevos?', a: 'Sí, te acompañamos desde tu primera importación, paso a paso.' }, { q: '¿La asesoría tiene costo?', a: 'La asesoría inicial para evaluar tu operación es gratuita.' }, { q: '¿En qué aduanas operan?', a: 'Operamos en las principales aduanas del país: marítima, aérea y terrestre.' }],
    contactTitle: 'Solicita tu asesoría', contactSub: 'Cuéntanos sobre tu operación y te orientamos sin compromiso.',
    phone: '+51 1 429 8080', address: 'Av. Sáenz Peña 480, Callao, Lima', hours: 'Lun–Vie · 8:30 – 18:00', contactCta: 'Solicitar asesoría', email: 'operaciones@globaladuanas.pe',
    footerAbout: 'Agencia de aduanas en el Callao. Gestionamos tus importaciones y exportaciones con cumplimiento y agilidad.',
    whatsappHref: 'https://wa.me/5114298080',
    pexels: { hero: 'shipping port containers customs', about: 'cargo containers logistics port' },
  },
];
