/* SERVICIOS PROFESIONALES — 8 rubros (juridico ya está en sectors.js base). */
const CAT = 'Servicios profesionales';

module.exports = [
  /* Contabilidad */
  {
    slug: 'contabilidad', category: CAT, label: 'Estudio contable', brand: 'Cifra Contadores',
    fonts: { heading: 'Sora', body: 'Inter' },
    palette: { primary: '#2A5D8C', secondary: '#14233B', accent: '#D4A53C', bg: '#F7F9FB', text: '#1A2330' },
    plan: ['nav', 'heroSplit', 'stats', 'servicesGrid', 'process', 'testimonials', 'faq', 'contact', 'footer'],
    nav: ['Inicio', 'Servicios', 'Proceso', 'Contacto'], navCta: 'Asesórate gratis',
    eyebrow: 'Estudio contable · Lima', h1: 'Tu contabilidad al día, sin preocupaciones', sub: 'Llevamos tus impuestos, planillas y declaraciones SUNAT con precisión, para que te dediques a hacer crecer tu negocio.',
    cta1: 'Solicita asesoría gratis', cta2: 'Ver servicios', heroPills: ['Primera asesoría sin costo', 'Atención a tiempo'],
    stats: [{ n: '18 años', l: 'de experiencia' }, { n: '600+', l: 'empresas asesoradas' }, { n: '0', l: 'multas por atrasos' }, { n: '4.9★', l: 'satisfacción' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Soluciones contables y tributarias',
    services: [{ t: 'Contabilidad mensual', d: 'Registro, balances y estados financieros al día.' }, { t: 'Tributación SUNAT', d: 'Declaraciones, IGV, renta y fraccionamientos.' }, { t: 'Planillas y RRHH', d: 'Cálculo de sueldos, CTS, gratificaciones y AFP.' }, { t: 'Constitución de empresas', d: 'Te ayudamos a formalizar tu negocio desde cero.' }, { t: 'Asesoría financiera', d: 'Decisiones con números claros y confiables.' }, { t: 'Auditoría', d: 'Revisión y diagnóstico de tu situación contable.' }],
    processTitle: 'Cómo trabajamos contigo',
    process: [{ t: 'Diagnóstico', d: 'Revisamos el estado de tu contabilidad sin costo.' }, { t: 'Propuesta', d: 'Te damos un plan claro con tarifa fija mensual.' }, { t: 'Gestión', d: 'Nos encargamos de todo, tú recibes reportes.' }, { t: 'Tranquilidad', d: 'Siempre al día con SUNAT, sin sorpresas.' }],
    testiTitle: 'Empresas que confían en nosotros',
    testimonials: [{ q: 'Desde que los contraté, nunca más tuve una multa de SUNAT. Excelentes.', n: 'Roberto Lazo', r: 'Gerente, Comercial RL' }, { q: 'Me explican todo en simple. Por fin entiendo mis números.', n: 'Patricia Vega', r: 'Emprendedora' }, { q: 'Formalizaron mi empresa rapidísimo y me asesoran cada mes.', n: 'Daniel Ortiz', r: 'Dueño de restaurante' }],
    faqTitle: 'Preguntas frecuentes',
    faq: [{ q: '¿Trabajan con empresas pequeñas?', a: 'Sí, desde personas naturales con negocio hasta medianas empresas.' }, { q: '¿La tarifa es fija?', a: 'Sí, trabajamos con una mensualidad clara según tu volumen.' }, { q: '¿Atienden de forma remota?', a: 'Sí, puedes enviarnos todo digital y recibir tus reportes online.' }],
    contactTitle: 'Solicita tu asesoría gratuita', contactSub: 'Cuéntanos sobre tu negocio y te damos una propuesta clara.',
    phone: '+51 1 433 5566', address: 'Av. Petit Thouars 4500, Miraflores, Lima', hours: 'Lun–Vie · 9:00 – 18:00', contactCta: 'Quiero asesoría', email: 'contacto@cifracontadores.pe',
    footerAbout: 'Estudio contable con 18 años llevando la contabilidad de empresas peruanas al día y sin multas.',
    whatsappHref: 'https://wa.me/5114335566',
    pexels: { hero: 'accountant office calculator documents', about: 'accounting financial advisor meeting' },
  },

  /* Consultoría empresarial */
  {
    slug: 'consultoria', category: CAT, label: 'Consultoría empresarial', brand: 'Rumbo Consultores',
    fonts: { heading: 'Sora', body: 'Inter' },
    palette: { primary: '#3A4FA0', secondary: '#1A1F40', accent: '#E0954C', bg: '#F8F8FC', text: '#1E2230' },
    plan: ['nav', 'heroSplit', 'stats', 'servicesGrid', 'process', 'testimonials', 'ctaBanner', 'contact', 'footer'],
    nav: ['Inicio', 'Servicios', 'Metodología', 'Contacto'], navCta: 'Agenda una reunión',
    eyebrow: 'Consultoría · Lima', h1: 'Llevamos tu empresa al siguiente nivel', sub: 'Estrategia, procesos y crecimiento. Te ayudamos a tomar mejores decisiones con datos, no con corazonadas.',
    cta1: 'Agenda una reunión', cta2: 'Cómo trabajamos', heroPills: ['Diagnóstico inicial gratis', 'Resultados medibles'],
    stats: [{ n: '120+', l: 'empresas potenciadas' }, { n: '+35%', l: 'crecimiento promedio' }, { n: '14 años', l: 'de experiencia' }, { n: '4.9★', l: 'recomendación' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Consultoría que genera resultados',
    services: [{ t: 'Estrategia de negocio', d: 'Define el rumbo y los objetivos de tu empresa.' }, { t: 'Optimización de procesos', d: 'Haz más con menos: eficiencia y productividad.' }, { t: 'Transformación digital', d: 'Moderniza tu operación con la tecnología correcta.' }, { t: 'Gestión comercial', d: 'Aumenta tus ventas con procesos claros.' }, { t: 'Plan financiero', d: 'Control de costos y proyección de crecimiento.' }, { t: 'Capacitación', d: 'Formamos a tu equipo para sostener el cambio.' }],
    processTitle: 'Nuestra metodología',
    process: [{ t: 'Diagnóstico', d: 'Analizamos tu empresa a fondo, gratis.' }, { t: 'Estrategia', d: 'Diseñamos un plan de acción a tu medida.' }, { t: 'Implementación', d: 'Ejecutamos contigo, paso a paso.' }, { t: 'Medición', d: 'Seguimos resultados y ajustamos.' }],
    testiTitle: 'Lo que logran nuestros clientes',
    testimonials: [{ q: 'Reorganizaron nuestros procesos y crecimos 40% en un año. Brutales.', n: 'Andrés Quevedo', r: 'CEO, Distribuidora AQ' }, { q: 'Nos dieron claridad estratégica que no teníamos. Un antes y un después.', n: 'Lorena Bustos', r: 'Gerente, Retail LB' }, { q: 'Profesionales, prácticos y con resultados reales. Recomendados.', n: 'Marco Tello', r: 'Fundador, TechMarco' }],
    ctaTitle: '¿Listo para crecer en serio?', ctaSub: 'Conversemos sobre tu empresa. El diagnóstico inicial es gratis.',
    contactTitle: 'Agenda tu reunión', contactSub: 'Cuéntanos tu reto y te mostramos cómo resolverlo.',
    phone: '+51 1 700 8080', address: 'Av. Camino Real 1180, San Isidro, Lima', hours: 'Lun–Vie · 9:00 – 18:00', contactCta: 'Agendar reunión', email: 'hola@rumboconsultores.pe',
    footerAbout: 'Consultoría empresarial en Lima. Estrategia y procesos para que tu empresa crezca con datos.',
    whatsappHref: 'https://wa.me/5117008080',
    pexels: { hero: 'business consulting team meeting', about: 'business strategy whiteboard' },
  },

  /* Notaría */
  {
    slug: 'notaria', category: CAT, label: 'Notaría', brand: 'Notaría Del Águila',
    fonts: { heading: 'Playfair Display', body: 'Source Sans 3' },
    palette: { primary: '#1C3A5E', secondary: '#14253B', accent: '#B8924A', bg: '#F8F7F3', text: '#1F2530' },
    plan: ['nav', 'heroSplit', 'stats', 'servicesGrid', 'faq', 'contact', 'footer'],
    nav: ['Inicio', 'Servicios', 'Contacto'], navCta: 'Consultar trámite',
    eyebrow: 'Notaría · Lima', h1: 'Trámites notariales con total seguridad', sub: 'Más de 30 años dando fe pública con rapidez, formalidad y atención cercana a personas y empresas.',
    cta1: 'Consulta tu trámite', cta2: 'Ver servicios', heroPills: ['Atención el mismo día', 'Trámites en línea'],
    stats: [{ n: '30+', l: 'años dando fe' }, { n: '100,000+', l: 'escrituras' }, { n: 'Mismo día', l: 'muchos trámites' }, { n: '4.8★', l: 'atención' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Servicios notariales completos',
    services: [{ t: 'Escrituras públicas', d: 'Compraventa de inmuebles, vehículos y más.' }, { t: 'Poderes', d: 'Poderes fuera de registro y por escritura pública.' }, { t: 'Constitución de empresas', d: 'Formaliza tu empresa con respaldo notarial.' }, { t: 'Legalización de firmas', d: 'Certificación de firmas y documentos.' }, { t: 'Actas y certificaciones', d: 'Cartas notariales, actas y copias certificadas.' }, { t: 'Sucesiones', d: 'Sucesión intestada y trámites de herencia.' }],
    faqTitle: 'Preguntas frecuentes',
    faq: [{ q: '¿Atienden trámites el mismo día?', a: 'Muchos trámites se resuelven el mismo día según su complejidad.' }, { q: '¿Puedo iniciar trámites en línea?', a: 'Sí, coordina por WhatsApp y agilizamos tu atención.' }, { q: '¿Qué documentos necesito?', a: 'Te indicamos exactamente qué llevar según tu trámite.' }],
    contactTitle: 'Consulta tu trámite', contactSub: 'Escríbenos y te orientamos sobre tu trámite notarial.',
    phone: '+51 1 421 9090', address: 'Av. Larco 880, Miraflores, Lima', hours: 'Lun–Vie · 8:30 – 18:00 · Sáb 9:00 – 13:00', contactCta: 'Consultar trámite', email: 'mesadepartes@notariadelaguila.pe',
    footerAbout: 'Notaría en Miraflores con más de 30 años dando fe pública con seguridad y rapidez.',
    whatsappHref: 'https://wa.me/5114219090',
    pexels: { hero: 'notary signing legal documents', about: 'legal documents signature pen' },
  },

  /* Arquitectura */
  {
    slug: 'arquitectura', category: CAT, label: 'Estudio de arquitectura', brand: 'Forma Estudio',
    fonts: { heading: 'Space Grotesk', body: 'Inter' },
    palette: { primary: '#2A2A2A', secondary: '#171717', accent: '#C0A062', bg: '#F6F5F2', text: '#1F1F1F' },
    plan: ['nav', 'heroMinimal', 'stats', 'gallery', 'servicesGrid', 'process', 'contact', 'footer'],
    nav: ['Inicio', 'Proyectos', 'Servicios', 'Contacto'], navCta: 'Conversemos',
    eyebrow: 'Arquitectura & Diseño', h1: 'Diseñamos espacios que inspiran', sub: 'Arquitectura contemporánea con propósito. Convertimos tus ideas en lugares para vivir y trabajar.',
    cta1: 'Ver proyectos', cta2: 'Conversemos',
    stats: [{ n: '90+', l: 'proyectos entregados' }, { n: '12 años', l: 'creando espacios' }, { n: '8', l: 'premios de diseño' }, { n: '100%', l: 'a la medida' }],
    galleryEyebrow: 'Portafolio', galleryTitle: 'Proyectos que hablan por sí solos',
    servicesEyebrow: 'Servicios', servicesTitle: 'De la idea a la obra',
    services: [{ t: 'Diseño arquitectónico', d: 'Proyectos residenciales, comerciales y corporativos.' }, { t: 'Interiorismo', d: 'Espacios interiores funcionales y con carácter.' }, { t: 'Remodelaciones', d: 'Renovamos y revalorizamos tus ambientes.' }, { t: 'Gestión de obra', d: 'Supervisamos la construcción de principio a fin.' }],
    processTitle: 'Nuestro proceso',
    process: [{ t: 'Concepto', d: 'Entendemos tu visión, estilo y necesidades.' }, { t: 'Diseño', d: 'Desarrollamos planos y render 3D realistas.' }, { t: 'Desarrollo', d: 'Detallamos ingeniería y especificaciones.' }, { t: 'Obra', d: 'Acompañamos la construcción hasta la entrega.' }],
    contactTitle: 'Conversemos sobre tu proyecto', contactSub: 'Cuéntanos qué imaginas y lo hacemos realidad.',
    phone: '+51 988 440 220', address: 'Calle Berlín 420, Miraflores, Lima', hours: 'Lun–Vie · 9:00 – 18:00', contactCta: 'Iniciar proyecto', email: 'estudio@formaestudio.pe',
    footerAbout: 'Estudio de arquitectura en Lima. Diseñamos espacios contemporáneos con propósito y carácter.',
    whatsappHref: 'https://wa.me/51988440220',
    pexels: { hero: 'modern architecture building design', gallery: ['modern house architecture', 'minimalist interior design', 'modern building facade', 'architecture interior space', 'modern villa exterior', 'concrete architecture'] },
  },

  /* Ingeniería */
  {
    slug: 'ingenieria', category: CAT, label: 'Ingeniería', brand: 'Estructura Ingeniería',
    fonts: { heading: 'Sora', body: 'Inter' },
    palette: { primary: '#15568C', secondary: '#0E2A45', accent: '#F0A030', bg: '#F6F8FA', text: '#18222E' },
    plan: ['nav', 'heroSplit', 'stats', 'servicesGrid', 'gallery', 'process', 'testimonials', 'contact', 'footer'],
    nav: ['Inicio', 'Servicios', 'Proyectos', 'Contacto'], navCta: 'Solicitar cotización',
    eyebrow: 'Ingeniería · Perú', h1: 'Ingeniería que construye confianza', sub: 'Proyectos de ingeniería civil, estructural y de instalaciones con los más altos estándares de calidad y seguridad.',
    cta1: 'Solicita cotización', cta2: 'Ver proyectos', heroPills: ['Equipo colegiado', 'Cumplimiento normativo'],
    stats: [{ n: '200+', l: 'proyectos ejecutados' }, { n: '20 años', l: 'de trayectoria' }, { n: '100%', l: 'normativa vigente' }, { n: '0', l: 'accidentes graves' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Soluciones de ingeniería integral',
    services: [{ t: 'Ingeniería estructural', d: 'Diseño y cálculo de estructuras seguras.' }, { t: 'Obras civiles', d: 'Edificaciones, infraestructura y urbanismo.' }, { t: 'Instalaciones', d: 'Eléctricas, sanitarias y mecánicas.' }, { t: 'Supervisión de obra', d: 'Control de calidad, plazos y presupuesto.' }, { t: 'Estudios y peritajes', d: 'Suelos, estructuras y diagnósticos técnicos.' }, { t: 'Saneamiento físico', d: 'Regularización y licencias de tu obra.' }],
    galleryEyebrow: 'Proyectos', galleryTitle: 'Obras que respaldan nuestra experiencia',
    processTitle: 'Cómo ejecutamos',
    process: [{ t: 'Estudio', d: 'Analizamos el terreno y los requerimientos.' }, { t: 'Diseño', d: 'Desarrollamos la ingeniería y el presupuesto.' }, { t: 'Ejecución', d: 'Construimos con control de calidad permanente.' }, { t: 'Entrega', d: 'Obra terminada, segura y a tiempo.' }],
    testiTitle: 'Clientes que confían en nuestra ingeniería',
    testimonials: [{ q: 'Ejecutaron nuestra obra en plazo y sin sobrecostos. Muy profesionales.', n: 'Inversiones del Sur', r: 'Proyecto comercial' }, { q: 'El nivel técnico y la seguridad en obra fueron impecables.', n: 'Municipalidad local', r: 'Obra de infraestructura' }, { q: 'Resolvieron un problema estructural complejo con total solvencia.', n: 'Condominio Las Lomas', r: 'Reforzamiento' }],
    contactTitle: 'Solicita tu cotización', contactSub: 'Cuéntanos sobre tu proyecto y te preparamos una propuesta técnica.',
    phone: '+51 1 622 4040', address: 'Av. Javier Prado Oeste 1450, San Isidro, Lima', hours: 'Lun–Vie · 8:00 – 18:00', contactCta: 'Solicitar cotización', email: 'proyectos@estructuraing.pe',
    footerAbout: 'Empresa de ingeniería con 20 años ejecutando obras civiles y estructurales en todo el Perú.',
    whatsappHref: 'https://wa.me/5116224040',
    pexels: { hero: 'civil engineering construction site', gallery: ['construction site crane', 'engineering blueprint', 'building construction', 'infrastructure bridge', 'engineers hard hat', 'structural steel'] },
  },

  /* Marketing / publicidad */
  {
    slug: 'marketing', category: CAT, label: 'Agencia de marketing', brand: 'Pulso Marketing',
    fonts: { heading: 'Sora', body: 'Inter' },
    palette: { primary: '#7C3AED', secondary: '#1E1A3A', accent: '#F0A93C', bg: '#FAF8FF', text: '#1F1B2E' },
    plan: ['nav', 'heroSplit', 'stats', 'servicesGrid', 'cards', 'process', 'testimonials', 'ctaBanner', 'contact', 'footer'],
    nav: ['Inicio', 'Servicios', 'Casos', 'Contacto'], navCta: 'Cotiza tu proyecto',
    eyebrow: 'Marketing digital · Lima', h1: 'Hacemos que tu marca despegue', sub: 'Estrategia, redes, publicidad y contenido que convierte seguidores en clientes. Resultados que se miden.',
    cta1: 'Cotiza tu proyecto', cta2: 'Ver casos', heroPills: ['Estrategia incluida', 'Reportes mensuales'],
    stats: [{ n: '+250%', l: 'ROAS promedio' }, { n: '180+', l: 'marcas potenciadas' }, { n: '9 años', l: 'de experiencia' }, { n: '4.9★', l: 'clientes felices' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Todo lo que tu marca necesita',
    services: [{ t: 'Redes sociales', d: 'Gestión, contenido y community management.' }, { t: 'Publicidad pagada', d: 'Meta Ads y Google Ads con foco en ventas.' }, { t: 'Branding', d: 'Identidad visual que conecta con tu público.' }, { t: 'Diseño y contenido', d: 'Piezas, video y fotografía de producto.' }, { t: 'Páginas web', d: 'Sitios y landing pages que convierten.' }, { t: 'Email marketing', d: 'Automatizaciones que fidelizan.' }],
    cardsEyebrow: 'Casos de éxito', cardsTitle: 'Resultados que hablan', cardsCta: 'Ver caso',
    cards: [{ tag: 'E-commerce', t: 'Tienda de moda', d: 'x3 en ventas online en 4 meses con Meta Ads', p: '+210%' }, { tag: 'Servicios', t: 'Clínica dental', d: 'Llenamos su agenda con campañas de captación', p: '+150 leads/mes' }, { tag: 'Retail', t: 'Cadena de comida', d: 'Comunidad de 0 a 80k seguidores reales', p: '80k+' }],
    processTitle: 'Cómo trabajamos',
    process: [{ t: 'Diagnóstico', d: 'Analizamos tu marca y competencia.' }, { t: 'Estrategia', d: 'Diseñamos el plan a tu objetivo.' }, { t: 'Ejecución', d: 'Creamos, publicamos y pauteamos.' }, { t: 'Optimización', d: 'Medimos y mejoramos cada mes.' }],
    testiTitle: 'Marcas que crecen con nosotros',
    testimonials: [{ q: 'Triplicamos las ventas de la tienda online en pocos meses. Crack total.', n: 'Carolina Ruiz', r: 'Dueña, Moda CR' }, { q: 'Por fin una agencia que muestra resultados con números. Recomendados.', n: 'Felipe Arana', r: 'Gerente, FoodCo' }, { q: 'Nuestra marca se ve profesional y vende. Gracias Pulso.', n: 'Ximena Polo', r: 'Fundadora, BellaSkin' }],
    ctaTitle: '¿Hacemos crecer tu marca?', ctaSub: 'Escríbenos por WhatsApp y cotiza tu proyecto sin compromiso.',
    contactTitle: 'Cotiza tu proyecto', contactSub: 'Cuéntanos tu objetivo y armamos tu estrategia.',
    phone: '+51 951 330 880', address: 'Av. Santa Cruz 1020, Miraflores, Lima', hours: 'Lun–Vie · 9:00 – 19:00', contactCta: 'Cotizar ahora', email: 'hola@pulsomarketing.pe',
    footerAbout: 'Agencia de marketing digital en Lima. Estrategia, redes y publicidad con resultados medibles.',
    whatsappHref: 'https://wa.me/51951330880',
    pexels: { hero: 'marketing team creative office', cards: ['fashion ecommerce', 'dental marketing', 'social media food'] },
  },

  /* Recursos Humanos / selección */
  {
    slug: 'rrhh', category: CAT, label: 'Recursos Humanos / Selección', brand: 'Talento Perú',
    fonts: { heading: 'Sora', body: 'Inter' },
    palette: { primary: '#2E8C8C', secondary: '#14333A', accent: '#E0A93C', bg: '#F5FAFA', text: '#1A2A2C' },
    plan: ['nav', 'heroSplit', 'stats', 'servicesGrid', 'process', 'testimonials', 'contact', 'footer'],
    nav: ['Inicio', 'Servicios', 'Proceso', 'Contacto'], navCta: 'Solicita talento',
    eyebrow: 'Recursos Humanos · Lima', h1: 'Encontramos al talento que tu empresa necesita', sub: 'Selección de personal, headhunting y gestión humana para que armes el mejor equipo, más rápido.',
    cta1: 'Solicita talento', cta2: 'Ver servicios', heroPills: ['Garantía de reemplazo', 'Procesos ágiles'],
    stats: [{ n: '5,000+', l: 'contrataciones' }, { n: '300+', l: 'empresas cliente' }, { n: '15 días', l: 'tiempo promedio' }, { n: '4.8★', l: 'satisfacción' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Gestión del talento integral',
    services: [{ t: 'Reclutamiento y selección', d: 'Encontramos al candidato ideal para tu puesto.' }, { t: 'Headhunting', d: 'Búsqueda especializada de perfiles ejecutivos.' }, { t: 'Evaluación psicolaboral', d: 'Pruebas y entrevistas por competencias.' }, { t: 'Outsourcing de planillas', d: 'Gestionamos tu nómina y obligaciones.' }, { t: 'Clima y cultura', d: 'Medimos y mejoramos el ambiente laboral.' }, { t: 'Capacitación', d: 'Programas de formación para tu equipo.' }],
    processTitle: 'Nuestro proceso de selección',
    process: [{ t: 'Perfil', d: 'Definimos contigo el candidato ideal.' }, { t: 'Búsqueda', d: 'Atraemos y filtramos a los mejores.' }, { t: 'Evaluación', d: 'Entrevistas y pruebas por competencias.' }, { t: 'Presentación', d: 'Te entregamos una terna lista para decidir.' }],
    testiTitle: 'Empresas que confían su talento',
    testimonials: [{ q: 'Nos consiguieron un gerente excelente en tiempo récord. Muy profesionales.', n: 'Grupo Comercial LM', r: 'Cliente corporativo' }, { q: 'La calidad de los candidatos fue muy superior a otras agencias.', n: 'Industrias del Norte', r: 'Cliente' }, { q: 'Gestionan nuestras planillas sin un solo error. Tranquilidad total.', n: 'Retail Express', r: 'Cliente' }],
    contactTitle: 'Solicita el talento que necesitas', contactSub: 'Cuéntanos qué perfil buscas y nos encargamos del resto.',
    phone: '+51 1 480 7070', address: 'Av. República de Panamá 3500, San Isidro, Lima', hours: 'Lun–Vie · 9:00 – 18:00', contactCta: 'Solicitar talento', email: 'contacto@talentoperu.pe',
    footerAbout: 'Consultora de RR.HH. en Lima. Selección de personal y headhunting para armar tu mejor equipo.',
    whatsappHref: 'https://wa.me/5114807070',
    pexels: { hero: 'job interview recruitment office', about: 'human resources team meeting' },
  },

  /* Coaching */
  {
    slug: 'coaching', category: CAT, label: 'Coaching / Desarrollo', brand: 'Impulso Coaching',
    fonts: { heading: 'Fraunces', body: 'Inter' },
    palette: { primary: '#E08A2C', secondary: '#2A2218', accent: '#5BB98C', bg: '#FBF8F2', text: '#2A2418' },
    plan: ['nav', 'heroSplit', 'stats', 'servicesGrid', 'featureSplit', 'testimonials', 'ctaBanner', 'contact', 'footer'],
    nav: ['Inicio', 'Servicios', 'Nosotros', 'Contacto'], navCta: 'Empieza hoy',
    eyebrow: 'Coaching & Desarrollo', h1: 'Desbloquea tu mejor versión', sub: 'Coaching personal y profesional para que alcances las metas que hoy parecen lejanas. Tú puedes, nosotros te guiamos.',
    cta1: 'Agenda tu sesión', cta2: 'Conoce más', heroPills: ['Primera sesión gratis', 'Online o presencial'],
    stats: [{ n: '2,000+', l: 'personas impulsadas' }, { n: '10 años', l: 'transformando vidas' }, { n: '95%', l: 'logra sus metas' }, { n: '4.9★', l: 'valoración' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Programas para cada meta',
    services: [{ t: 'Coaching de vida', d: 'Claridad, propósito y equilibrio personal.' }, { t: 'Coaching ejecutivo', d: 'Liderazgo y desarrollo profesional.' }, { t: 'Coaching de equipos', d: 'Alinea y potencia a tu equipo de trabajo.' }, { t: 'Oratoria y comunicación', d: 'Habla en público con seguridad y poder.' }],
    aboutTitle: 'Creemos en tu potencial', aboutBody: 'Todos tenemos un techo que en realidad es una puerta. Con herramientas probadas y acompañamiento cercano, te ayudamos a romper creencias limitantes y avanzar hacia la vida y la carrera que quieres.',
    aboutBullets: ['Coaches certificados internacionalmente', 'Metodología práctica y medible', 'Acompañamiento real entre sesiones'],
    testiTitle: 'Historias de transformación',
    testimonials: [{ q: 'Cambió mi forma de liderar y mi equipo lo notó al instante. Increíble.', n: 'Renzo Falcón', r: 'Gerente comercial' }, { q: 'Por fin me animé a emprender. El coaching me dio la seguridad que faltaba.', n: 'Sandra Lévano', r: 'Emprendedora' }, { q: 'Aprendí a hablar en público sin miedo. Me cambió profesionalmente.', n: 'Julio Ramos', r: 'Cliente' }],
    ctaTitle: '¿Empezamos tu transformación?', ctaSub: 'Tu primera sesión es gratis. Escríbenos por WhatsApp.',
    contactTitle: 'Agenda tu primera sesión', contactSub: 'Da el primer paso hacia tu mejor versión hoy.',
    phone: '+51 949 880 110', address: 'Av. Pardo y Aliaga 640, San Isidro, Lima', hours: 'Lun–Sáb · 8:00 – 20:00', contactCta: 'Agendar sesión', email: 'hola@impulsocoaching.pe',
    footerAbout: 'Coaching personal y profesional en Lima. Te acompañamos a alcanzar las metas que te propongas.',
    whatsappHref: 'https://wa.me/51949880110',
    pexels: { hero: 'coaching mentor motivational session', about: 'life coach conversation success' },
  },
];
