/* COMERCIO / RETAIL — 6 rubros. */
const CAT = 'Comercio / Retail';

module.exports = [
  /* Boutique de ropa */
  {
    slug: 'boutique', category: CAT, label: 'Boutique de ropa', brand: 'Atelier Moda',
    fonts: { heading: 'Cormorant Garamond', body: 'Jost' },
    palette: { primary: '#B08D57', secondary: '#2A241E', accent: '#C8A876', bg: '#FAF7F2', text: '#2A241E' },
    plan: ['nav', 'heroMinimal', 'stats', 'cards', 'featureSplit', 'testimonials', 'ctaBanner', 'contact', 'footer'],
    nav: ['Inicio', 'Colección', 'Nosotros', 'Contacto'], navCta: 'Ver colección',
    eyebrow: 'Boutique · Lima', h1: 'Viste tu mejor versión', sub: 'Moda femenina con identidad. Prendas seleccionadas que combinan tendencia, calidad y un estilo que es solo tuyo.',
    cta1: 'Ver colección', cta2: 'Pide por WhatsApp',
    stats: [{ n: 'Nueva', l: 'colección cada mes' }, { n: '5,000+', l: 'clientas con estilo' }, { n: 'Envíos', l: 'a todo el Perú' }, { n: '4.9★', l: 'valoración' }],
    cardsEyebrow: 'Colección', cardsTitle: 'Lo nuevo de temporada', cardsCta: 'Consultar',
    cards: [{ tag: 'Nuevo', t: 'Vestido Primavera', d: 'Fluido, ideal para toda ocasión', p: 'S/ 159' }, { tag: 'Tendencia', t: 'Blazer Estructurado', d: 'Elegancia para el día a día', p: 'S/ 219' }, { t: 'Blusa de seda', d: 'Suave y versátil', p: 'S/ 129' }, { t: 'Pantalón sastre', d: 'Corte perfecto, alta cintura', p: 'S/ 169' }, { tag: 'Top', t: 'Conjunto tejido', d: 'Comodidad con estilo', p: 'S/ 189' }, { t: 'Accesorios', d: 'Carteras y complementos', p: 'Desde S/ 59' }],
    aboutTitle: 'Moda con propósito y carácter', aboutBody: 'Seleccionamos cada prenda pensando en ti: en cómo te sientes, en cómo te ves y en que dure. Trabajamos con telas de calidad y diseños que no pasan de moda, porque tu estilo merece prendas que lo acompañen.',
    aboutBullets: ['Prendas seleccionadas de calidad', 'Asesoría de estilo personalizada', 'Envíos a todo el país'],
    testiTitle: 'Lo que dicen nuestras clientas',
    testimonials: [{ q: 'La calidad de la ropa es increíble y siempre recibo cumplidos. Encantada.', n: 'Daniela Pareja', r: 'Cliente' }, { q: 'Me asesoraron para armar mi clóset cápsula. Atención de lujo.', n: 'Rocío Mendoza', r: 'Cliente frecuente' }, { q: 'Envíos rápidos y prendas hermosas. Mi boutique favorita.', n: 'Andrea Solís', r: 'Cliente' }],
    ctaTitle: '¿Lista para renovar tu clóset?', ctaSub: 'Escríbenos por WhatsApp y te asesoramos con la nueva colección.',
    contactTitle: 'Visítanos o compra online', contactSub: 'Te esperamos en tienda o te enviamos a todo el Perú.',
    phone: '+51 956 110 220', address: 'Av. Conquistadores 380, San Isidro, Lima', hours: 'Lun–Sáb · 11:00 – 20:00', contactCta: 'Escríbenos', email: 'hola@ateliermoda.pe',
    footerAbout: 'Boutique de moda femenina en San Isidro. Prendas seleccionadas con estilo, calidad y carácter.',
    whatsappHref: 'https://wa.me/51956110220',
    pexels: { hero: 'fashion boutique clothing store', about: 'woman fashion shopping elegant', cards: ['dress fashion woman', 'blazer fashion', 'silk blouse', 'tailored pants fashion', 'knitwear outfit', 'handbag accessories'] },
  },

  /* Joyería */
  {
    slug: 'joyeria', category: CAT, label: 'Joyería', brand: 'Aurum Joyería',
    fonts: { heading: 'Cormorant Garamond', body: 'Jost' },
    palette: { primary: '#1A1A1A', secondary: '#14110E', accent: '#C0A062', bg: '#F7F5F0', text: '#1F1B16' },
    plan: ['nav', 'heroMinimal', 'stats', 'cards', 'featureSplit', 'testimonials', 'contact', 'footer'],
    nav: ['Inicio', 'Colección', 'Nosotros', 'Contacto'], navCta: 'Ver colección',
    eyebrow: 'Joyería · Lima', h1: 'Piezas que cuentan historias', sub: 'Joyas en oro y plata, diseños exclusivos y personalizados. El detalle perfecto para los momentos que importan.',
    cta1: 'Ver colección', cta2: 'Diseño a medida',
    stats: [{ n: '25 años', l: 'de tradición' }, { n: 'Oro y plata', l: 'certificados' }, { n: 'A medida', l: 'diseños únicos' }, { n: '4.9★', l: 'clientes' }],
    cardsEyebrow: 'Colección', cardsTitle: 'Joyas que perduran', cardsCta: 'Consultar',
    cards: [{ tag: 'Destacado', t: 'Anillos de compromiso', d: 'Oro 18k con diamantes certificados', p: 'Desde S/ 1,200' }, { t: 'Aretes de oro', d: 'Diseños clásicos y modernos', p: 'Desde S/ 390' }, { t: 'Cadenas y dijes', d: 'Oro y plata para cada estilo', p: 'Desde S/ 250' }, { t: 'Pulseras', d: 'Elegancia para tu muñeca', p: 'Desde S/ 320' }, { tag: 'A medida', t: 'Diseño personalizado', d: 'Creamos la joya que imaginas', p: 'Cotización' }, { t: 'Alianzas de boda', d: 'El símbolo de su unión', p: 'Desde S/ 680' }],
    aboutTitle: 'Maestría artesanal en cada detalle', aboutBody: 'Desde hace 25 años creamos joyas que se convierten en herencia. Cada pieza es trabajada a mano por nuestros maestros joyeros, con materiales certificados y el cuidado que un momento especial merece.',
    aboutBullets: ['Oro y plata con certificado de garantía', 'Diseños exclusivos y personalizados', 'Servicio de mantenimiento y reparación'],
    testiTitle: 'Momentos que hicimos brillar',
    testimonials: [{ q: 'El anillo de compromiso quedó perfecto. Dijo que sí. Gracias por tanto.', n: 'Sebastián Lara', r: 'Cliente' }, { q: 'Diseñaron una joya con la inicial de mi hija. Una hermosura única.', n: 'Claudia Reyes', r: 'Cliente' }, { q: 'Calidad y atención impecables. Compro aquí desde hace años.', n: 'Mónica Tello', r: 'Cliente frecuente' }],
    contactTitle: 'Visítanos', contactSub: 'Descubre la joya perfecta o diseña la tuya con nosotros.',
    phone: '+51 1 444 2020', address: 'C.C. Centro, Local 120, Miraflores, Lima', hours: 'Lun–Sáb · 11:00 – 20:00', contactCta: 'Escríbenos', email: 'contacto@aurumjoyeria.pe',
    footerAbout: 'Joyería con 25 años de tradición en Lima. Oro, plata y diseños a medida hechos a mano.',
    whatsappHref: 'https://wa.me/5114442020',
    pexels: { hero: 'jewelry gold luxury elegant', about: 'jeweler crafting jewelry hands', cards: ['diamond ring engagement', 'gold earrings', 'gold necklace pendant', 'gold bracelet', 'jewelry design custom', 'wedding rings gold'] },
  },

  /* Tienda de tecnología */
  {
    slug: 'tecnologia', category: CAT, label: 'Tienda de tecnología', brand: 'TecnoZone',
    fonts: { heading: 'Sora', body: 'Inter' },
    palette: { primary: '#2563EB', secondary: '#0E1A33', accent: '#22D3EE', bg: '#F5F8FD', text: '#16202E' },
    plan: ['nav', 'heroSplit', 'stats', 'cards', 'servicesGrid', 'testimonials', 'ctaBanner', 'contact', 'footer'],
    nav: ['Inicio', 'Productos', 'Servicios', 'Contacto'], navCta: 'Comprar ahora',
    eyebrow: 'Tecnología · Lima', h1: 'La tecnología que necesitas, al mejor precio', sub: 'Laptops, celulares, accesorios y gaming. Productos originales con garantía y delivery a todo el Perú.',
    cta1: 'Ver productos', cta2: 'Pide por WhatsApp', heroPills: ['Productos originales', 'Garantía oficial'],
    stats: [{ n: '100%', l: 'productos originales' }, { n: '10,000+', l: 'clientes felices' }, { n: '24-48h', l: 'delivery' }, { n: '4.8★', l: 'valoración' }],
    cardsEyebrow: 'Productos', cardsTitle: 'Lo más vendido', cardsCta: 'Comprar',
    cards: [{ tag: 'Oferta', t: 'Laptops', d: 'Para trabajo, estudio y gaming', p: 'Desde S/ 1,499' }, { tag: 'Nuevo', t: 'Smartphones', d: 'Las últimas marcas y modelos', p: 'Desde S/ 699' }, { t: 'Audífonos', d: 'Inalámbricos y con cancelación de ruido', p: 'Desde S/ 99' }, { tag: 'Gaming', t: 'Consolas y accesorios', d: 'Todo para el gamer', p: 'Desde S/ 199' }, { t: 'Smartwatches', d: 'Salud y notificaciones en tu muñeca', p: 'Desde S/ 149' }, { t: 'Accesorios', d: 'Cargadores, fundas y más', p: 'Desde S/ 29' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Compra con confianza',
    services: [{ t: 'Garantía oficial', d: 'Todos los productos con garantía de fábrica.' }, { t: 'Delivery nacional', d: 'Te llevamos tu pedido a todo el Perú.' }, { t: 'Soporte técnico', d: 'Te asesoramos antes y después de tu compra.' }],
    ctaTitle: '¿Buscas algo en especial?', ctaSub: 'Escríbenos por WhatsApp y cotiza al instante con stock real.',
    contactTitle: 'Haz tu pedido', contactSub: 'Consulta stock y precios. Te respondemos al toque.',
    phone: '+51 940 220 110', address: 'C.C. Tecnológico, Stand 45, Cercado, Lima', hours: 'Lun–Sáb · 10:00 – 20:00', contactCta: 'Cotizar ahora', email: 'ventas@tecnozone.pe',
    footerAbout: 'Tienda de tecnología en Lima. Laptops, celulares y gaming originales con garantía y delivery nacional.',
    whatsappHref: 'https://wa.me/51940220110',
    pexels: { hero: 'technology store gadgets laptop', cards: ['laptop computer modern', 'smartphone new', 'wireless headphones', 'gaming console controller', 'smartwatch wrist', 'tech accessories cables'] },
  },

  /* Florería */
  {
    slug: 'floreria', category: CAT, label: 'Florería', brand: 'Flor & Detalle',
    fonts: { heading: 'Fraunces', body: 'Jost' },
    palette: { primary: '#C24E6E', secondary: '#2A1A22', accent: '#8CA86A', bg: '#FBF6F4', text: '#2A2024' },
    plan: ['nav', 'heroFullBg', 'stats', 'cards', 'gallery', 'testimonials', 'ctaBanner', 'contact', 'footer'],
    nav: ['Inicio', 'Productos', 'Galería', 'Contacto'], navCta: 'Pedir flores',
    eyebrow: 'Florería · Lima', h1: 'Flores que dicen lo que sientes', sub: 'Arreglos florales para cada ocasión, hechos con flores frescas y mucho cariño. Delivery el mismo día en Lima.',
    cta1: 'Pide tu arreglo', cta2: 'Ver galería',
    stats: [{ n: 'Mismo día', l: 'delivery en Lima' }, { n: '100%', l: 'flores frescas' }, { n: '12 años', l: 'creando detalles' }, { n: '4.9★', l: 'clientes' }],
    cardsEyebrow: 'Productos', cardsTitle: 'Para cada ocasión', cardsCta: 'Pedir',
    cards: [{ tag: 'Top', t: 'Ramo de rosas', d: 'Clásico y siempre perfecto', p: 'Desde S/ 89' }, { t: 'Box de flores', d: 'Elegante caja con flores de temporada', p: 'Desde S/ 119' }, { t: 'Arreglo de cumpleaños', d: 'Colorido y alegre', p: 'Desde S/ 99' }, { t: 'Flores + chocolates', d: 'El combo que enamora', p: 'Desde S/ 139' }, { tag: 'Eventos', t: 'Decoración floral', d: 'Bodas, eventos y locales', p: 'Cotización' }, { t: 'Plantas de interior', d: 'Vida y color para tu espacio', p: 'Desde S/ 69' }],
    galleryEyebrow: 'Galería', galleryTitle: 'Detalles que enamoran',
    testiTitle: 'Lo que dicen nuestros clientes',
    testimonials: [{ q: 'El ramo llegó hermoso y a tiempo. Mi esposa quedó feliz. Gracias.', n: 'Martín Solano', r: 'Cliente' }, { q: 'Decoraron mi evento con un gusto increíble. Todo precioso.', n: 'Lucía Paredes', r: 'Cliente' }, { q: 'Flores fresquísimas y atención cálida. Mi florería de siempre.', n: 'Carmen Díaz', r: 'Cliente frecuente' }],
    ctaTitle: '¿Quieres sorprender a alguien?', ctaSub: 'Escríbenos por WhatsApp y enviamos tu detalle el mismo día.',
    contactTitle: 'Haz tu pedido', contactSub: 'Cuéntanos la ocasión y creamos el detalle perfecto.',
    phone: '+51 956 440 330', address: 'Av. Dos de Mayo 720, San Isidro, Lima', hours: 'Lun–Dom · 8:00 – 21:00', contactCta: 'Pedir ahora', email: 'pedidos@florydetalle.pe',
    footerAbout: 'Florería en San Isidro. Arreglos con flores frescas y delivery el mismo día en Lima.',
    whatsappHref: 'https://wa.me/51956440330',
    pexels: { hero: 'flower shop bouquet roses', cards: ['rose bouquet red', 'flower box arrangement', 'birthday flowers colorful', 'flowers chocolates gift', 'wedding floral decoration', 'indoor plants pots'], gallery: ['flower bouquet beautiful', 'florist arrangement', 'roses close up', 'flower shop interior', 'wedding flowers', 'colorful flowers'] },
  },

  /* Mueblería */
  {
    slug: 'muebles', category: CAT, label: 'Mueblería', brand: 'Casa & Madera',
    fonts: { heading: 'Sora', body: 'Inter' },
    palette: { primary: '#8C6A45', secondary: '#2A2018', accent: '#C0A077', bg: '#FAF6F0', text: '#2A2118' },
    plan: ['nav', 'heroSplit', 'stats', 'cards', 'featureSplit', 'gallery', 'testimonials', 'contact', 'footer'],
    nav: ['Inicio', 'Productos', 'Nosotros', 'Galería', 'Contacto'], navCta: 'Ver catálogo',
    eyebrow: 'Mueblería · Lima', h1: 'Muebles que hacen un hogar', sub: 'Muebles de madera y diseño para cada ambiente. Calidad que dura, fabricados a medida o listos para llevar.',
    cta1: 'Ver catálogo', cta2: 'Diseño a medida', heroPills: ['Fabricación a medida', 'Envío e instalación'],
    stats: [{ n: '20 años', l: 'fabricando' }, { n: 'A medida', l: 'o estándar' }, { n: 'Madera', l: 'de primera' }, { n: '4.8★', l: 'clientes' }],
    cardsEyebrow: 'Productos', cardsTitle: 'Para cada ambiente', cardsCta: 'Cotizar',
    cards: [{ tag: 'Sala', t: 'Juegos de sala', d: 'Sofás y muebles para tu living', p: 'Desde S/ 1,290' }, { tag: 'Comedor', t: 'Comedores', d: 'Mesas y sillas de madera sólida', p: 'Desde S/ 1,490' }, { t: 'Dormitorio', d: 'Camas, cómodas y veladores', p: 'Desde S/ 990' }, { t: 'Closets y roperos', d: 'A medida para tu espacio', p: 'Cotización' }, { t: 'Muebles de cocina', d: 'Reposteros funcionales y modernos', p: 'Cotización' }, { t: 'Muebles de oficina', d: 'Escritorios y estanterías', p: 'Desde S/ 690' }],
    aboutTitle: 'Hechos para durar generaciones', aboutBody: 'Trabajamos la madera con el oficio de siempre y el diseño de hoy. Cada mueble se fabrica con materiales nobles y acabados cuidados, para que acompañe tu hogar por muchos años.',
    aboutBullets: ['Madera de primera calidad', 'Fabricación a medida', 'Envío e instalación incluidos'],
    galleryEyebrow: 'Galería', galleryTitle: 'Ambientes que inspiran',
    testiTitle: 'Hogares que amueblamos',
    testimonials: [{ q: 'Mi comedor quedó espectacular y la calidad de la madera se nota. Excelentes.', n: 'Rafael Uribe', r: 'Cliente' }, { q: 'Hicieron mi closet a medida perfecto. Aprovecharon cada centímetro.', n: 'Patricia Salas', r: 'Cliente' }, { q: 'Muebles bonitos, resistentes y a buen precio. Muy recomendados.', n: 'Jorge Medina', r: 'Cliente' }],
    contactTitle: 'Cotiza tus muebles', contactSub: 'Cuéntanos qué necesitas y te asesoramos sin compromiso.',
    phone: '+51 945 550 110', address: 'Av. Nicolás Ayllón 2400, Ate, Lima', hours: 'Lun–Sáb · 9:00 – 19:00', contactCta: 'Solicitar cotización', email: 'ventas@casaymadera.pe',
    footerAbout: 'Mueblería en Lima con 20 años fabricando muebles de madera a medida, hechos para durar.',
    whatsappHref: 'https://wa.me/51945550110',
    pexels: { hero: 'furniture store living room wood', about: 'carpenter wood furniture workshop', cards: ['sofa living room', 'wooden dining table', 'bedroom furniture bed', 'wardrobe closet', 'kitchen cabinets', 'office desk wood'], gallery: ['living room furniture', 'dining room set', 'bedroom design', 'modern furniture', 'wooden furniture detail', 'home interior cozy'] },
  },

  /* Petshop / mascotas */
  {
    slug: 'petshop', category: CAT, label: 'Petshop / Mascotas', brand: 'Mundo Mascota',
    fonts: { heading: 'Poppins', body: 'Inter' },
    palette: { primary: '#F08A3C', secondary: '#2A2418', accent: '#5BB98C', bg: '#FBF7F0', text: '#2A2218' },
    plan: ['nav', 'heroFullBg', 'stats', 'cards', 'servicesGrid', 'gallery', 'testimonials', 'contact', 'footer'],
    nav: ['Inicio', 'Productos', 'Servicios', 'Galería', 'Contacto'], navCta: 'Pedir por WhatsApp',
    eyebrow: 'Petshop · Lima', h1: 'Todo lo que tu mascota necesita', sub: 'Alimento, accesorios, juguetes y baño. Productos de calidad para consentir a tu engreído, con delivery a casa.',
    cta1: 'Ver productos', cta2: 'Pide por WhatsApp',
    stats: [{ n: '5,000+', l: 'mascotas felices' }, { n: 'Premium', l: 'marcas de alimento' }, { n: 'Delivery', l: 'a domicilio' }, { n: '4.9★', l: 'clientes' }],
    cardsEyebrow: 'Productos', cardsTitle: 'Para tu engreído', cardsCta: 'Pedir',
    cards: [{ tag: 'Top', t: 'Alimento premium', d: 'Para perros y gatos, todas las etapas', p: 'Desde S/ 49' }, { t: 'Juguetes', d: 'Diversión y entretenimiento', p: 'Desde S/ 15' }, { t: 'Camas y casas', d: 'Para que descanse cómodo', p: 'Desde S/ 79' }, { t: 'Accesorios', d: 'Correas, platos y transportadoras', p: 'Desde S/ 25' }, { t: 'Higiene', d: 'Shampoo, pañales y cuidado', p: 'Desde S/ 19' }, { t: 'Snacks y premios', d: 'Para consentirlo y entrenarlo', p: 'Desde S/ 12' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Más que una tienda',
    services: [{ t: 'Baño y peluquería', d: 'Spa para que luzca y huela increíble.' }, { t: 'Delivery a casa', d: 'Te llevamos su comida y accesorios.' }, { t: 'Asesoría', d: 'Te ayudamos a elegir lo mejor para él.' }],
    galleryEyebrow: 'Galería', galleryTitle: 'Nuestros clientes consentidos',
    testiTitle: 'Lo que dicen los dueños',
    testimonials: [{ q: 'Siempre tienen el alimento de mi perro y el delivery es rapidísimo.', n: 'Andrea Loja', r: 'Cliente' }, { q: 'El baño dejó a mi gata hermosa. Atención con mucho cariño.', n: 'Renzo Paz', r: 'Cliente' }, { q: 'Buenos precios y gran variedad. Mi petshop de confianza.', n: 'Sofía Marina', r: 'Cliente frecuente' }],
    contactTitle: 'Haz tu pedido', contactSub: 'Consulta productos y te llevamos todo a casa.',
    phone: '+51 945 330 880', address: 'Av. Aviación 2680, San Borja, Lima', hours: 'Lun–Dom · 9:00 – 21:00', contactCta: 'Pedir ahora', email: 'ventas@mundomascota.pe',
    footerAbout: 'Petshop en San Borja. Alimento, accesorios y baño para consentir a tu mascota, con delivery a casa.',
    whatsappHref: 'https://wa.me/51945330880',
    pexels: { hero: 'pet shop dog cat supplies', cards: ['dog food bag', 'pet toys colorful', 'dog bed cozy', 'pet accessories leash', 'pet grooming shampoo', 'dog treats snacks'], gallery: ['happy dog pet', 'cat cute pet', 'dog grooming bath', 'puppy playing', 'pet store interior', 'cat playing toy'] },
  },
];
