/* SALUD Y BIENESTAR — 9 rubros, cada uno con identidad propia. */
const CAT = 'Salud y bienestar';

module.exports = [
  /* Clínica / consultorio médico */
  {
    slug: 'salud', category: CAT, label: 'Clínica / Consultorio médico', brand: 'Clínica Vida Plena',
    fonts: { heading: 'Poppins', body: 'Inter' },
    palette: { primary: '#0E7C86', secondary: '#0B3B40', accent: '#5FC9C0', bg: '#F4FBFB', text: '#16302F' },
    plan: ['nav', 'heroSplit', 'stats', 'servicesGrid', 'team', 'testimonials', 'faq', 'contact', 'footer'],
    nav: ['Inicio', 'Especialidades', 'Equipo', 'Contacto'], navCta: 'Reservar cita',
    eyebrow: 'Salud · Lima', h1: 'Tu salud en manos que confías', sub: 'Atención médica integral con tecnología moderna y un trato humano que marca la diferencia.',
    cta1: 'Reserva tu cita', cta2: 'Especialidades', heroPills: ['Atención el mismo día', 'Convenios con seguros'],
    stats: [{ n: '25+', l: 'años de servicio' }, { n: '40,000+', l: 'pacientes atendidos' }, { n: '15', l: 'especialidades' }, { n: '4.9★', l: 'satisfacción' }],
    servicesEyebrow: 'Especialidades', servicesTitle: 'Atención que cubre a toda tu familia', servicesSub: 'Diagnóstico oportuno y tratamiento con calidez humana.',
    services: [
      { t: 'Medicina General', d: 'Chequeos, diagnóstico y seguimiento de tu salud integral.' },
      { t: 'Pediatría', d: 'Cuidamos el crecimiento sano de tus hijos en cada etapa.' },
      { t: 'Cardiología', d: 'Evaluación y prevención de enfermedades del corazón.' },
      { t: 'Ginecología', d: 'Salud femenina con privacidad, confianza y profesionalismo.' },
      { t: 'Laboratorio', d: 'Análisis clínicos con resultados rápidos y confiables.' },
      { t: 'Imágenes', d: 'Ecografías y diagnóstico por imágenes de alta precisión.' },
    ],
    teamTitle: 'Médicos en quienes confiar',
    team: [{ n: 'Dra. Elena Paredes', r: 'Medicina Interna' }, { n: 'Dr. Hugo Ramírez', r: 'Cardiología' }, { n: 'Dra. Carmen Ruiz', r: 'Pediatría' }, { n: 'Dr. Luis Acosta', r: 'Ginecología' }],
    testiTitle: 'La confianza de nuestros pacientes',
    testimonials: [
      { q: 'Me atendieron el mismo día y con muchísima amabilidad. Excelente clínica.', n: 'Rosa Quispe', r: 'Paciente' },
      { q: 'Los doctores explican todo con paciencia. Mi familia entera se atiende aquí.', n: 'Manuel Díaz', r: 'Paciente frecuente' },
      { q: 'Instalaciones modernas y limpias. Me sentí en buenas manos.', n: 'Ana Flores', r: 'Paciente' },
    ],
    faqTitle: 'Preguntas frecuentes',
    faq: [{ q: '¿Atienden con seguro?', a: 'Sí, trabajamos con los principales seguros y EPS del país.' }, { q: '¿Necesito cita previa?', a: 'Recomendamos reservar, pero también atendemos urgencias el mismo día.' }, { q: '¿Tienen laboratorio propio?', a: 'Sí, contamos con laboratorio e imágenes en la misma sede.' }],
    contactTitle: 'Reserva tu cita', contactSub: 'Escríbenos y coordinamos tu atención lo antes posible.',
    phone: '+51 1 610 2020', address: 'Av. Arequipa 3450, San Isidro, Lima', hours: 'Lun–Sáb · 7:00 – 20:00', contactCta: 'Reservar cita', email: 'citas@vidaplena.pe',
    footerAbout: 'Clínica con 25 años cuidando la salud de las familias limeñas con calidez y tecnología.',
    whatsappHref: 'https://wa.me/5116102020',
    pexels: { hero: 'doctor patient consultation clinic', team: ['doctor portrait white coat', 'female doctor portrait', 'pediatrician doctor portrait', 'medical professional portrait'] },
  },

  /* Odontología / dental */
  {
    slug: 'dental', category: CAT, label: 'Clínica dental', brand: 'Sonrisa Studio',
    fonts: { heading: 'Poppins', body: 'Inter' },
    palette: { primary: '#2BA8E0', secondary: '#14384D', accent: '#58D0C9', bg: '#F5FBFE', text: '#1B2A33' },
    plan: ['nav', 'heroSplit', 'stats', 'servicesGrid', 'gallery', 'team', 'testimonials', 'faq', 'contact', 'footer'],
    nav: ['Inicio', 'Tratamientos', 'Galería', 'Equipo', 'Contacto'], navCta: 'Agenda tu cita',
    eyebrow: 'Odontología · Lima', h1: 'La sonrisa que siempre quisiste', sub: 'Odontología moderna, sin dolor y con resultados que se ven. Te acompañamos en cada paso.',
    cta1: 'Agenda tu evaluación', cta2: 'Ver tratamientos', heroPills: ['Primera evaluación gratis', 'Financiamiento disponible'],
    stats: [{ n: '12 años', l: 'transformando sonrisas' }, { n: '8,000+', l: 'pacientes felices' }, { n: '0', l: 'dolor garantizado' }, { n: '4.9★', l: 'en Google' }],
    servicesEyebrow: 'Tratamientos', servicesTitle: 'Todo para tu salud bucal',
    services: [
      { t: 'Ortodoncia', d: 'Brackets y alineadores invisibles para una sonrisa perfecta.' },
      { t: 'Implantes', d: 'Recupera tus dientes con implantes de la más alta calidad.' },
      { t: 'Blanqueamiento', d: 'Una sonrisa más blanca y brillante en una sola sesión.' },
      { t: 'Diseño de sonrisa', d: 'Carillas y estética dental personalizada para ti.' },
      { t: 'Odontopediatría', d: 'Cuidamos la sonrisa de los más pequeños sin miedo.' },
      { t: 'Limpieza dental', d: 'Profilaxis profesional para una boca sana.' },
    ],
    galleryEyebrow: 'Resultados', galleryTitle: 'Sonrisas que hablan por sí solas',
    teamTitle: 'Especialistas que te cuidan',
    team: [{ n: 'Dr. Diego Salas', r: 'Ortodoncista' }, { n: 'Dra. Mónica Ávila', r: 'Implantología' }, { n: 'Dra. Karina Ponce', r: 'Estética dental' }, { n: 'Dr. Renato Gil', r: 'Odontopediatría' }],
    testiTitle: 'Lo que dicen nuestros pacientes',
    testimonials: [{ q: 'Me hice los brackets invisibles y nadie notó nada. Resultado increíble.', n: 'Valeria Soto', r: 'Paciente de ortodoncia' }, { q: 'Le tenía pánico al dentista y aquí me quitaron el miedo. 100% recomendados.', n: 'José Linares', r: 'Paciente' }, { q: 'Mi diseño de sonrisa cambió mi vida. Profesionales de primera.', n: 'Daniela Cruz', r: 'Paciente' }],
    faqTitle: 'Preguntas frecuentes',
    faq: [{ q: '¿La primera evaluación tiene costo?', a: 'No, la primera evaluación y diagnóstico son totalmente gratis.' }, { q: '¿Ofrecen facilidades de pago?', a: 'Sí, financiamos tu tratamiento en cuotas cómodas.' }, { q: '¿Atienden niños?', a: 'Claro, contamos con odontopediatría especializada.' }],
    contactTitle: 'Agenda tu evaluación gratuita', contactSub: 'Da el primer paso hacia tu mejor sonrisa.',
    phone: '+51 987 112 233', address: 'Av. Benavides 2040, Miraflores, Lima', hours: 'Lun–Sáb · 9:00 – 19:00', contactCta: 'Agendar cita', email: 'hola@sonrisastudio.pe',
    footerAbout: 'Clínica dental moderna en Miraflores. Tu sonrisa es nuestra mejor carta de presentación.',
    whatsappHref: 'https://wa.me/51987112233',
    pexels: { hero: 'dental clinic smile dentist', gallery: ['dental smile teeth', 'dentist patient', 'dental clinic modern', 'happy smile woman', 'orthodontics braces', 'dental tools clean'], team: ['dentist portrait', 'female dentist portrait', 'dental professional woman', 'young dentist portrait'] },
  },

  /* Psicología / terapia */
  {
    slug: 'psicologia', category: CAT, label: 'Psicología / Terapia', brand: 'Espacio Sereno',
    fonts: { heading: 'Fraunces', body: 'Inter' },
    palette: { primary: '#7C6BB0', secondary: '#2E2A40', accent: '#E0A98F', bg: '#FAF7FB', text: '#2B2733' },
    plan: ['nav', 'heroSplit', 'stats', 'servicesGrid', 'featureSplit', 'testimonials', 'faq', 'contact', 'footer'],
    nav: ['Inicio', 'Servicios', 'Nosotros', 'Contacto'], navCta: 'Reservar sesión',
    eyebrow: 'Bienestar emocional', h1: 'Un espacio seguro para sentirte mejor', sub: 'Terapia psicológica con un enfoque cálido y profesional. Presencial o en línea, a tu ritmo.',
    cta1: 'Reserva tu sesión', cta2: 'Conoce más', heroPills: ['Primera sesión orientativa', 'Atención online'],
    stats: [{ n: '10 años', l: 'acompañando procesos' }, { n: '2,500+', l: 'personas atendidas' }, { n: '100%', l: 'confidencial' }, { n: 'Online', l: 'o presencial' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Acompañamiento para cada etapa',
    services: [{ t: 'Terapia individual', d: 'Ansiedad, depresión, autoestima y desarrollo personal.' }, { t: 'Terapia de pareja', d: 'Reconstruir la comunicación y el vínculo.' }, { t: 'Terapia familiar', d: 'Resolver conflictos y fortalecer los lazos.' }, { t: 'Psicología infantil', d: 'Apoyo emocional para niños y adolescentes.' }],
    aboutTitle: 'Tu bienestar, nuestra prioridad', aboutBody: 'Creemos que pedir ayuda es un acto de valentía. Por eso ofrecemos un espacio libre de juicios, donde puedas hablar con confianza y avanzar a tu propio ritmo, acompañado por profesionales que de verdad escuchan.',
    aboutBullets: ['Profesionales colegiados y con experiencia', 'Total confidencialidad', 'Sesiones presenciales y virtuales'],
    testiTitle: 'Historias de cambio',
    testimonials: [{ q: 'Encontré las herramientas para manejar mi ansiedad. Estoy muy agradecida.', n: 'Paciente anónima', r: 'Terapia individual' }, { q: 'Salvamos nuestra relación gracias al acompañamiento. Gracias de corazón.', n: 'Pareja atendida', r: 'Terapia de pareja' }, { q: 'Un trato humano y profesional. Me sentí escuchado desde el primer día.', n: 'Paciente', r: 'Terapia individual' }],
    faqTitle: 'Preguntas frecuentes',
    faq: [{ q: '¿Las sesiones son confidenciales?', a: 'Absolutamente. Todo lo conversado está protegido por el secreto profesional.' }, { q: '¿Atienden de forma virtual?', a: 'Sí, ofrecemos sesiones online con la misma calidad que las presenciales.' }, { q: '¿Cuánto dura una sesión?', a: 'Cada sesión dura aproximadamente 50 minutos.' }],
    contactTitle: 'Reserva tu sesión', contactSub: 'Da el primer paso. Estamos aquí para acompañarte.',
    phone: '+51 956 778 990', address: 'Av. Pardo 610, Miraflores, Lima', hours: 'Lun–Sáb · 8:00 – 21:00', contactCta: 'Reservar sesión', email: 'contacto@espaciosereno.pe',
    footerAbout: 'Centro de psicología en Lima. Un espacio seguro para tu bienestar emocional, presencial y online.',
    whatsappHref: 'https://wa.me/51956778990',
    pexels: { hero: 'therapy psychology calm session', about: 'psychologist talking patient' },
  },

  /* Veterinaria */
  {
    slug: 'veterinaria', category: CAT, label: 'Veterinaria', brand: 'Huellitas Vet',
    fonts: { heading: 'Poppins', body: 'Inter' },
    palette: { primary: '#F08A3C', secondary: '#2C3A2E', accent: '#5BB98C', bg: '#FBF7F0', text: '#2A2520' },
    plan: ['nav', 'heroFullBg', 'stats', 'servicesGrid', 'gallery', 'testimonials', 'ctaBanner', 'contact', 'footer'],
    nav: ['Inicio', 'Servicios', 'Galería', 'Contacto'], navCta: 'Reservar cita',
    eyebrow: 'Veterinaria · Lima', h1: 'Porque ellos también son familia', sub: 'Atención veterinaria con amor y profesionalismo. Cuidamos la salud de tu mascota como si fuera nuestra.',
    cta1: 'Reserva una cita', cta2: 'Nuestros servicios',
    stats: [{ n: '15 años', l: 'cuidando mascotas' }, { n: '20,000+', l: 'patitas atendidas' }, { n: '24/7', l: 'emergencias' }, { n: '4.9★', l: 'amor de clientes' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Todo para el bienestar de tu mascota',
    services: [{ t: 'Consulta general', d: 'Chequeos y diagnóstico para perros y gatos.' }, { t: 'Vacunación', d: 'Calendario completo de vacunas y desparasitación.' }, { t: 'Cirugía', d: 'Quirófano equipado y atención especializada.' }, { t: 'Peluquería canina', d: 'Baño, corte y spa para que luzca radiante.' }, { t: 'Emergencias 24h', d: 'Estamos cuando más nos necesitas.' }, { t: 'Tienda y alimento', d: 'Productos premium para su nutrición.' }],
    galleryEyebrow: 'Galería', galleryTitle: 'Nuestros pacientes consentidos',
    testiTitle: 'Familias que confían en nosotros',
    testimonials: [{ q: 'Salvaron a mi perrito en una emergencia de madrugada. Eternamente agradecida.', n: 'Lucía Mendoza', r: 'Dueña de Toby' }, { q: 'El trato con los animales es increíble. Mi gata ya no le teme al veterinario.', n: 'Carlos Pérez', r: 'Dueño de Michi' }, { q: 'Profesionales y con mucho amor. No los cambio por nada.', n: 'Andrea Ríos', r: 'Dueña de Luna' }],
    ctaTitle: '¿Tu mascota necesita atención?', ctaSub: 'Escríbenos por WhatsApp y reservamos su cita hoy mismo.',
    contactTitle: 'Visítanos o reserva', contactSub: 'Estamos listos para cuidar a tu mejor amigo.',
    phone: '+51 945 332 110', address: 'Av. Primavera 980, Surco, Lima', hours: 'Todos los días · 8:00 – 22:00', contactCta: 'Reservar cita', email: 'hola@huellitasvet.pe',
    footerAbout: 'Veterinaria en Surco con atención 24h. Cuidamos a tu mascota con el amor que merece.',
    whatsappHref: 'https://wa.me/51945332110',
    pexels: { hero: 'veterinarian dog cat clinic', gallery: ['happy dog vet', 'cat veterinary', 'puppy cute', 'dog grooming', 'veterinarian pet', 'kitten care'] },
  },

  /* Óptica */
  {
    slug: 'optica', category: CAT, label: 'Óptica', brand: 'Visión Clara',
    fonts: { heading: 'Sora', body: 'Inter' },
    palette: { primary: '#1E5BB0', secondary: '#16233B', accent: '#E0B23C', bg: '#F7F9FC', text: '#1A2230' },
    plan: ['nav', 'heroSplit', 'stats', 'cards', 'servicesGrid', 'testimonials', 'contact', 'footer'],
    nav: ['Inicio', 'Colección', 'Servicios', 'Contacto'], navCta: 'Reservar examen',
    eyebrow: 'Óptica · Lima', h1: 'Ve el mundo con la mejor claridad', sub: 'Monturas de diseño, lentes de alta tecnología y exámenes de la vista gratuitos con tu compra.',
    cta1: 'Ver colección', cta2: 'Examen de vista', heroPills: ['Examen gratis', 'Garantía de un año'],
    stats: [{ n: '18 años', l: 'de experiencia' }, { n: '500+', l: 'modelos de montura' }, { n: 'Gratis', l: 'examen de vista' }, { n: '4.8★', l: 'satisfacción' }],
    cardsEyebrow: 'Colección', cardsTitle: 'Monturas para cada estilo', cardsCta: 'Ver modelo',
    cards: [{ tag: 'Nuevo', t: 'Línea Clásica', d: 'Monturas atemporales de acetato premium', p: 'Desde S/ 199' }, { tag: 'Tendencia', t: 'Línea Urbana', d: 'Diseños modernos y ligeros para el día a día', p: 'Desde S/ 249' }, { tag: 'Premium', t: 'Línea Titanio', d: 'Resistencia y elegancia ultraligera', p: 'Desde S/ 399' }, { t: 'Lentes de sol', d: 'Protección UV con estilo, polarizados', p: 'Desde S/ 159' }, { t: 'Línea Infantil', d: 'Resistentes y divertidas para los más pequeños', p: 'Desde S/ 149' }, { t: 'Lentes de contacto', d: 'Mensuales y diarios de las mejores marcas', p: 'Desde S/ 89' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Más que una óptica',
    services: [{ t: 'Examen de vista', d: 'Evaluación computarizada gratuita con tu compra.' }, { t: 'Lentes a medida', d: 'Antirreflejo, fotocromáticos y progresivos.' }, { t: 'Reparaciones', d: 'Ajustes y mantenimiento de tus monturas.' }],
    testiTitle: 'Clientes que ven mejor',
    testimonials: [{ q: 'Me hicieron el examen gratis y encontré la montura perfecta. Excelente atención.', n: 'Pedro Vela', r: 'Cliente' }, { q: 'Mis progresivos quedaron perfectos. Calidad y buen precio.', n: 'Marta Ochoa', r: 'Cliente' }, { q: 'Gran variedad de modelos y asesoría honesta. Recomendados.', n: 'Iván Castro', r: 'Cliente' }],
    contactTitle: 'Visítanos', contactSub: 'Reserva tu examen de vista gratuito hoy.',
    phone: '+51 1 445 7788', address: 'Av. La Marina 2100, San Miguel, Lima', hours: 'Lun–Dom · 10:00 – 21:00', contactCta: 'Reservar examen', email: 'contacto@visionclara.pe',
    footerAbout: 'Óptica con 18 años de experiencia. Monturas de diseño y exámenes de vista gratuitos.',
    whatsappHref: 'https://wa.me/5114457788',
    pexels: { hero: 'eyewear glasses optical store', cards: ['eyeglasses frames', 'modern glasses', 'titanium eyewear', 'sunglasses fashion', 'kids glasses', 'contact lenses'] },
  },

  /* Laboratorio clínico */
  {
    slug: 'laboratorio', category: CAT, label: 'Laboratorio clínico', brand: 'BioLab Análisis',
    fonts: { heading: 'Poppins', body: 'Inter' },
    palette: { primary: '#1AA0A0', secondary: '#102E3A', accent: '#58C0E0', bg: '#F4FAFB', text: '#16292F' },
    plan: ['nav', 'heroSplit', 'stats', 'servicesGrid', 'process', 'faq', 'contact', 'footer'],
    nav: ['Inicio', 'Análisis', 'Proceso', 'Contacto'], navCta: 'Reservar muestra',
    eyebrow: 'Laboratorio · Lima', h1: 'Resultados confiables, sin esperas', sub: 'Análisis clínicos con tecnología de punta y resultados en línea. Tomamos tu muestra a domicilio.',
    cta1: 'Reservar toma de muestra', cta2: 'Ver análisis', heroPills: ['Resultados en línea', 'Toma a domicilio'],
    stats: [{ n: '20 años', l: 'de trayectoria' }, { n: '500+', l: 'tipos de análisis' }, { n: '24h', l: 'resultados promedio' }, { n: 'ISO', l: 'certificados' }],
    servicesEyebrow: 'Análisis', servicesTitle: 'Cobertura completa de exámenes',
    services: [{ t: 'Hematología', d: 'Hemogramas y perfiles sanguíneos completos.' }, { t: 'Bioquímica', d: 'Glucosa, colesterol, perfil hepático y renal.' }, { t: 'Hormonas', d: 'Perfil tiroideo, reproductivo y más.' }, { t: 'Microbiología', d: 'Cultivos y detección de infecciones.' }, { t: 'Pruebas COVID', d: 'Antígeno y molecular con resultados rápidos.' }, { t: 'Chequeos preventivos', d: 'Paquetes integrales a precio especial.' }],
    processTitle: 'Cómo funciona',
    process: [{ t: 'Reserva', d: 'Agenda tu análisis por WhatsApp o web.' }, { t: 'Toma de muestra', d: 'En sede o a domicilio, con todas las medidas.' }, { t: 'Procesamiento', d: 'Analizamos con equipos certificados.' }, { t: 'Resultados', d: 'Los recibes en línea, listos para tu médico.' }],
    faqTitle: 'Preguntas frecuentes',
    faq: [{ q: '¿Hacen toma de muestra a domicilio?', a: 'Sí, llegamos a tu casa u oficina con cita previa.' }, { q: '¿En cuánto tiempo están los resultados?', a: 'La mayoría en 24 horas, disponibles en línea.' }, { q: '¿Necesito ayuno?', a: 'Depende del análisis; te indicamos al reservar.' }],
    contactTitle: 'Reserva tu análisis', contactSub: 'Atención en sede o a domicilio, cuando lo necesites.',
    phone: '+51 1 500 3030', address: 'Av. Brasil 1280, Jesús María, Lima', hours: 'Lun–Sáb · 6:30 – 19:00', contactCta: 'Reservar muestra', email: 'contacto@biolab.pe',
    footerAbout: 'Laboratorio clínico certificado con 20 años de trayectoria. Resultados confiables y rápidos.',
    whatsappHref: 'https://wa.me/5115003030',
    pexels: { hero: 'medical laboratory blood test', about: 'laboratory technician microscope' },
  },

  /* Fisioterapia / rehabilitación */
  {
    slug: 'fisioterapia', category: CAT, label: 'Fisioterapia / Rehabilitación', brand: 'ReActiva Fisioterapia',
    fonts: { heading: 'Sora', body: 'Inter' },
    palette: { primary: '#2E7CC4', secondary: '#16304A', accent: '#4FC2A8', bg: '#F5F9FC', text: '#1A2733' },
    plan: ['nav', 'heroSplit', 'stats', 'servicesGrid', 'process', 'testimonials', 'contact', 'footer'],
    nav: ['Inicio', 'Terapias', 'Proceso', 'Contacto'], navCta: 'Reservar evaluación',
    eyebrow: 'Fisioterapia · Lima', h1: 'Recupera tu movimiento sin dolor', sub: 'Rehabilitación física personalizada para que vuelvas a hacer lo que amas, más fuerte que antes.',
    cta1: 'Reserva tu evaluación', cta2: 'Ver terapias', heroPills: ['Plan personalizado', 'Atención a domicilio'],
    stats: [{ n: '10 años', l: 'rehabilitando' }, { n: '5,000+', l: 'pacientes recuperados' }, { n: '95%', l: 'mejoría reportada' }, { n: '4.9★', l: 'valoración' }],
    servicesEyebrow: 'Terapias', servicesTitle: 'Tratamientos para cada necesidad',
    services: [{ t: 'Rehabilitación deportiva', d: 'Recuperación de lesiones y prevención.' }, { t: 'Terapia de columna', d: 'Alivio de dolor lumbar y cervical.' }, { t: 'Post-operatorio', d: 'Recuperación guiada tras cirugías.' }, { t: 'Terapia geriátrica', d: 'Movilidad y bienestar para adultos mayores.' }, { t: 'Masoterapia', d: 'Masajes terapéuticos descontracturantes.' }, { t: 'Electroterapia', d: 'Tecnología para acelerar tu recuperación.' }],
    processTitle: 'Tu camino a la recuperación',
    process: [{ t: 'Evaluación', d: 'Diagnosticamos el origen de tu dolor.' }, { t: 'Plan a medida', d: 'Diseñamos tu tratamiento personalizado.' }, { t: 'Terapia', d: 'Sesiones guiadas con seguimiento constante.' }, { t: 'Alta', d: 'Te damos pautas para mantenerte bien.' }],
    testiTitle: 'Pacientes que volvieron a moverse',
    testimonials: [{ q: 'Tras mi operación de rodilla, me ayudaron a caminar de nuevo. Increíbles.', n: 'Gustavo Ñañez', r: 'Post-operatorio' }, { q: 'Mi dolor de espalda desapareció después de años. Mil gracias.', n: 'Elsa Romero', r: 'Terapia de columna' }, { q: 'Volví a correr maratones gracias a ellos. Profesionales de verdad.', n: 'Bruno Tello', r: 'Rehab deportiva' }],
    contactTitle: 'Reserva tu evaluación', contactSub: 'El primer paso para volver a moverte sin dolor.',
    phone: '+51 967 220 445', address: 'Av. Aviación 3120, San Borja, Lima', hours: 'Lun–Sáb · 7:00 – 20:00', contactCta: 'Reservar evaluación', email: 'hola@reactiva.pe',
    footerAbout: 'Centro de fisioterapia y rehabilitación en San Borja. Recupera tu movimiento con un plan a tu medida.',
    whatsappHref: 'https://wa.me/51967220445',
    pexels: { hero: 'physiotherapy rehabilitation patient', about: 'physiotherapist treatment session' },
  },

  /* Nutrición */
  {
    slug: 'nutricion', category: CAT, label: 'Nutrición', brand: 'Nutre Bien',
    fonts: { heading: 'Poppins', body: 'Inter' },
    palette: { primary: '#5BA02E', secondary: '#2A3A1E', accent: '#E0A93C', bg: '#F8FBF3', text: '#232A1A' },
    plan: ['nav', 'heroSplit', 'stats', 'servicesGrid', 'featureSplit', 'pricing', 'testimonials', 'contact', 'footer'],
    nav: ['Inicio', 'Servicios', 'Nosotros', 'Planes', 'Contacto'], navCta: 'Reservar consulta',
    eyebrow: 'Nutrición · Lima', h1: 'Come bien, vive mejor', sub: 'Planes de nutrición personalizados que sí se adaptan a tu vida. Sin dietas imposibles, con resultados reales.',
    cta1: 'Reserva tu consulta', cta2: 'Ver planes', heroPills: ['Plan a tu medida', 'Seguimiento online'],
    stats: [{ n: '8 años', l: 'transformando hábitos' }, { n: '3,000+', l: 'metas alcanzadas' }, { n: '100%', l: 'personalizado' }, { n: '4.9★', l: 'resultados' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Nutrición para cada objetivo',
    services: [{ t: 'Pérdida de peso', d: 'Baja de forma saludable y sostenible.' }, { t: 'Nutrición deportiva', d: 'Potencia tu rendimiento y recuperación.' }, { t: 'Nutrición clínica', d: 'Diabetes, colesterol y condiciones especiales.' }, { t: 'Embarazo y lactancia', d: 'Alimentación segura para mamá y bebé.' }],
    aboutTitle: 'No es una dieta, es un estilo de vida', aboutBody: 'Olvídate de pasar hambre. Diseñamos planes con comida real, rica y peruana, que puedes mantener en el tiempo. Te acompañamos con seguimiento constante para que los resultados lleguen y se queden.',
    aboutBullets: ['Planes con comida que te gusta', 'Seguimiento semanal por WhatsApp', 'Recetas y listas de compra incluidas'],
    pricingTitle: 'Elige tu plan',
    pricing: [{ name: 'Consulta única', price: 'S/ 120', per: '', feats: ['Evaluación completa', 'Plan personalizado', 'Lista de compras'], cta: 'Reservar' }, { name: 'Plan mensual', price: 'S/ 320', per: '/mes', feats: ['4 consultas al mes', 'Seguimiento por WhatsApp', 'Ajustes de plan', 'Recetario exclusivo'], featured: true, cta: 'Empezar' }, { name: 'Plan trimestral', price: 'S/ 850', per: '/3 meses', feats: ['Todo el plan mensual', 'Mejor precio', 'Mediciones de control'], cta: 'Empezar' }],
    testiTitle: 'Transformaciones reales',
    testimonials: [{ q: 'Bajé 12 kilos sin pasar hambre y aprendí a comer. Lo mejor que hice.', n: 'Carla Núñez', r: 'Plan mensual' }, { q: 'Mejoró mi colesterol y mi energía. Comida rica y sana, increíble.', n: 'Raúl Méndez', r: 'Nutrición clínica' }, { q: 'Como deportista, mi rendimiento subió un montón. Recomendadísima.', n: 'Sergio Paz', r: 'Nutrición deportiva' }],
    contactTitle: 'Reserva tu consulta', contactSub: 'Empieza hoy tu cambio hacia una vida más saludable.',
    phone: '+51 954 667 220', address: 'Av. Conquistadores 850, San Isidro, Lima', hours: 'Lun–Sáb · 8:00 – 19:00', contactCta: 'Reservar consulta', email: 'hola@nutrebien.pe',
    footerAbout: 'Nutrición personalizada en Lima. Comida real, resultados reales y acompañamiento constante.',
    whatsappHref: 'https://wa.me/51954667220',
    pexels: { hero: 'healthy food nutrition bowl', about: 'nutritionist healthy meal planning' },
  },

  /* Medicina estética / spa */
  {
    slug: 'estetica', category: CAT, label: 'Medicina estética / Spa', brand: 'Lumière Estética',
    fonts: { heading: 'Cormorant Garamond', body: 'Jost' },
    palette: { primary: '#C49A6C', secondary: '#2E2620', accent: '#D8B08C', bg: '#FBF7F2', text: '#2A2420' },
    plan: ['nav', 'heroFullBg', 'stats', 'servicesGrid', 'gallery', 'pricing', 'testimonials', 'contact', 'footer'],
    nav: ['Inicio', 'Tratamientos', 'Galería', 'Planes', 'Contacto'], navCta: 'Reservar cita',
    eyebrow: 'Medicina estética', h1: 'Realza tu belleza natural', sub: 'Tratamientos faciales y corporales de última generación, en un espacio pensado para tu bienestar.',
    cta1: 'Reserva tu cita', cta2: 'Ver tratamientos',
    stats: [{ n: '12 años', l: 'de experiencia' }, { n: '6,000+', l: 'clientas felices' }, { n: '30+', l: 'tratamientos' }, { n: '4.9★', l: 'valoración' }],
    servicesEyebrow: 'Tratamientos', servicesTitle: 'Belleza con respaldo profesional',
    services: [{ t: 'Limpieza facial profunda', d: 'Piel renovada, luminosa y sana.' }, { t: 'Rejuvenecimiento', d: 'Tratamientos antiedad de eficacia comprobada.' }, { t: 'Modelado corporal', d: 'Reducción y tonificación sin cirugía.' }, { t: 'Depilación láser', d: 'Resultados duraderos y seguros.' }, { t: 'Tratamientos capilares', d: 'Fortalece y revitaliza tu cabello.' }, { t: 'Masajes y spa', d: 'Relájate y desconéctate del estrés.' }],
    galleryEyebrow: 'Nuestro espacio', galleryTitle: 'Un oasis de bienestar',
    pricingTitle: 'Paquetes destacados',
    pricing: [{ name: 'Facial Glow', price: 'S/ 150', per: '/sesión', feats: ['Limpieza profunda', 'Hidratación', 'Masaje facial'], cta: 'Reservar' }, { name: 'Pack Renovación', price: 'S/ 590', per: '/4 sesiones', feats: ['Limpieza + rejuvenecimiento', 'Plan personalizado', 'Productos incluidos', 'Mejor precio'], featured: true, cta: 'Reservar' }, { name: 'Spa Relax', price: 'S/ 220', per: '/sesión', feats: ['Masaje corporal', 'Aromaterapia', 'Circuito de relax'], cta: 'Reservar' }],
    testiTitle: 'Lo que dicen nuestras clientas',
    testimonials: [{ q: 'Mi piel cambió por completo. El trato es espectacular y muy profesional.', n: 'Fiorella Ramos', r: 'Cliente' }, { q: 'El mejor spa de Lima. Salgo renovada cada vez que voy.', n: 'Milagros León', r: 'Cliente frecuente' }, { q: 'La depilación láser me cambió la vida. Resultados increíbles.', n: 'Gabriela Soto', r: 'Cliente' }],
    contactTitle: 'Reserva tu cita', contactSub: 'Regálate un momento para ti. Te esperamos.',
    phone: '+51 962 110 778', address: 'Av. El Polo 740, Surco, Lima', hours: 'Lun–Sáb · 10:00 – 20:00', contactCta: 'Reservar cita', email: 'citas@lumiere.pe',
    footerAbout: 'Centro de medicina estética y spa en Surco. Realza tu belleza natural en manos expertas.',
    whatsappHref: 'https://wa.me/51962110778',
    pexels: { hero: 'spa facial treatment beauty', gallery: ['spa treatment room', 'facial skincare', 'massage spa relax', 'beauty clinic modern', 'woman skincare glow', 'spa stones candles'] },
  },
];
