/* TECNOLOGÍA — 3 rubros. */
const CAT = 'Tecnología';

module.exports = [
  /* Software / desarrollo */
  {
    slug: 'software', category: CAT, label: 'Software / Desarrollo', brand: 'Codek Software',
    fonts: { heading: 'Sora', body: 'Inter' },
    palette: { primary: '#6D3FE0', secondary: '#1E1A3A', accent: '#22D3EE', bg: '#FAF8FF', text: '#1F1B2E' },
    plan: ['nav', 'heroSplit', 'stats', 'servicesGrid', 'process', 'cards', 'testimonials', 'ctaBanner', 'contact', 'footer'],
    nav: ['Inicio', 'Servicios', 'Proceso', 'Contacto'], navCta: 'Cuéntanos tu idea',
    eyebrow: 'Software · Perú', h1: 'Construimos el software que tu empresa necesita', sub: 'Desarrollo de aplicaciones web y móviles a la medida. Transformamos tus procesos en tecnología que genera resultados.',
    cta1: 'Cuéntanos tu idea', cta2: 'Ver servicios', heroPills: ['Equipo senior', 'Metodología ágil'],
    stats: [{ n: '120+', l: 'proyectos entregados' }, { n: '10 años', l: 'desarrollando' }, { n: '98%', l: 'clientes que repiten' }, { n: '4.9★', l: 'satisfacción' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Soluciones de software a medida',
    services: [{ t: 'Aplicaciones web', d: 'Sistemas y plataformas escalables y seguras.' }, { t: 'Apps móviles', d: 'iOS y Android nativas o híbridas.' }, { t: 'E-commerce', d: 'Tiendas online que venden de verdad.' }, { t: 'Integraciones y APIs', d: 'Conectamos tus sistemas y servicios.' }, { t: 'Software empresarial', d: 'ERP, CRM y herramientas a tu medida.' }, { t: 'Mantenimiento y soporte', d: 'Tu software siempre actualizado y estable.' }],
    processTitle: 'Cómo trabajamos',
    process: [{ t: 'Descubrimiento', d: 'Entendemos tu negocio y objetivos.' }, { t: 'Diseño', d: 'Definimos UX, arquitectura y alcance.' }, { t: 'Desarrollo ágil', d: 'Construimos en sprints con entregas continuas.' }, { t: 'Lanzamiento', d: 'Desplegamos y te acompañamos.' }],
    cardsEyebrow: 'Casos', cardsTitle: 'Proyectos que entregamos', cardsCta: 'Ver caso',
    cards: [{ tag: 'Web App', t: 'Plataforma logística', d: 'Sistema de gestión y rastreo de flota', p: '+40% eficiencia' }, { tag: 'Mobile', t: 'App de delivery', d: 'Pedidos y pagos para cadena de comida', p: '50k descargas' }, { tag: 'E-commerce', t: 'Tienda online', d: 'Marketplace con pasarela de pago', p: 'x3 ventas' }],
    testiTitle: 'Clientes que confían en nuestra tecnología',
    testimonials: [{ q: 'Desarrollaron nuestro sistema a medida y transformó la operación. Brutales.', n: 'Gerencia, LogiPerú', r: 'Cliente' }, { q: 'La app superó lo que imaginábamos. Equipo serio y muy capaz.', n: 'FoodApp', r: 'Cliente' }, { q: 'Profesionales, cumplidos y siempre disponibles. Un gran socio tecnológico.', n: 'RetailX', r: 'Cliente' }],
    ctaTitle: '¿Tienes un proyecto en mente?', ctaSub: 'Escríbenos por WhatsApp y cuéntanos tu idea. La asesoría es gratis.',
    contactTitle: 'Cuéntanos tu idea', contactSub: 'Conversemos sobre tu proyecto y cómo hacerlo realidad.',
    phone: '+51 940 330 110', address: 'Av. El Derby 254, Surco, Lima', hours: 'Lun–Vie · 9:00 – 18:00', contactCta: 'Agendar reunión', email: 'hola@codek.pe',
    footerAbout: 'Empresa de desarrollo de software en Lima. Apps web y móviles a la medida con metodología ágil.',
    whatsappHref: 'https://wa.me/51940330110',
    pexels: { hero: 'software development team coding', cards: ['logistics dashboard app', 'mobile app delivery', 'ecommerce online shopping'] },
  },

  /* Soporte técnico / IT */
  {
    slug: 'soporte', category: CAT, label: 'Soporte técnico / IT', brand: 'TecnoSoporte',
    fonts: { heading: 'Sora', body: 'Inter' },
    palette: { primary: '#2563EB', secondary: '#0E1A33', accent: '#22D3EE', bg: '#F5F8FD', text: '#16202E' },
    plan: ['nav', 'heroSplit', 'stats', 'servicesGrid', 'process', 'pricing', 'testimonials', 'contact', 'footer'],
    nav: ['Inicio', 'Servicios', 'Proceso', 'Planes', 'Contacto'], navCta: 'Solicita soporte',
    eyebrow: 'Soporte IT · Lima', h1: 'Tu tecnología siempre funcionando', sub: 'Soporte técnico y gestión de TI para empresas. Resolvemos rápido para que tu operación nunca se detenga.',
    cta1: 'Solicita soporte', cta2: 'Ver servicios', heroPills: ['Respuesta inmediata', 'Soporte remoto y en sitio'],
    stats: [{ n: '300+', l: 'empresas atendidas' }, { n: '< 2h', l: 'tiempo de respuesta' }, { n: '99.9%', l: 'uptime gestionado' }, { n: '4.9★', l: 'clientes' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Soporte tecnológico integral',
    services: [{ t: 'Soporte de equipos', d: 'PCs, laptops, impresoras y periféricos.' }, { t: 'Redes y servidores', d: 'Instalación, configuración y monitoreo.' }, { t: 'Seguridad informática', d: 'Antivirus, backups y protección de datos.' }, { t: 'Soporte en la nube', d: 'Microsoft 365, Google Workspace y más.' }, { t: 'Mantenimiento preventivo', d: 'Evitamos fallas antes de que ocurran.' }, { t: 'Help desk', d: 'Mesa de ayuda para tu equipo.' }],
    processTitle: 'Cómo te ayudamos',
    process: [{ t: 'Reportas', d: 'Nos contactas por el canal que prefieras.' }, { t: 'Diagnóstico', d: 'Identificamos el problema rápido.' }, { t: 'Solución', d: 'Resolvemos remoto o en sitio.' }, { t: 'Prevención', d: 'Te dejamos recomendaciones para evitarlo.' }],
    pricingTitle: 'Planes de soporte',
    pricing: [{ name: 'Por incidencia', price: 'S/ 90', per: '/visita', feats: ['Atención puntual', 'Soporte remoto o en sitio', 'Diagnóstico incluido'], cta: 'Solicitar' }, { name: 'Plan Empresa', price: 'S/ 690', per: '/mes', feats: ['Soporte ilimitado', 'Monitoreo proactivo', 'Mantenimiento mensual', 'Respuesta prioritaria'], featured: true, cta: 'Contratar' }, { name: 'Plan Pyme', price: 'S/ 290', per: '/mes', feats: ['Hasta 10 equipos', 'Soporte remoto', 'Backups gestionados'], cta: 'Contratar' }],
    testiTitle: 'Empresas que confían su TI',
    testimonials: [{ q: 'Resuelven rapidísimo. Nuestra operación nunca se detiene gracias a ellos.', n: 'Estudio Contable RB', r: 'Cliente' }, { q: 'Profesionales y siempre disponibles. Nos dan total tranquilidad.', n: 'Clínica Dental Sur', r: 'Cliente' }, { q: 'Migraron nuestros sistemas a la nube sin un solo problema. Top.', n: 'Comercial JK', r: 'Cliente' }],
    contactTitle: 'Solicita soporte', contactSub: 'Cuéntanos qué necesitas y te respondemos al instante.',
    phone: '+51 945 110 440', address: 'Av. Arenales 1500, Lince, Lima', hours: 'Lun–Sáb · 8:00 – 20:00', contactCta: 'Solicitar soporte', email: 'soporte@tecnosoporte.pe',
    footerAbout: 'Soporte técnico y gestión de TI para empresas en Lima. Resolvemos rápido para que nunca te detengas.',
    whatsappHref: 'https://wa.me/51945110440',
    pexels: { hero: 'it support technician computer', about: 'technician fixing computer server' },
  },

  /* Agencia digital */
  {
    slug: 'agencia', category: CAT, label: 'Agencia digital', brand: 'Nova Digital',
    fonts: { heading: 'Sora', body: 'Inter' },
    palette: { primary: '#E0457B', secondary: '#2A1422', accent: '#4FC2A8', bg: '#FBF5F8', text: '#2A1A24' },
    plan: ['nav', 'heroSplit', 'stats', 'servicesGrid', 'cards', 'process', 'testimonials', 'ctaBanner', 'contact', 'footer'],
    nav: ['Inicio', 'Servicios', 'Casos', 'Contacto'], navCta: 'Cotiza tu proyecto',
    eyebrow: 'Agencia digital · Lima', h1: 'Llevamos tu negocio al mundo digital', sub: 'Web, e-commerce, branding y performance. Todo lo que tu marca necesita para crecer en internet, en un solo lugar.',
    cta1: 'Cotiza tu proyecto', cta2: 'Ver casos', heroPills: ['Estrategia 360°', 'Resultados medibles'],
    stats: [{ n: '200+', l: 'proyectos digitales' }, { n: '9 años', l: 'de experiencia' }, { n: '+180%', l: 'crecimiento promedio' }, { n: '4.9★', l: 'clientes' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Tu socio digital completo',
    services: [{ t: 'Diseño y desarrollo web', d: 'Sitios y landing pages que convierten.' }, { t: 'E-commerce', d: 'Tiendas online listas para vender.' }, { t: 'Branding e identidad', d: 'Una marca memorable y coherente.' }, { t: 'Performance & ads', d: 'Campañas que generan clientes reales.' }, { t: 'SEO', d: 'Posiciona tu web en los primeros lugares.' }, { t: 'Contenido y redes', d: 'Comunidad y contenido que conecta.' }],
    cardsEyebrow: 'Casos', cardsTitle: 'Marcas que despegaron', cardsCta: 'Ver caso',
    cards: [{ tag: 'Web', t: 'Sitio corporativo', d: 'Rediseño que duplicó los contactos', p: '+120% leads' }, { tag: 'E-commerce', t: 'Tienda de belleza', d: 'Lanzamiento y campañas de venta', p: 'x4 ventas' }, { tag: 'Branding', t: 'Marca de alimentos', d: 'Identidad completa y posicionamiento', p: '+90% reconocimiento' }],
    processTitle: 'Cómo trabajamos',
    process: [{ t: 'Estrategia', d: 'Analizamos tu marca y objetivos.' }, { t: 'Creación', d: 'Diseñamos y desarrollamos tu proyecto.' }, { t: 'Lanzamiento', d: 'Publicamos y activamos campañas.' }, { t: 'Crecimiento', d: 'Medimos y optimizamos resultados.' }],
    testiTitle: 'Lo que logran nuestros clientes',
    testimonials: [{ q: 'Rediseñaron nuestra web y los contactos se dispararon. Excelente equipo.', n: 'Constructora MV', r: 'Cliente' }, { q: 'Lanzaron mi tienda online y las ventas crecieron como nunca. Brutales.', n: 'BellaCosmetics', r: 'Cliente' }, { q: 'Entienden de negocio, no solo de diseño. Resultados reales.', n: 'Alimentos Frescos', r: 'Cliente' }],
    ctaTitle: '¿Hacemos crecer tu marca?', ctaSub: 'Escríbenos por WhatsApp y cotiza tu proyecto digital sin compromiso.',
    contactTitle: 'Cotiza tu proyecto', contactSub: 'Cuéntanos tu objetivo y diseñamos tu estrategia digital.',
    phone: '+51 951 220 770', address: 'Av. La Encalada 1420, Surco, Lima', hours: 'Lun–Vie · 9:00 – 19:00', contactCta: 'Cotizar ahora', email: 'hola@novadigital.pe',
    footerAbout: 'Agencia digital en Lima. Web, e-commerce, branding y performance para que tu marca crezca online.',
    whatsappHref: 'https://wa.me/51951220770',
    pexels: { hero: 'digital agency creative team office', cards: ['corporate website design', 'beauty ecommerce online', 'food brand packaging'] },
  },
];
