/* TURISMO Y EVENTOS — 4 rubros. */
const CAT = 'Turismo y eventos';

module.exports = [
  /* Agencia de viajes */
  {
    slug: 'viajes', category: CAT, label: 'Agencia de viajes', brand: 'Andes Travel',
    fonts: { heading: 'Sora', body: 'Inter' },
    palette: { primary: '#1E9BB0', secondary: '#14333A', accent: '#F0A82E', bg: '#F4FBFB', text: '#16292F' },
    plan: ['nav', 'heroFullBg', 'stats', 'cards', 'servicesGrid', 'testimonials', 'ctaBanner', 'contact', 'footer'],
    nav: ['Inicio', 'Destinos', 'Servicios', 'Contacto'], navCta: 'Reserva tu viaje',
    eyebrow: 'Agencia de viajes · Perú', h1: 'Vive el viaje de tus sueños', sub: 'Paquetes turísticos nacionales e internacionales, tours y full days. Tú solo disfruta, nosotros nos encargamos de todo.',
    cta1: 'Reserva tu viaje', cta2: 'Ver destinos',
    stats: [{ n: '15,000+', l: 'viajeros felices' }, { n: '50+', l: 'destinos' }, { n: '16 años', l: 'creando experiencias' }, { n: '4.9★', l: 'valoración' }],
    cardsEyebrow: 'Destinos', cardsTitle: 'Paquetes destacados', cardsCta: 'Ver paquete',
    cards: [{ tag: 'Top', t: 'Cusco & Machu Picchu', d: '4 días / 3 noches · hotel + tours', p: 'Desde S/ 1,290' }, { tag: 'Playa', t: 'Norte Peruano', d: 'Máncora y Punta Sal · 5 días', p: 'Desde S/ 1,490' }, { t: 'Selva Amazónica', d: 'Iquitos o Tarapoto · aventura', p: 'Desde S/ 1,190' }, { tag: 'Internacional', t: 'Cancún All Inclusive', d: '6 días · vuelo + hotel + comidas', p: 'Desde US$ 990' }, { t: 'Arequipa & Colca', d: '3 días · ciudad blanca y cañón', p: 'Desde S/ 890' }, { t: 'Full days', d: 'Paracas, Ica y más, en un día', p: 'Desde S/ 159' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Todo para tu viaje',
    services: [{ t: 'Paquetes a medida', d: 'Diseñamos el viaje exacto que quieres.' }, { t: 'Boletos aéreos', d: 'Los mejores precios en vuelos.' }, { t: 'Hoteles y traslados', d: 'Alojamiento y transporte resueltos.' }],
    ctaTitle: '¿A dónde quieres ir?', ctaSub: 'Escríbenos por WhatsApp y armamos tu viaje ideal hoy mismo.',
    contactTitle: 'Reserva tu viaje', contactSub: 'Cuéntanos tu destino soñado y lo hacemos realidad.',
    phone: '+51 1 433 9090', address: 'Av. Larco 1010, Miraflores, Lima', hours: 'Lun–Sáb · 9:00 – 19:00', contactCta: 'Reservar viaje', email: 'reservas@andestravel.pe',
    footerAbout: 'Agencia de viajes en Lima. Paquetes, tours y full days nacionales e internacionales a tu medida.',
    whatsappHref: 'https://wa.me/5114339090',
    pexels: { hero: 'machu picchu travel peru landscape', cards: ['machu picchu cusco', 'beach tropical mancora', 'amazon jungle river', 'cancun beach resort', 'arequipa colca canyon', 'paracas ica desert'] },
  },

  /* Hotel / hospedaje */
  {
    slug: 'hotel', category: CAT, label: 'Hotel / Hospedaje', brand: 'Hotel Costa Serena',
    fonts: { heading: 'Cormorant Garamond', body: 'Jost' },
    palette: { primary: '#2A5D6E', secondary: '#16282E', accent: '#C8A45C', bg: '#F7F6F2', text: '#1F2A2E' },
    plan: ['nav', 'heroFullBg', 'stats', 'servicesGrid', 'cards', 'gallery', 'testimonials', 'contact', 'footer'],
    nav: ['Inicio', 'Servicios', 'Habitaciones', 'Galería', 'Contacto'], navCta: 'Reservar ahora',
    eyebrow: 'Hotel · Lima', h1: 'Tu descanso merece lo mejor', sub: 'Un hotel donde la comodidad se encuentra con la elegancia. Habitaciones impecables, atención cálida y la mejor ubicación.',
    cta1: 'Reserva ahora', cta2: 'Ver habitaciones',
    stats: [{ n: '4.8★', l: 'en plataformas' }, { n: '60', l: 'habitaciones' }, { n: '24h', l: 'recepción' }, { n: '100%', l: 'ubicación céntrica' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Todo pensado para ti',
    services: [{ t: 'Desayuno buffet', d: 'Variado y delicioso, incluido en tu estadía.' }, { t: 'WiFi de alta velocidad', d: 'Conéctate en todo el hotel sin límites.' }, { t: 'Restaurante & bar', d: 'Gastronomía de primer nivel a cualquier hora.' }, { t: 'Estacionamiento', d: 'Seguro y disponible para huéspedes.' }, { t: 'Sala de eventos', d: 'Espacios para reuniones y celebraciones.' }, { t: 'Room service', d: 'Atención en tu habitación las 24 horas.' }],
    cardsEyebrow: 'Habitaciones', cardsTitle: 'Elige tu espacio ideal', cardsCta: 'Reservar',
    cards: [{ tag: 'Popular', t: 'Habitación Estándar', d: 'Cama queen, baño privado, todo lo esencial', p: 'Desde S/ 220' }, { tag: 'Recomendada', t: 'Habitación Superior', d: 'Más espacio, vista a la ciudad', p: 'Desde S/ 320' }, { t: 'Suite Junior', d: 'Sala de estar y comodidades premium', p: 'Desde S/ 480' }],
    galleryEyebrow: 'Galería', galleryTitle: 'Conoce nuestro hotel',
    testiTitle: 'Lo que dicen nuestros huéspedes',
    testimonials: [{ q: 'Habitaciones impecables y atención de cinco estrellas. Volveremos seguro.', n: 'Ricardo Fuentes', r: 'Huésped' }, { q: 'La ubicación es perfecta y el desayuno, espectacular. Muy recomendado.', n: 'Laura Mejía', r: 'Huésped' }, { q: 'Todo limpio, cómodo y con un personal amabilísimo. Excelente estadía.', n: 'Tomás Bravo', r: 'Huésped' }],
    contactTitle: 'Reserva tu estadía', contactSub: 'Consulta disponibilidad y asegura tu habitación.',
    phone: '+51 1 421 5050', address: 'Av. José Pardo 620, Miraflores, Lima', hours: 'Recepción 24 horas', contactCta: 'Reservar ahora', email: 'reservas@costaserena.pe',
    footerAbout: 'Hotel en Miraflores. Comodidad, elegancia y la mejor ubicación para tu descanso o viaje de negocios.',
    whatsappHref: 'https://wa.me/5114215050',
    pexels: { hero: 'luxury hotel lobby elegant', cards: ['hotel room standard', 'hotel room superior view', 'hotel suite luxury'], gallery: ['hotel lobby', 'hotel pool', 'hotel restaurant', 'hotel room bed', 'hotel bathroom luxury', 'hotel exterior'] },
  },

  /* Organización de eventos / wedding */
  {
    slug: 'eventos', category: CAT, label: 'Organización de eventos', brand: 'Momentos Eventos',
    fonts: { heading: 'Cormorant Garamond', body: 'Jost' },
    palette: { primary: '#B0879C', secondary: '#2A2024', accent: '#C8A45C', bg: '#FAF6F4', text: '#2A2228' },
    plan: ['nav', 'heroFullBg', 'stats', 'servicesGrid', 'gallery', 'testimonials', 'ctaBanner', 'contact', 'footer'],
    nav: ['Inicio', 'Servicios', 'Galería', 'Contacto'], navCta: 'Planifiquemos',
    eyebrow: 'Eventos & Bodas', h1: 'Hacemos realidad el evento que sueñas', sub: 'Bodas, quinceañeros y eventos corporativos planificados al detalle. Tú vives el momento, nosotros cuidamos todo lo demás.',
    cta1: 'Planifiquemos tu evento', cta2: 'Ver galería',
    stats: [{ n: '600+', l: 'eventos producidos' }, { n: '12 años', l: 'creando momentos' }, { n: '100%', l: 'a tu medida' }, { n: '4.9★', l: 'parejas felices' }],
    servicesEyebrow: 'Servicios', servicesTitle: 'Producimos cada detalle',
    services: [{ t: 'Bodas', d: 'Wedding planning integral para tu gran día.' }, { t: 'Quinceañeros', d: 'Una fiesta de ensueño para sus 15.' }, { t: 'Eventos corporativos', d: 'Lanzamientos, galas y celebraciones de empresa.' }, { t: 'Decoración y ambientación', d: 'Diseño floral, iluminación y mobiliario.' }, { t: 'Catering y barra', d: 'Gastronomía y tragos para tus invitados.' }, { t: 'Coordinación del día', d: 'Todo fluye perfecto mientras tú disfrutas.' }],
    galleryEyebrow: 'Galería', galleryTitle: 'Momentos que hemos creado',
    testiTitle: 'Celebraciones inolvidables',
    testimonials: [{ q: 'Nuestra boda fue perfecta, tal como la soñamos. No cambiaríamos nada.', n: 'Andrea & Luis', r: 'Boda' }, { q: 'Los 15 de mi hija fueron mágicos. Cada detalle estuvo cuidado.', n: 'Familia Rosales', r: 'Quinceañero' }, { q: 'Produjeron el evento de nuestra empresa de forma impecable. Profesionales.', n: 'Corporación VR', r: 'Evento corporativo' }],
    ctaTitle: '¿Tienes un evento en mente?', ctaSub: 'Cuéntanos tu idea por WhatsApp y empecemos a planificarlo.',
    contactTitle: 'Planifiquemos tu evento', contactSub: 'Cuéntanos qué celebras y diseñamos una propuesta a tu medida.',
    phone: '+51 956 880 110', address: 'Av. El Sol 340, La Molina, Lima', hours: 'Lun–Sáb · 10:00 – 19:00', contactCta: 'Solicitar propuesta', email: 'hola@momentoseventos.pe',
    footerAbout: 'Organización de bodas y eventos en Lima. Planificamos cada detalle para que vivas tu momento.',
    whatsappHref: 'https://wa.me/51956880110',
    pexels: { hero: 'wedding event decoration elegant', gallery: ['wedding ceremony decoration', 'event table setup elegant', 'wedding flowers centerpiece', 'party celebration lights', 'corporate event stage', 'wedding reception hall'] },
  },

  /* Fotografía / video */
  {
    slug: 'fotografia', category: CAT, label: 'Fotografía / Video', brand: 'Lente Studio',
    fonts: { heading: 'Space Grotesk', body: 'Inter' },
    palette: { primary: '#2A2A2A', secondary: '#16110E', accent: '#C0A062', bg: '#F6F5F2', text: '#1F1F1F' },
    plan: ['nav', 'heroMinimal', 'stats', 'gallery', 'servicesGrid', 'pricing', 'testimonials', 'contact', 'footer'],
    nav: ['Inicio', 'Portafolio', 'Servicios', 'Precios', 'Contacto'], navCta: 'Reservar sesión',
    eyebrow: 'Fotografía & Video', h1: 'Capturamos los momentos que importan', sub: 'Fotografía y video profesional para bodas, eventos, productos y marcas. Imágenes que cuentan tu historia.',
    cta1: 'Ver portafolio', cta2: 'Reservar sesión',
    stats: [{ n: '500+', l: 'proyectos' }, { n: '10 años', l: 'detrás del lente' }, { n: '100%', l: 'a tu estilo' }, { n: '4.9★', l: 'clientes' }],
    galleryEyebrow: 'Portafolio', galleryTitle: 'Nuestro trabajo',
    servicesEyebrow: 'Servicios', servicesTitle: 'Lo que capturamos',
    services: [{ t: 'Bodas y eventos', d: 'Cobertura completa de tu día especial.' }, { t: 'Sesiones de retrato', d: 'Personales, familiares y profesionales.' }, { t: 'Fotografía de producto', d: 'Imágenes que venden para tu marca.' }, { t: 'Video corporativo', d: 'Cuenta la historia de tu empresa.' }],
    pricingTitle: 'Paquetes',
    pricing: [{ name: 'Sesión Retrato', price: 'S/ 290', per: '', feats: ['1 hora de sesión', '15 fotos editadas', 'Galería digital'], cta: 'Reservar' }, { name: 'Boda Completa', price: 'S/ 2,490', per: '', feats: ['Cobertura todo el día', 'Foto + video', '300+ fotos editadas', 'Video highlights'], featured: true, cta: 'Reservar' }, { name: 'Producto / Marca', price: 'S/ 590', per: '', feats: ['Hasta 20 productos', 'Fondo profesional', 'Listas para e-commerce'], cta: 'Reservar' }],
    testiTitle: 'Clientes que confiaron su historia',
    testimonials: [{ q: 'Las fotos de nuestra boda son una obra de arte. Reviviremos ese día por siempre.', n: 'Camila & Andrés', r: 'Boda' }, { q: 'Las fotos de mis productos subieron mis ventas online. Calidad impresionante.', n: 'Tienda Origen', r: 'Cliente' }, { q: 'Profesionales, creativos y puntuales. El resultado superó todo.', n: 'Marcela Pinto', r: 'Sesión de retrato' }],
    contactTitle: 'Reserva tu sesión', contactSub: 'Cuéntanos tu proyecto y creamos algo memorable.',
    phone: '+51 945 110 770', address: 'Estudio en Barranco · Cobertura en todo Lima', hours: 'Lun–Sáb · 10:00 – 19:00', contactCta: 'Reservar sesión', email: 'hola@lentestudio.pe',
    footerAbout: 'Estudio de fotografía y video en Lima. Capturamos bodas, eventos, productos y marcas con estilo.',
    whatsappHref: 'https://wa.me/51945110770',
    pexels: { hero: 'photographer camera professional', gallery: ['wedding photography couple', 'portrait photography studio', 'product photography', 'event photography', 'photographer working', 'fashion photography'] },
  },
];
